//! `generate_foundation_md` — Rust port of `src/generators/foundation-md.ts`.
//!
//! Produces `FOUNDATION.md` from a parsed `foundation.json` (generic schema
//! v2.0.0) document. The output is **byte-for-byte identical** to the
//! TypeScript `generateFoundationMd` reference: the TS builds a `string[]`
//! and `join('\n')`s it, so we accumulate `Vec<String>` and `join("\n")`
//! the same way. Every section block ends by pushing an empty `String`, so
//! the joined output always ends in a single `\n` (matching the TS
//! `writeFile(foundationMdPath, markdown)` bytes — FOUNDATION.md ends with
//! `---\n`).
//!
//! ## Mermaid validation (Framing A)
//!
//! The TS generator calls `validateMermaidSyntax` (mermaid.parse() + jsdom)
//! on the auto-generated Bounded-Context Map (throwing on failure) and on
//! each per-context Event-Flow diagram (skipping the diagram when invalid).
//! Rust cannot run mermaid.parse(); per the documented convention in
//! `src/commands/add_diagram.rs`, we perform the same lightweight pure-string
//! pre-check that `src/utils/mermaid-validation.ts` runs *before* mermaid
//! (see [`super::foundation_md_util::validate_mermaid`]). The diagrams this
//! generator emits always pass that check, so the rendered output matches
//! the TS reference for every valid foundation.

use serde_json::Value;

use super::foundation_md_diagrams::{
    bounded_context_mermaid, context_event_flow_mermaid, items_for,
};
use super::foundation_md_util::{js_str, nonempty_array, truthy, validate_mermaid};

/// Render `FOUNDATION.md` from a parsed `foundation.json` value.
///
/// Returns `Err(message)` only when the auto-generated Bounded-Context Map
/// fails the lightweight Mermaid pre-check — mirroring the TS
/// `throw new Error('Mermaid validation failed: ...')`. The message is the
/// bare text the TS command surfaces as `error.message`.
pub fn generate_foundation_md(foundation: &Value) -> Result<String, String> {
    // Header with auto-generation warning.
    let mut sections: Vec<String> = vec![
        "<!-- THIS FILE IS AUTO-GENERATED FROM spec/foundation.json -->".to_string(),
        "<!-- DO NOT EDIT THIS FILE DIRECTLY -->".to_string(),
        "<!-- Edit spec/foundation.json and run: fspec generate-foundation-md -->".to_string(),
        String::new(),
    ];

    let project = foundation.get("project");

    // Project header.
    if truthy(project) && truthy(project.and_then(|p| p.get("name"))) {
        let name = js_str(project.and_then(|p| p.get("name")).unwrap_or(&Value::Null));
        sections.push(format!("# {name} Project Foundation"));
        sections.push(String::new());
    } else {
        sections.push("# Project Foundation".to_string());
        sections.push(String::new());
    }

    // Project Vision.
    if truthy(project) && truthy(project.and_then(|p| p.get("vision"))) {
        let vision = js_str(
            project
                .and_then(|p| p.get("vision"))
                .unwrap_or(&Value::Null),
        );
        sections.push("## Vision".to_string());
        sections.push(String::new());
        sections.push(vision);
        sections.push(String::new());
        sections.push("---".to_string());
        sections.push(String::new());
    }

    render_problem_space(foundation, &mut sections);
    render_solution_space(foundation, &mut sections);
    render_personas(foundation, &mut sections);
    render_architecture_diagrams(foundation, &mut sections);
    render_domain_architecture(foundation, &mut sections)?;

    Ok(sections.join("\n"))
}

/// Render the `## Problem Space` block. Mirrors the TS
/// `if (foundation.problemSpace && foundation.problemSpace.primaryProblem)`.
fn render_problem_space(foundation: &Value, sections: &mut Vec<String>) {
    let problem_space = foundation.get("problemSpace");
    let problem = problem_space.and_then(|ps| ps.get("primaryProblem"));
    if !(truthy(problem_space) && truthy(problem)) {
        return;
    }
    let problem = match problem {
        Some(p) => p,
        None => return,
    };

    sections.push("## Problem Space".to_string());
    sections.push(String::new());

    if truthy(problem.get("title")) {
        sections.push(format!(
            "### {}",
            js_str(problem.get("title").unwrap_or(&Value::Null))
        ));
        sections.push(String::new());
    }
    if truthy(problem.get("description")) {
        sections.push(js_str(problem.get("description").unwrap_or(&Value::Null)));
        sections.push(String::new());
    }
    if truthy(problem.get("impact")) {
        sections.push(format!(
            "**Impact:** {}",
            js_str(problem.get("impact").unwrap_or(&Value::Null))
        ));
        sections.push(String::new());
    }

    sections.push("---".to_string());
    sections.push(String::new());
}

/// Render the `## Solution Space` block. Mirrors `if (foundation.solutionSpace)`.
fn render_solution_space(foundation: &Value, sections: &mut Vec<String>) {
    let solution = match foundation.get("solutionSpace") {
        Some(s) if truthy(Some(s)) => s,
        _ => return,
    };

    sections.push("## Solution Space".to_string());
    sections.push(String::new());

    if truthy(solution.get("overview")) {
        sections.push("### Overview".to_string());
        sections.push(String::new());
        sections.push(js_str(solution.get("overview").unwrap_or(&Value::Null)));
        sections.push(String::new());
    }

    if let Some(capabilities) = nonempty_array(solution.get("capabilities")) {
        sections.push("### Capabilities".to_string());
        sections.push(String::new());
        for capability in capabilities {
            let has_name = truthy(capability.get("name"));
            let has_desc = truthy(capability.get("description"));
            if has_name && has_desc {
                sections.push(format!(
                    "- **{}**: {}",
                    js_str(capability.get("name").unwrap_or(&Value::Null)),
                    js_str(capability.get("description").unwrap_or(&Value::Null))
                ));
            } else if has_name {
                sections.push(format!(
                    "- **{}**",
                    js_str(capability.get("name").unwrap_or(&Value::Null))
                ));
            }
        }
        sections.push(String::new());
    }

    sections.push("---".to_string());
    sections.push(String::new());
}

/// Render the `## Personas` block. Mirrors `if (foundation.personas && length > 0)`.
fn render_personas(foundation: &Value, sections: &mut Vec<String>) {
    let personas = match nonempty_array(foundation.get("personas")) {
        Some(p) => p,
        None => return,
    };

    sections.push("## Personas".to_string());
    sections.push(String::new());

    for persona in personas {
        if truthy(persona.get("name")) {
            sections.push(format!(
                "### {}",
                js_str(persona.get("name").unwrap_or(&Value::Null))
            ));
            sections.push(String::new());
        }
        if truthy(persona.get("description")) {
            sections.push(js_str(persona.get("description").unwrap_or(&Value::Null)));
            sections.push(String::new());
        }
        if let Some(goals) = nonempty_array(persona.get("goals")) {
            sections.push("**Goals:**".to_string());
            for goal in goals {
                sections.push(format!("- {}", js_str(goal)));
            }
            sections.push(String::new());
        }
    }

    sections.push("---".to_string());
    sections.push(String::new());
}

/// Render the `## Architecture Diagrams` block. Mirrors
/// `if (foundation.architectureDiagrams && length > 0)`.
fn render_architecture_diagrams(foundation: &Value, sections: &mut Vec<String>) {
    let diagrams = match nonempty_array(foundation.get("architectureDiagrams")) {
        Some(d) => d,
        None => return,
    };

    sections.push("## Architecture Diagrams".to_string());
    sections.push(String::new());

    for diagram in diagrams {
        if truthy(diagram.get("title")) {
            sections.push(format!(
                "### {}",
                js_str(diagram.get("title").unwrap_or(&Value::Null))
            ));
            sections.push(String::new());
        }
        if truthy(diagram.get("description")) {
            sections.push(js_str(diagram.get("description").unwrap_or(&Value::Null)));
            sections.push(String::new());
        }
        if truthy(diagram.get("mermaidCode")) {
            sections.push("```mermaid".to_string());
            sections.push(js_str(diagram.get("mermaidCode").unwrap_or(&Value::Null)));
            sections.push("```".to_string());
            sections.push(String::new());
        }
    }

    sections.push("---".to_string());
    sections.push(String::new());
}

/// Render the `# Domain Architecture` block. Mirrors the TS
/// `if (foundation.eventStorm && foundation.eventStorm.items)` branch.
fn render_domain_architecture(
    foundation: &Value,
    sections: &mut Vec<String>,
) -> Result<(), String> {
    let items = foundation
        .get("eventStorm")
        .and_then(|es| es.get("items"))
        .and_then(Value::as_array);
    let items = match items {
        Some(a) => a,
        None => return Ok(()),
    };

    // Bounded contexts (not deleted), in document order.
    let bounded_contexts: Vec<&Value> = items
        .iter()
        .filter(|item| {
            item.get("type").and_then(Value::as_str) == Some("bounded_context")
                && !truthy(item.get("deleted"))
        })
        .collect();

    if bounded_contexts.is_empty() {
        return Ok(());
    }

    sections.push("# Domain Architecture".to_string());
    sections.push(String::new());

    // Bounded Contexts list.
    sections.push("## Bounded Contexts".to_string());
    sections.push(String::new());
    for context in &bounded_contexts {
        sections.push(format!(
            "- {}",
            js_str(context.get("text").unwrap_or(&Value::Null))
        ));
    }
    sections.push(String::new());

    // Bounded Context Map (Mermaid diagram).
    sections.push("## Bounded Context Map".to_string());
    sections.push(String::new());

    let mermaid_code = bounded_context_mermaid(&bounded_contexts);
    if let Err(e) = validate_mermaid(&mermaid_code) {
        return Err(format!("Mermaid validation failed: {e}"));
    }

    sections.push("```mermaid".to_string());
    sections.push(mermaid_code);
    sections.push("```".to_string());
    sections.push(String::new());

    // Bounded Context Sections (Aggregates, Events, Commands).
    for context in &bounded_contexts {
        sections.push(format!(
            "## {} Context",
            js_str(context.get("text").unwrap_or(&Value::Null))
        ));
        sections.push(String::new());

        let context_id = context.get("id").cloned().unwrap_or(Value::Null);

        // Event Flow diagram for this context.
        let event_flow = context_event_flow_mermaid(&context_id, foundation);
        if !event_flow.is_empty() && validate_mermaid(&event_flow).is_ok() {
            sections.push("### Event Flow".to_string());
            sections.push(String::new());
            sections.push("```mermaid".to_string());
            sections.push(event_flow);
            sections.push("```".to_string());
            sections.push(String::new());
        }

        render_context_items(
            foundation,
            &context_id,
            "aggregate",
            "**Aggregates:**",
            sections,
        );
        render_context_items(
            foundation,
            &context_id,
            "event",
            "**Domain Events:**",
            sections,
        );
        render_context_items(
            foundation,
            &context_id,
            "command",
            "**Commands:**",
            sections,
        );
    }

    sections.push("---".to_string());
    sections.push(String::new());

    Ok(())
}

/// Render an item list (aggregates/events/commands) for one bounded context.
/// Mirrors the TS `- ${item.text}${description}` pattern where `description`
/// is ` - ${item.description}` only when the key is present AND truthy.
fn render_context_items(
    foundation: &Value,
    context_id: &Value,
    item_type: &str,
    heading: &str,
    sections: &mut Vec<String>,
) {
    let matched = items_for(foundation, item_type, context_id);
    if matched.is_empty() {
        return;
    }
    sections.push(heading.to_string());
    for item in matched {
        let has_desc = item
            .as_object()
            .map(|o| o.contains_key("description"))
            .unwrap_or(false)
            && truthy(item.get("description"));
        let description = if has_desc {
            format!(
                " - {}",
                js_str(item.get("description").unwrap_or(&Value::Null))
            )
        } else {
            String::new()
        };
        sections.push(format!(
            "- {}{description}",
            js_str(item.get("text").unwrap_or(&Value::Null))
        ));
    }
    sections.push(String::new());
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
    use super::*;
    use serde_json::json;

    #[test]
    fn header_only_when_no_optional_sections() {
        let foundation = json!({
            "project": { "name": "Demo", "vision": "V" },
            "problemSpace": {},
            "solutionSpace": {}
        });
        let md = generate_foundation_md(&foundation).unwrap();
        assert!(md.starts_with("<!-- THIS FILE IS AUTO-GENERATED"));
        assert!(md.contains("# Demo Project Foundation"));
        assert!(md.contains("## Vision"));
        // Every rendered section ends with a trailing empty element, so the
        // `join("\n")` output always ends in a newline — matching the TS
        // `writeFile(..., markdown)` bytes (FOUNDATION.md ends with `---\n`).
        assert!(md.ends_with("---\n"));
    }

    #[test]
    fn fallback_header_when_no_project_name() {
        let foundation = json!({ "problemSpace": {}, "solutionSpace": {} });
        let md = generate_foundation_md(&foundation).unwrap();
        assert!(md.contains("# Project Foundation"));
        assert!(!md.contains("Project Foundation\n\n## Vision"));
    }
}
