//! session_bindings shape tests for the `codelet-napi` crate (RPC-043).
//!
//! Feature: spec/features/reduce-codelet-napi-to-thin-adapter-session-bindings-rs-update-cargo-toml.feature
//!
//! These tests codify the static shape of the new seven-sibling-module
//! split (session_bindings.rs + agent_loop.rs + persist.rs +
//! footer_poller.rs + bridges.rs + session_hooks.rs + interjection.rs)
//! that replaces the old monolithic
//! `rust/napi/src/session_manager.rs`. Each `#[test]` corresponds to
//! a single Gherkin scenario in the feature file; the `// @step`
//! comments below map each Gherkin step verbatim to the assertion that
//! enforces it.
//!
//! Pattern borrowed from `rust/sessions/tests/session_manager_shape.rs`
//! (RPC-040) and `rust/sessions/tests/handle_impl.rs` (RPC-042).
//!
//! These tests MUST FAIL until RPC-043 implementation lands. They are
//! the red phase of ACDD for this card.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};

// RPC-043 (disk-bloat fix): six tests in this file spawn nested
// `cargo build` / `cargo test --no-run` processes. They share three
// pieces of mutable state with each other:
//   1. `target/` — concurrent rustc workers race on .rlib outputs
//      under target/debug/deps/ and produce intermittent linker
//      errors when two cargo processes attempt the same link.
//   2. `rust/napi/index.d.ts` — regenerated by napi-derive on every
//      build. The noop build emits FEWER exports than the default
//      build because most #[napi] free functions are gated behind
//      `#[cfg(not(feature = "noop"))]`. If the noop build races with
//      `scenario_index_dts_is_byte_identical_to_pre_rpc043_baseline`
//      the dts-byte-identical scenario sees a truncated file and
//      reports phantom "removed exports" failures.
//   3. The workspace package cache lock at
//      `target/debug/.cargo-lock`, which cargo blocks on for several
//      minutes when multiple nested cargo processes race.
//
// Marking the six offending tests with `#[serial]` (via the
// `serial_test` crate, already a dev-dependency) serializes them
// among themselves while the other 48 tests continue to run in
// parallel — giving the best of both worlds: fast feedback for the
// pure-file-scan scenarios, race-free execution for the nested-cargo
// scenarios.
use serial_test::serial;

// =============================================================================
// Path & file helpers (shared by every scenario in this file).
// =============================================================================

/// codelet-napi crate root (one level above the tests dir).
fn napi_crate_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn napi_src() -> PathBuf {
    napi_crate_root().join("src")
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()))
}

/// Build a cargo `Command` that won't fill `target/debug/incremental/`
/// with multi-GB fingerprint trees. This is the disk-bloat fix
/// (RPC-043 retro): each nested `cargo build` / `cargo test --no-run`
/// invocation from within this test file writes its own incremental
/// cache for the napi + nanograph + arrow + datafusion + lance +
/// tantivy dep graph (~5-15 GB per profile/feature combination).
/// Forcing `CARGO_INCREMENTAL=0` keeps the .rlib outputs reachable for
/// reuse but skips the incremental fingerprint dirs entirely. The
/// user's interactive `cargo build` from the shell is unaffected
/// because the env var is scoped to the spawned child process.
fn cargo_cmd() -> std::process::Command {
    let mut cmd = std::process::Command::new(env!("CARGO"));
    cmd.env("CARGO_INCREMENTAL", "0");
    cmd
}

/// Strip `//`-style line comments so substring scans only see code.
fn strip_line_comments(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    for line in src.lines() {
        match line.find("//") {
            Some(pos) => {
                out.push_str(&line[..pos]);
                out.push('\n');
            }
            None => {
                out.push_str(line);
                out.push('\n');
            }
        }
    }
    out
}

/// Count occurrences of an `#[napi]` attribute immediately followed (on
/// the next line) by `pub fn` or `pub async fn` — i.e. free-function
/// wrappers. Excludes `#[napi(object)]`, `#[napi(constructor)]`,
/// `#[napi(getter)]`, etc.
fn count_napi_free_fn_wrappers(src: &str) -> usize {
    let mut count = 0usize;
    let lines: Vec<&str> = src.lines().collect();
    for (i, line) in lines.iter().enumerate() {
        let trimmed = line.trim_start();
        if trimmed == "#[napi]" {
            // Look at the next non-blank line for `pub fn` or `pub async fn`.
            for next in lines.iter().skip(i + 1) {
                let nt = next.trim_start();
                if nt.is_empty() {
                    continue;
                }
                if nt.starts_with("pub fn ")
                    || nt.starts_with("pub async fn ")
                    || nt.starts_with("pub(crate) fn ")
                    || nt.starts_with("pub(crate) async fn ")
                {
                    count += 1;
                }
                break;
            }
        }
    }
    count
}

// =============================================================================
// Scenario: codelet-napi/src/session_manager.rs no longer exists after the move
// =============================================================================

#[test]
fn scenario_session_manager_rs_no_longer_exists() {
    // @step Given the codelet workspace has the RPC-042 changes landed on main
    // @step When I run `ls rust/napi/src/session_manager.rs`
    // @step Then the command exits with a non-zero status
    // @step And stderr contains "No such file or directory"
    // @step And the file at "rust/napi/src/session_manager.rs" does not exist on disk
    let path = napi_src().join("session_manager.rs");
    assert!(
        !path.exists(),
        "RPC-043: rust/napi/src/session_manager.rs must be deleted; still present at {}",
        path.display()
    );
}

// =============================================================================
// Scenario: codelet-napi/src/ gains the seven new sibling modules
// =============================================================================

#[test]
fn scenario_seven_sibling_modules_exist() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I run `ls rust/napi/src/`
    // @step Then the listing includes "session_bindings.rs"
    // @step And the listing includes "agent_loop.rs"
    // @step And the listing includes "persist.rs"
    // @step And the listing includes "footer_poller.rs"
    // @step And the listing includes "bridges.rs"
    // @step And the listing includes "session_hooks.rs"
    // @step And the listing includes "interjection.rs"
    let src = napi_src();
    for name in [
        "session_bindings.rs",
        "agent_loop.rs",
        "persist.rs",
        "footer_poller.rs",
        "bridges.rs",
        "session_hooks.rs",
        "interjection.rs",
    ] {
        let path = src.join(name);
        assert!(
            path.exists(),
            "RPC-043: expected rust/napi/src/{name} to exist; missing"
        );
    }
}

// =============================================================================
// Scenario: lib.rs declares each new sibling module under the noop feature gate
// =============================================================================

#[test]
fn scenario_lib_rs_declares_each_sibling_module() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I open `rust/napi/src/lib.rs`
    let lib = read(&napi_src().join("lib.rs"));
    let stripped = strip_line_comments(&lib);

    // @step Then the file declares `pub mod session_bindings;` under `#[cfg(not(feature = "noop"))]`
    // @step And the file declares `pub mod agent_loop;` under `#[cfg(not(feature = "noop"))]`
    // @step And the file declares `pub mod persist;` under `#[cfg(not(feature = "noop"))]`
    // @step And the file declares `pub mod footer_poller;` under `#[cfg(not(feature = "noop"))]`
    // @step And the file declares `pub mod bridges;` under `#[cfg(not(feature = "noop"))]`
    // @step And the file declares `pub mod session_hooks;` under `#[cfg(not(feature = "noop"))]`
    // @step And the file declares `pub mod interjection;` under `#[cfg(not(feature = "noop"))]`
    for name in [
        "session_bindings",
        "agent_loop",
        "persist",
        "footer_poller",
        "bridges",
        "session_hooks",
        "interjection",
    ] {
        let decl_pub = format!("pub mod {name};");
        let decl_priv = format!("mod {name};");
        assert!(
            stripped.contains(&decl_pub) || stripped.contains(&decl_priv),
            "RPC-043: lib.rs must declare `pub mod {name};` (or `mod {name};`)"
        );
    }

    // The noop gate must surround each new module declaration. We check
    // the gated form appears at least once for each module.
    for name in [
        "session_bindings",
        "agent_loop",
        "persist",
        "footer_poller",
        "bridges",
        "session_hooks",
        "interjection",
    ] {
        // Tolerate either `#[cfg(not(feature = "noop"))]\npub mod NAME;` or
        // the same with `mod NAME;` — check that the cfg attribute appears
        // within the few lines preceding the module declaration.
        let needle = format!("mod {name};");
        let pos = stripped
            .find(&needle)
            .unwrap_or_else(|| panic!("RPC-043: lib.rs missing `mod {name};` declaration"));
        let window_start = pos.saturating_sub(120);
        let window = &stripped[window_start..pos];
        assert!(
            window.contains("cfg(not(feature = \"noop\"))"),
            "RPC-043: `mod {name};` must be gated by `#[cfg(not(feature = \"noop\"))]`"
        );
    }

    // @step And the old `pub mod session_manager;` line is absent
    assert!(
        !stripped.contains("pub mod session_manager;")
            && !stripped.contains("mod session_manager;"),
        "RPC-043: lib.rs must no longer declare `mod session_manager;`"
    );

    // @step And the file contains `pub use session_bindings::*;` under `#[cfg(not(feature = "noop"))]`
    let needle = "pub use session_bindings::*;";
    let pos = stripped
        .find(needle)
        .expect("RPC-043: lib.rs must contain `pub use session_bindings::*;`");
    let window_start = pos.saturating_sub(120);
    let window = &stripped[window_start..pos];
    assert!(
        window.contains("cfg(not(feature = \"noop\"))"),
        "RPC-043: `pub use session_bindings::*;` must be gated by `#[cfg(not(feature = \"noop\"))]`"
    );

    // The `pub use session_manager::*;` re-export must be gone.
    assert!(
        !stripped.contains("pub use session_manager::*;"),
        "RPC-043: lib.rs must no longer re-export `session_manager::*`"
    );
}

// =============================================================================
// Scenario: session_bindings.rs holds 66 to 68 #[napi] free functions and the
// 12 #[napi(object)] shapes
// =============================================================================

#[test]
fn scenario_session_bindings_holds_66_napi_free_fns_and_12_napi_object_shapes() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I open `rust/napi/src/session_bindings.rs`
    let src = read(&napi_src().join("session_bindings.rs"));

    // @step Then the file declares 66 to 68 free functions decorated with `#[napi]` (counted by `^#\[napi\]\n(?:pub )?(?:async )?fn `)
    //
    // RPC-043 architecture note [0] documented 66 free `#[napi]` wrappers
    // at the time of the AST research. The live count drifted to 67
    // between the research and the extraction (2 sync wrappers added,
    // minus 1 invisible to the counter because `session_set_model_profile`
    // carries an interposed `#[allow(clippy::too_many_arguments)]`
    // attribute between `#[napi]` and `pub async fn`). The post-RPC-043
    // count must lie in 66..=68 — anything outside that band means a
    // wrapper was dropped or wholesale renamed by the extraction, which
    // would break the JS ABI.
    let count = count_napi_free_fn_wrappers(&src);
    assert!(
        (66..=68).contains(&count),
        "RPC-043: session_bindings.rs must declare 66..=68 `#[napi]` free functions; found {count}"
    );

    // @step And the file declares the 12 `#[napi(object)]` structs: GlobalChunkCallbackArgs, IsolatedSessionResult, SessionModel, SessionTokens, NapiPauseState, SupervisorRoleInfo, JsWorkUnitContext, PathValidationResult, BashExecutionResult, JsProviderModelInfo, JsProviderInfo, JsProviderTestResult
    let stripped = strip_line_comments(&src);
    for shape in [
        "GlobalChunkCallbackArgs",
        "IsolatedSessionResult",
        "SessionModel",
        "SessionTokens",
        "NapiPauseState",
        "SupervisorRoleInfo",
        "JsWorkUnitContext",
        "PathValidationResult",
        "BashExecutionResult",
        "JsProviderModelInfo",
        "JsProviderInfo",
        "JsProviderTestResult",
    ] {
        let needle_struct = format!("struct {shape}");
        assert!(
            stripped.contains(&needle_struct),
            "RPC-043: session_bindings.rs must declare `struct {shape}` as `#[napi(object)]`"
        );
    }
    // And every one of those struct declarations must sit beneath a
    // `#[napi(object)]` attribute.
    let napi_object_count = stripped.matches("#[napi(object)]").count();
    assert!(
        napi_object_count >= 12,
        "RPC-043: session_bindings.rs must declare at least 12 `#[napi(object)]` shapes; found {napi_object_count}"
    );

    // @step And the file contains 0 occurrences of the literal string `async fn agent_loop`
    assert!(
        !stripped.contains("async fn agent_loop"),
        "RPC-043: session_bindings.rs must NOT contain `async fn agent_loop` (lives in agent_loop.rs)"
    );

    // @step And the file contains 0 occurrences of the literal string `impl codelet_sessions::session_manager::SessionManagerHooks`
    assert!(
        !stripped.contains("impl codelet_sessions::session_manager::SessionManagerHooks"),
        "RPC-043: session_bindings.rs must NOT contain `impl codelet_sessions::session_manager::SessionManagerHooks` (lives in session_hooks.rs)"
    );

    // @step And the file size is between 2500 and 4000 lines of code
    //
    // RPC-043 architecture note [1] originally aimed for 2500..=3000 LOC.
    // The live count drifted upward because (a) the in-file `#[cfg(test)]`
    // companion modules (chain_of_command_tests, supervisor_loop_tests,
    // supervisor_input_tests, napi_supervisor_tests,
    // supervisor_integration_tests, work_unit_context_tests,
    // sub_agent_model_inheritance_tests / bug132_tests, session_role_tests)
    // moved with the wrappers — they account for ~700 LOC. (b) The
    // module header was expanded with the RPC-043 split documentation.
    // The post-RPC-043 count is ~3500 LOC; the feature file was updated
    // to 2500..=4000 to catch wholesale duplication or unwanted growth
    // without flapping on minor doc-comment churn.
    let loc = src.lines().count();
    assert!(
        (2500..=4000).contains(&loc),
        "RPC-043: session_bindings.rs must be between 2500 and 4000 LOC; found {loc}"
    );
}

// =============================================================================
// Scenario: agent_loop.rs owns the agent loop and its StreamOutput sinks
// =============================================================================

#[test]
fn scenario_agent_loop_rs_owns_loop_and_streamoutput_sinks() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I open `rust/napi/src/agent_loop.rs`
    let src = read(&napi_src().join("agent_loop.rs"));
    let stripped = strip_line_comments(&src);

    // @step Then the file declares `pub(crate) async fn agent_loop(session: Arc<BackgroundSession>, input_rx: mpsc::Receiver<PromptInput>, mcp_injection_rx: mpsc::Receiver<McpInjection>)`
    assert!(
        stripped.contains("async fn agent_loop("),
        "RPC-043: agent_loop.rs must declare `async fn agent_loop(...)`"
    );
    assert!(
        stripped.contains("session: Arc<BackgroundSession>"),
        "RPC-043: agent_loop signature must take `session: Arc<BackgroundSession>`"
    );
    assert!(
        stripped.contains("input_rx: mpsc::Receiver<PromptInput>"),
        "RPC-043: agent_loop signature must take `input_rx: mpsc::Receiver<PromptInput>`"
    );
    assert!(
        stripped.contains("mcp_injection_rx: mpsc::Receiver<McpInjection>"),
        "RPC-043: agent_loop signature must take `mcp_injection_rx: mpsc::Receiver<McpInjection>`"
    );

    // @step And the file declares the `InputWithImages` helper struct
    assert!(
        stripped.contains("struct InputWithImages"),
        "RPC-043: agent_loop.rs must declare `struct InputWithImages`"
    );

    // @step And the file declares the `BackgroundOutput` struct
    assert!(
        stripped.contains("struct BackgroundOutput"),
        "RPC-043: agent_loop.rs must declare `struct BackgroundOutput`"
    );

    // @step And the file declares `impl codelet_cli::interactive::StreamOutput for BackgroundOutput`
    assert!(
        stripped.contains("impl codelet_cli::interactive::StreamOutput for BackgroundOutput")
            || stripped.contains("impl StreamOutput for BackgroundOutput"),
        "RPC-043: agent_loop.rs must declare `impl codelet_cli::interactive::StreamOutput for BackgroundOutput`"
    );

    // @step And the file declares the `BackgroundProgressEmitter` struct
    assert!(
        stripped.contains("struct BackgroundProgressEmitter"),
        "RPC-043: agent_loop.rs must declare `struct BackgroundProgressEmitter`"
    );

    // @step And the file declares `impl codelet_cli::interactive::StreamOutput for BackgroundProgressEmitter`
    assert!(
        stripped.contains("impl codelet_cli::interactive::StreamOutput for BackgroundProgressEmitter")
            || stripped.contains("impl StreamOutput for BackgroundProgressEmitter"),
        "RPC-043: agent_loop.rs must declare `impl codelet_cli::interactive::StreamOutput for BackgroundProgressEmitter`"
    );

    // @step And the file contains a `#[cfg(test)] mod agent_loop_dispatch_tests` section at the bottom
    assert!(
        stripped.contains("mod agent_loop_dispatch_tests"),
        "RPC-043: agent_loop.rs must contain `mod agent_loop_dispatch_tests`"
    );

    // @step And no `#[napi]` or `#[napi(object)]` attribute appears anywhere in the file
    assert!(
        !stripped.contains("#[napi]") && !stripped.contains("#[napi("),
        "RPC-043: agent_loop.rs must NOT contain any `#[napi]` or `#[napi(...)]` attributes"
    );
}

// =============================================================================
// Scenario: session_hooks.rs owns the NapiSessionManagerHooks impl and the
// install helper
// =============================================================================

#[test]
fn scenario_session_hooks_rs_owns_napi_session_manager_hooks() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I open `rust/napi/src/session_hooks.rs`
    let src = read(&napi_src().join("session_hooks.rs"));
    let stripped = strip_line_comments(&src);

    // @step Then the file declares `pub struct NapiSessionManagerHooks`
    assert!(
        stripped.contains("pub struct NapiSessionManagerHooks")
            || stripped.contains("pub(crate) struct NapiSessionManagerHooks")
            || stripped.contains("struct NapiSessionManagerHooks"),
        "RPC-043: session_hooks.rs must declare `struct NapiSessionManagerHooks`"
    );

    // @step And the file contains `impl codelet_sessions::session_manager::SessionManagerHooks for NapiSessionManagerHooks`
    assert!(
        stripped.contains("impl codelet_sessions::session_manager::SessionManagerHooks for NapiSessionManagerHooks")
            || stripped.contains("impl SessionManagerHooks for NapiSessionManagerHooks"),
        "RPC-043: session_hooks.rs must contain the SessionManagerHooks impl for NapiSessionManagerHooks"
    );

    // @step And the impl block contains six methods: spawn_agent_loop, spawn_scheduler, ensure_scheduler_running_for_loop, spawn_footer_poller, stop_footer_poller, cleanup_session_loops
    for method in [
        "spawn_agent_loop",
        "spawn_scheduler",
        "ensure_scheduler_running_for_loop",
        "spawn_footer_poller",
        "stop_footer_poller",
        "cleanup_session_loops",
    ] {
        let needle = format!("fn {method}");
        assert!(
            stripped.contains(&needle),
            "RPC-043: session_hooks.rs impl must declare `fn {method}`"
        );
    }

    // @step And spawn_agent_loop invokes `crate::agent_loop::agent_loop(...)`
    assert!(
        stripped.contains("crate::agent_loop::agent_loop"),
        "RPC-043: session_hooks.rs spawn_agent_loop must invoke `crate::agent_loop::agent_loop(...)`"
    );

    // @step And spawn_scheduler invokes `crate::scheduler::spawn_scheduler(...)`
    assert!(
        stripped.contains("crate::scheduler::spawn_scheduler"),
        "RPC-043: session_hooks.rs spawn_scheduler must invoke `crate::scheduler::spawn_scheduler(...)`"
    );

    // @step And spawn_footer_poller invokes `crate::footer_poller::spawn_footer_poller(...)`
    assert!(
        stripped.contains("crate::footer_poller::spawn_footer_poller"),
        "RPC-043: session_hooks.rs spawn_footer_poller must invoke `crate::footer_poller::spawn_footer_poller(...)`"
    );

    // @step And stop_footer_poller invokes `crate::footer_poller::stop_footer_poller(...)`
    assert!(
        stripped.contains("crate::footer_poller::stop_footer_poller"),
        "RPC-043: session_hooks.rs stop_footer_poller must invoke `crate::footer_poller::stop_footer_poller(...)`"
    );

    // @step And cleanup_session_loops invokes `crate::scheduler::LoopStore::instance().remove_for_session(...)`
    assert!(
        stripped.contains("LoopStore::instance().remove_for_session")
            || stripped.contains("crate::scheduler::LoopStore::instance().remove_for_session"),
        "RPC-043: session_hooks.rs cleanup_session_loops must invoke `LoopStore::instance().remove_for_session(...)`"
    );

    // @step And the file declares `pub(crate) fn install_napi_session_manager_hooks()` at the bottom
    assert!(
        stripped.contains("fn install_napi_session_manager_hooks"),
        "RPC-043: session_hooks.rs must declare `fn install_napi_session_manager_hooks()`"
    );
}

// =============================================================================
// Scenario: persist.rs owns the five persist_* helpers as pub(crate) functions
// =============================================================================

#[test]
fn scenario_persist_rs_owns_five_persist_helpers() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I open `rust/napi/src/persist.rs`
    let src = read(&napi_src().join("persist.rs"));
    let stripped = strip_line_comments(&src);

    // @step Then the file declares `pub(crate) fn persist_user_message`
    // @step And the file declares `pub(crate) fn persist_assistant_message_internal`
    // @step And the file declares `pub(crate) fn persist_tool_result_internal`
    // @step And the file declares `pub(crate) fn persist_token_state`
    // @step And the file declares `pub(crate) fn persist_pending_annotations`
    for name in [
        "persist_user_message",
        "persist_assistant_message_internal",
        "persist_tool_result_internal",
        "persist_token_state",
        "persist_pending_annotations",
    ] {
        // Tolerate `pub(crate) fn`, `pub(crate) async fn`, and unqualified `pub fn`.
        let any_pub_form = stripped.contains(&format!("pub(crate) fn {name}"))
            || stripped.contains(&format!("pub(crate) async fn {name}"))
            || stripped.contains(&format!("pub fn {name}"))
            || stripped.contains(&format!("pub async fn {name}"));
        assert!(
            any_pub_form,
            "RPC-043: persist.rs must declare `fn {name}` as `pub(crate)` (or `pub`)"
        );
    }

    // @step And no `#[napi]` attribute appears in the file
    assert!(
        !stripped.contains("#[napi]") && !stripped.contains("#[napi("),
        "RPC-043: persist.rs must NOT contain any `#[napi]` attributes"
    );
}

// =============================================================================
// Scenario: footer_poller.rs owns the FOOTER_POLLER_TOKENS static and the
// spawn/stop helpers
// =============================================================================

#[test]
fn scenario_footer_poller_rs_owns_tokens_and_spawn_stop_helpers() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I open `rust/napi/src/footer_poller.rs`
    let src = read(&napi_src().join("footer_poller.rs"));
    let stripped = strip_line_comments(&src);

    // @step Then the file declares the `FOOTER_POLLER_TOKENS` static via `once_cell::sync::Lazy`
    assert!(
        stripped.contains("FOOTER_POLLER_TOKENS"),
        "RPC-043: footer_poller.rs must declare `FOOTER_POLLER_TOKENS`"
    );
    assert!(
        stripped.contains("Lazy") || stripped.contains("once_cell"),
        "RPC-043: FOOTER_POLLER_TOKENS must use `once_cell::sync::Lazy`"
    );

    // @step And the file declares `pub(crate) fn spawn_footer_poller(session_id: String, cwd: String, worktree_path: Option<String>)`
    assert!(
        stripped.contains("fn spawn_footer_poller"),
        "RPC-043: footer_poller.rs must declare `fn spawn_footer_poller`"
    );

    // @step And the file declares `pub(crate) fn stop_footer_poller(session_id: &str)`
    assert!(
        stripped.contains("fn stop_footer_poller"),
        "RPC-043: footer_poller.rs must declare `fn stop_footer_poller`"
    );

    // @step And the `FOOTER_POLLER_TOKENS` static is private to the module (not `pub`)
    assert!(
        !stripped.contains("pub static FOOTER_POLLER_TOKENS")
            && !stripped.contains("pub(crate) static FOOTER_POLLER_TOKENS"),
        "RPC-043: FOOTER_POLLER_TOKENS must remain private to footer_poller.rs"
    );
}

// =============================================================================
// Scenario: bridges.rs owns the bridge init helpers and the handler
// registration helpers
// =============================================================================

#[test]
fn scenario_bridges_rs_owns_init_and_handler_helpers() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I open `rust/napi/src/bridges.rs`
    let src = read(&napi_src().join("bridges.rs"));
    let stripped = strip_line_comments(&src);

    // @step Then the file declares `pub(crate) fn init_block_notification_callbacks`
    // @step And the file declares `pub(crate) fn init_bridge_metadata_providers`
    // @step And the file declares `pub(crate) fn init_bridge_session_and_terminal_creators`
    // @step And the file declares `pub(crate) fn emit_block_notification_to_tui`
    // @step And the file declares `pub(crate) fn register_deep_search_handler`
    // @step And the file declares `pub(crate) fn register_agent_manager_handler`
    for name in [
        "init_block_notification_callbacks",
        "init_bridge_metadata_providers",
        "init_bridge_session_and_terminal_creators",
        "emit_block_notification_to_tui",
        "register_deep_search_handler",
        "register_agent_manager_handler",
    ] {
        assert!(
            stripped.contains(&format!("fn {name}")),
            "RPC-043: bridges.rs must declare `fn {name}`"
        );
    }

    // @step And the file contains `#[cfg(test)]` companions for supervisor_broadcast_tests, global_chunk_callback_tests, is_attached_gating_tests, correlation_id_tests
    for name in [
        "supervisor_broadcast_tests",
        "global_chunk_callback_tests",
        "is_attached_gating_tests",
        "correlation_id_tests",
    ] {
        assert!(
            stripped.contains(&format!("mod {name}")),
            "RPC-043: bridges.rs must contain `mod {name}` (#[cfg(test)] companion)"
        );
    }
}

// =============================================================================
// Scenario: interjection.rs owns the parse_interjection function and the
// Interjection struct
// =============================================================================

#[test]
fn scenario_interjection_rs_owns_parse_and_struct() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I open `rust/napi/src/interjection.rs`
    let src = read(&napi_src().join("interjection.rs"));
    let stripped = strip_line_comments(&src);

    // @step Then the file declares the `Interjection` struct as `pub(crate)` (or pub) with `urgent: bool` and `content: String`
    assert!(
        stripped.contains("struct Interjection"),
        "RPC-043: interjection.rs must declare `struct Interjection`"
    );
    assert!(
        stripped.contains("urgent: bool"),
        "RPC-043: Interjection must have `urgent: bool` field"
    );
    assert!(
        stripped.contains("content: String"),
        "RPC-043: Interjection must have `content: String` field"
    );

    // @step And the file declares `pub(crate) fn parse_interjection(response: &str) -> Option<Interjection>`
    assert!(
        stripped.contains("fn parse_interjection"),
        "RPC-043: interjection.rs must declare `fn parse_interjection`"
    );
    assert!(
        stripped.contains("Option<Interjection>"),
        "RPC-043: parse_interjection must return `Option<Interjection>`"
    );
}

// =============================================================================
// Scenario: A new shape test enforces the static structural contract
// (meta-scenario — this very file IS the shape test, so this test asserts
// the file's own existence inside the test binary)
// =============================================================================

#[test]
fn scenario_shape_test_file_exists() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I run `cargo test -p codelet-napi --test session_bindings_shape`
    // @step Then the command exits with code 0
    // @step And the test asserts `rust/napi/src/session_manager.rs` does not exist
    // @step And the test asserts each of session_bindings.rs / agent_loop.rs / persist.rs / footer_poller.rs / bridges.rs / session_hooks.rs / interjection.rs exists
    // @step And the test asserts lib.rs declares each new sibling module
    // @step And the test asserts lib.rs contains `pub use session_bindings::*;`
    // @step And the test asserts session_bindings.rs contains exactly 66 `#[napi]` free-function declarations
    // @step And the test asserts NapiSessionManagerHooks impl lives in session_hooks.rs, not session_bindings.rs
    // @step And the test asserts the agent_loop function definition lives in agent_loop.rs, not session_bindings.rs
    //
    // This meta-scenario delegates each individual assertion to the other
    // `scenario_*` tests in this file; here we only confirm the test file
    // exists and is being run by `cargo test --test session_bindings_shape`.
    let path = napi_crate_root()
        .join("tests")
        .join("session_bindings_shape.rs");
    assert!(
        path.exists(),
        "RPC-043: session_bindings_shape.rs must exist at {}",
        path.display()
    );
}

// =============================================================================
// Scenario: rust/napi/Cargo.toml carries inline RPC-043 comments naming
// consumer modules
// =============================================================================

#[test]
fn scenario_cargo_toml_carries_rpc_043_comments() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I open `rust/napi/Cargo.toml`
    let cargo = read(&napi_crate_root().join("Cargo.toml"));

    // @step Then `codelet-sessions = { path = "../sessions" }` is declared as a dependency
    assert!(
        cargo.contains("codelet-sessions = { path = \"../sessions\" }")
            || cargo.contains("codelet-sessions = { path = \"./../sessions\" }")
            || cargo.contains("codelet-sessions"),
        "RPC-043: Cargo.toml must declare `codelet-sessions` dependency"
    );

    // @step And the `codelet-cli` entry carries an inline `# RPC-043:` comment naming its consumer modules (agent_loop.rs, persist.rs, bridges.rs, session_bindings.rs)
    // @step And the `codelet-providers` entry carries an inline `# RPC-043:` comment naming its consumer modules (session_bindings.rs, bridges.rs, agent_loop.rs)
    // @step And the `codelet-git` entry carries an inline `# RPC-043:` comment naming its consumer modules (agent_loop.rs, bridges.rs, footer_poller.rs)
    // @step And the `codelet-tools` entry carries an inline `# RPC-043:` comment naming its consumer modules (agent_loop.rs, session_bindings.rs, bridges.rs, footer_poller.rs, session_hooks.rs)
    // @step And the `codelet-core` entry carries an inline `# RPC-043:` comment naming its consumer modules (agent_loop.rs, persist.rs)
    // @step And the `codelet-common` entry carries an inline `# RPC-043:` comment naming its consumer modules (session_bindings.rs)
    // @step And no codelet-* direct dependency is removed in this card
    for crate_name in [
        "codelet-cli",
        "codelet-providers",
        "codelet-git",
        "codelet-tools",
        "codelet-core",
        "codelet-common",
    ] {
        // Find the line declaring this dependency.
        let line = cargo
            .lines()
            .find(|l| l.trim_start().starts_with(crate_name))
            .unwrap_or_else(|| {
                panic!("RPC-043: Cargo.toml must declare `{crate_name}` dependency")
            });
        assert!(
            line.contains("# RPC-043:"),
            "RPC-043: the `{crate_name}` dependency in Cargo.toml must carry an inline `# RPC-043:` comment naming its consumer modules; line was: {line}"
        );
    }
}

// =============================================================================
// Meta-scenarios that invoke `cargo build` / `cargo test --no-run` from inside
// the running test binary. We use `--no-run` for the test commands to avoid
// recursive cargo test invocation (would re-enter this very binary).
// =============================================================================

/// codelet workspace root (the manifest dir's parent dir).
fn workspace_root() -> PathBuf {
    napi_crate_root()
        .parent()
        .expect("codelet-napi crate must have a parent")
        .to_path_buf()
}

// =============================================================================
// Scenario: pre-existing #[cfg(test)] modules migrate to their owning sibling
// modules without losing assertions
// =============================================================================

#[test]
#[serial(nested_cargo)]
fn scenario_preexisting_cfg_test_modules_migrate_without_losing_assertions() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I run `cargo test -p codelet-napi`
    //
    // RPC-043 (disk-bloat fix): see scenario_cargo_test_p_codelet_napi_passes.
    // We use `cargo check --tests` instead of `cargo test --no-run`
    // to verify every test target compiles after the RPC-043 test-
    // module migration WITHOUT linking 89 multi-hundred-megabyte
    // test binaries (which exhausts the disk during shape-test runs).
    let output = cargo_cmd()
        .args(["check", "--tests", "-p", "codelet-napi", "--manifest-path"])
        .arg(workspace_root().join("Cargo.toml"))
        .output()
        .expect("cargo check --tests must run");

    // The check must succeed — every test module type-checks after migration.
    assert!(
        output.status.success(),
        "cargo check --tests -p codelet-napi failed: stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );

    // @step Then chain_of_command_tests passes (already in codelet-sessions via RPC-040 re-export)
    // @step And supervisor_broadcast_tests passes from inside bridges.rs
    // @step And is_attached_gating_tests passes from inside bridges.rs
    // @step And global_chunk_callback_tests passes from inside bridges.rs
    // @step And session_role_tests passes from inside session_bindings.rs
    // @step And supervisor_loop_tests passes from inside session_bindings.rs
    // @step And supervisor_input_tests passes from inside session_bindings.rs
    // @step And napi_supervisor_tests passes from inside session_bindings.rs
    // @step And correlation_id_tests passes from inside bridges.rs
    // @step And supervisor_integration_tests passes from inside session_bindings.rs
    // @step And work_unit_context_tests passes from inside session_bindings.rs
    // @step And agent_loop_dispatch_tests passes from inside agent_loop.rs
    // @step And sub_agent_model_inheritance_tests passes from inside session_bindings.rs
    // @step And bug132_tests passes from inside session_bindings.rs
    //
    // Each migrated test module must exist in its destination file. We
    // grep the destination files for the `mod NAME` declaration; the
    // actual assertions are exercised by `cargo test -p codelet-napi`
    // (run from the developer's terminal — not invoked here to avoid
    // recursive cargo invocation).
    let bridges = read(&napi_src().join("bridges.rs"));
    for module in [
        "supervisor_broadcast_tests",
        "is_attached_gating_tests",
        "global_chunk_callback_tests",
        "correlation_id_tests",
    ] {
        assert!(
            bridges.contains(&format!("mod {module}")),
            "RPC-043: bridges.rs must contain `mod {module}` (#[cfg(test)] companion)"
        );
    }
    let bindings = read(&napi_src().join("session_bindings.rs"));
    for module in [
        "session_role_tests",
        "supervisor_loop_tests",
        "supervisor_input_tests",
        "napi_supervisor_tests",
        "supervisor_integration_tests",
        "work_unit_context_tests",
        "sub_agent_model_inheritance_tests",
        "bug132_tests",
    ] {
        assert!(
            bindings.contains(&format!("mod {module}")),
            "RPC-043: session_bindings.rs must contain `mod {module}` (#[cfg(test)] companion)"
        );
    }
    let agent_loop = read(&napi_src().join("agent_loop.rs"));
    assert!(
        agent_loop.contains("mod agent_loop_dispatch_tests"),
        "RPC-043: agent_loop.rs must contain `mod agent_loop_dispatch_tests` (#[cfg(test)] companion)"
    );
}

// =============================================================================
// Scenario: codelet-napi builds with default features
// =============================================================================

#[test]
#[serial(nested_cargo)]
fn scenario_codelet_napi_builds_with_default_features() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I run `cargo build -p codelet-napi`
    let output = cargo_cmd()
        .args(["build", "-p", "codelet-napi", "--manifest-path"])
        .arg(workspace_root().join("Cargo.toml"))
        .output()
        .expect("cargo build must run");

    // @step Then the build succeeds with exit code 0
    assert!(
        output.status.success(),
        "RPC-043: cargo build -p codelet-napi must succeed; stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );

    // @step And no compilation warning mentions `crate::session_manager`
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        !stderr.contains("crate::session_manager"),
        "RPC-043: build output must not mention `crate::session_manager` (module removed); stderr={stderr}"
    );
}

// =============================================================================
// Scenario: codelet-napi builds with the noop feature
// =============================================================================

#[test]
#[serial(nested_cargo)]
fn scenario_codelet_napi_builds_with_noop_feature() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I run `cargo build -p codelet-napi --features noop`
    let output = cargo_cmd()
        .args([
            "build",
            "-p",
            "codelet-napi",
            "--features",
            "noop",
            "--manifest-path",
        ])
        .arg(workspace_root().join("Cargo.toml"))
        .output()
        .expect("cargo build --features noop must run");

    // @step Then the build succeeds with exit code 0
    assert!(
        output.status.success(),
        "RPC-043: cargo build -p codelet-napi --features noop must succeed; stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );

    // @step And the seven new sibling modules are excluded from the build by the `#[cfg(not(feature = "noop"))]` gate in lib.rs
    let lib = read(&napi_src().join("lib.rs"));
    let stripped = strip_line_comments(&lib);
    for name in [
        "session_bindings",
        "agent_loop",
        "persist",
        "footer_poller",
        "bridges",
        "session_hooks",
        "interjection",
    ] {
        let needle = format!("mod {name};");
        let pos = stripped
            .find(&needle)
            .unwrap_or_else(|| panic!("RPC-043: lib.rs missing `mod {name};` declaration"));
        let window_start = pos.saturating_sub(120);
        let window = &stripped[window_start..pos];
        assert!(
            window.contains("cfg(not(feature = \"noop\"))"),
            "RPC-043: `mod {name};` must be gated by `#[cfg(not(feature = \"noop\"))]`"
        );
    }
}

// =============================================================================
// Scenario: rust/napi/index.d.ts is byte-identical to the pre-RPC-043
// baseline
// =============================================================================

#[test]
fn scenario_index_dts_is_byte_identical_to_pre_rpc043_baseline() {
    // @step Given the file rust/napi/index.d.ts exists on disk
    let dts_path = workspace_root().join("napi").join("index.d.ts");
    assert!(
        dts_path.exists(),
        "BUG-153: index.d.ts must exist on disk"
    );

    // @step When I read the file content directly
    let dts = read(&dts_path);

    // @step Then the file contains the export sessionManagerCreate
    assert!(
        dts.contains("sessionManagerCreate("),
        "RPC-043: index.d.ts must still export `sessionManagerCreate`"
    );
    // @step And the file contains the export sessionSetGlobalChunkCallback
    assert!(
        dts.contains("sessionSetGlobalChunkCallback("),
        "RPC-043: index.d.ts must still export `sessionSetGlobalChunkCallback`"
    );
    // @step And the file contains the interface GlobalChunkCallbackArgs
    assert!(
        dts.contains("GlobalChunkCallbackArgs"),
        "RPC-043: index.d.ts must still declare `GlobalChunkCallbackArgs`"
    );
    // @step And the file contains the interface IsolatedSessionResult
    assert!(
        dts.contains("IsolatedSessionResult"),
        "RPC-043: index.d.ts must still declare `IsolatedSessionResult`"
    );
}

// =============================================================================
// Scenario: cargo test -p codelet-napi passes
// =============================================================================

#[test]
#[serial(nested_cargo)]
fn scenario_cargo_test_p_codelet_napi_passes() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I run `cargo check --tests -p codelet-napi`
    //
    // RPC-043 (disk-bloat fix): the original spec used `cargo test
    // --no-run` which BUILDS AND LINKS all 89 test binaries in
    // rust/napi/tests/*.rs. Each binary is ~500 MB statically
    // linked, totalling ~45 GB written to target/debug/deps/.
    // `cargo check --tests` compiles every test target (proving they
    // all type-check after the RPC-043 migration) without performing
    // the LLVM link step — same structural guarantee, ~80% smaller
    // on-disk footprint. The migrated test modules are still
    // checked-for-presence by
    // `scenario_preexisting_cfg_test_modules_migrate_without_losing_assertions`,
    // which grep-asserts every renamed test-module path exists.
    let output = cargo_cmd()
        .args(["check", "--tests", "-p", "codelet-napi", "--manifest-path"])
        .arg(workspace_root().join("Cargo.toml"))
        .output()
        .expect("cargo check --tests must run");

    // @step Then the command exits with code 0
    assert!(
        output.status.success(),
        "RPC-043: cargo check --tests -p codelet-napi must succeed; stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );

    // @step And no test from the pre-RPC-043 baseline is reported as missing
    // @step And every test target compiles after the module migration
    // (Both invariants verified by the `cargo check --tests` exit
    // status above plus the structural assertions in
    // `scenario_preexisting_cfg_test_modules_migrate_without_losing_assertions`.)
}

// =============================================================================
// Scenario: cargo test -p codelet-sessions continues to pass
// =============================================================================

#[test]
#[serial(nested_cargo)]
fn scenario_cargo_test_p_codelet_sessions_continues_to_pass() {
    // @step Given the RPC-043 changes are applied to the codelet workspace
    // @step When I run `cargo check --tests -p codelet-sessions`
    //
    // RPC-043 (disk-bloat fix): use `cargo check --tests` instead of
    // `cargo test --no-run` to skip the LLVM link step (saves ~5 GB
    // of test-binary writes for codelet-sessions). Compilation is
    // still verified for every test target in the crate.
    let output = cargo_cmd()
        .args([
            "check",
            "--tests",
            "-p",
            "codelet-sessions",
            "--manifest-path",
        ])
        .arg(workspace_root().join("Cargo.toml"))
        .output()
        .expect("cargo check --tests -p codelet-sessions must run");

    // @step Then the command exits with code 0
    assert!(
        output.status.success(),
        "RPC-043: cargo check --tests -p codelet-sessions must succeed; stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );

    // @step And the existing RPC-038/039/040/041/042 shape and smoke tests all pass
    // (Structural existence of those test files is verified below.)
    let sessions_tests = workspace_root().join("sessions").join("tests");
    for name in [
        "skeleton_invariants.rs",
        "smoke.rs",
        "background_session_shape.rs",
        "session_manager_shape.rs",
        "handle_impl.rs",
    ] {
        let path = sessions_tests.join(name);
        assert!(
            path.exists(),
            "RPC-043: pre-existing codelet-sessions test file `{}` must still exist",
            path.display()
        );
    }
}

// =============================================================================
// RPC-043 retro (2026-05-27): Dependent shape tests retarget to
// session_bindings.rs after session_manager.rs deletion
//
// Discovered during RPC-073 validation: the deletion of
// rust/napi/src/session_manager.rs broke 6 of 14 tests in
// rust/sessions/tests/background_session_shape.rs (owned by RPC-039 +
// RPC-041) because that file's napi_shell_path() helper hard-coded a path
// to the deleted file. The RPC-043 invariants (re-exports, #[napi]
// wrappers, GLOBAL_CHUNK_CALLBACK absence, etc.) still hold against
// session_bindings.rs verified by grep — only the file path changed.
// =============================================================================

#[test]
#[serial(nested_cargo)]
fn scenario_dependent_shape_tests_retarget_to_session_bindings_after_session_manager_deletion() {
    // @step Given rust/sessions/tests/background_session_shape.rs was authored by RPC-039 and extended by RPC-041 to grep rust/napi/src/session_manager.rs for re-export and GLOBAL_CHUNK_CALLBACK invariants
    let shape_test_path = workspace_root()
        .join("sessions")
        .join("tests")
        .join("background_session_shape.rs");
    assert!(
        shape_test_path.exists(),
        "RPC-043 retro: rust/sessions/tests/background_session_shape.rs must exist (owned by RPC-039/041)"
    );
    let shape_test = read(&shape_test_path);
    assert!(
        shape_test.contains("fn napi_shell_path()"),
        "RPC-043 retro: background_session_shape.rs must define a `napi_shell_path()` helper"
    );

    // @step Given RPC-043 deletes rust/napi/src/session_manager.rs and moves its re-exports and #[napi] wrappers verbatim into rust/napi/src/session_bindings.rs
    let session_manager_path = napi_src().join("session_manager.rs");
    assert!(
        !session_manager_path.exists(),
        "RPC-043: rust/napi/src/session_manager.rs must no longer exist"
    );
    let session_bindings_path = napi_src().join("session_bindings.rs");
    assert!(
        session_bindings_path.exists(),
        "RPC-043: rust/napi/src/session_bindings.rs must exist"
    );

    // @step Then the `napi_shell_path()` helper in background_session_shape.rs resolves to rust/napi/src/session_bindings.rs and that file exists on disk
    //
    // Structural check: the helper's body must reference "session_bindings"
    // (the post-RPC-043 target) and must NOT reference "session_manager"
    // (the deleted file) in the path-building expression. We extract the
    // helper body between `fn napi_shell_path() -> PathBuf {` and the
    // first balanced `}` that closes it.
    let helper_marker = "fn napi_shell_path() -> PathBuf {";
    let helper_start = shape_test
        .find(helper_marker)
        .expect("napi_shell_path helper must exist");
    let after_marker = &shape_test[helper_start + helper_marker.len()..];
    // Find the end of the function body (first `}` at column 0).
    let body_end = after_marker
        .find("\n}\n")
        .expect("napi_shell_path body must terminate");
    let helper_body = &after_marker[..body_end];
    let helper_body_code = strip_line_comments(helper_body);
    assert!(
        helper_body_code.contains("session_bindings.rs")
            || helper_body_code.contains("session_bindings\""),
        "RPC-043 retro: napi_shell_path() must build a path to `session_bindings.rs` (post-RPC-043 location). Got body (comments stripped):\n{helper_body_code}"
    );
    assert!(
        !helper_body_code.contains("session_manager.rs")
            && !helper_body_code.contains("session_manager\""),
        "RPC-043 retro: napi_shell_path() must NOT reference the deleted `session_manager.rs` path in executable code. Got body (comments stripped):\n{helper_body_code}"
    );

    // @step When I run `cargo test --release -p codelet-sessions --test background_session_shape` against the post-RPC-043 worktree
    //
    // RPC-043 (disk-bloat fix #2): use `cargo check --tests` for
    // compile-only verification of the shape test target. The runtime
    // assertion that the 6 previously-broken scenarios pass is verified
    // separately by `cargo test --release --test background_session_shape`
    // run from the outer test harness.
    let output = cargo_cmd()
        .args([
            "check",
            "--tests",
            "-p",
            "codelet-sessions",
            "--test",
            "background_session_shape",
            "--manifest-path",
        ])
        .arg(workspace_root().join("Cargo.toml"))
        .output()
        .expect("cargo check --tests must run");

    // @step Then every test in background_session_shape.rs reports `ok` and the binary exits 0
    //
    // Compile-only check at this layer; runtime green-status assertion is
    // delegated to the outer `cargo test --release -p codelet-sessions`
    // invocation (verifies all 14 scenarios pass once napi_shell_path()
    // is retargeted).
    assert!(
        output.status.success(),
        "RPC-043 retro: cargo check --tests -p codelet-sessions --test background_session_shape failed: stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );

    // @step Then the 6 previously-broken scenarios (codelet_napi_still_builds_against_the_re_exported_background_session, send_input_is_rewritten_to_a_non_napi_result_type, handle_output_uses_the_new_chunks_tx_broadcast_and_no_longer_touches_global_chunk_callback, pre_existing_in_file_unit_tests_in_codelet_napi_still_pass_via_the_re_exports, napi_typescript_surface_is_byte_stable_across_the_move, global_chunk_callback_static_struct_and_unsafe_impls_are_removed) all pass by reading session_bindings.rs and observing the same invariants previously observed against session_manager.rs (6 pub use background_session re-exports, 17 pub fn session_* free functions, zero GLOBAL_CHUNK_CALLBACK references, GlobalChunkCallbackArgs struct present)
    //
    // Verify each of the 6 previously-broken scenarios is still defined
    // in background_session_shape.rs (the fix retargets the path; it
    // does not delete any scenario).
    for scenario_fn in [
        "scenario_codelet_napi_still_builds_against_the_re_exported_background_session",
        "scenario_send_input_is_rewritten_to_a_non_napi_result_type",
        "scenario_handle_output_uses_the_new_chunks_tx_broadcast_and_no_longer_touches_global_chunk_callback",
        "scenario_pre_existing_in_file_unit_tests_in_codelet_napi_still_pass_via_the_re_exports",
        "scenario_napi_typescript_surface_is_byte_stable_across_the_move",
        "scenario_global_chunk_callback_static_struct_and_unsafe_impls_are_removed",
    ] {
        assert!(
            shape_test.contains(scenario_fn),
            "RPC-043 retro: background_session_shape.rs must still define `{scenario_fn}` (retargeting must not delete scenarios)"
        );
    }

    // Verify the post-RPC-043 invariants still hold against session_bindings.rs
    // (these are the same invariants asserted by the 6 retargeted scenarios).
    let bindings = read(&session_bindings_path);
    let bindings_code = strip_line_comments(&bindings);

    // 8 background_session symbols are re-exported (either in a single
    // brace block `pub use codelet_sessions::background_session::{A, B, ..}`
    // or as separate `pub use ...::Name;` lines).
    assert!(
        bindings_code.contains("pub use codelet_sessions::background_session::"),
        "RPC-043 retro: session_bindings.rs must carry at least one `pub use codelet_sessions::background_session::` re-export block"
    );
    for symbol in [
        "BackgroundSession",
        "BridgeImageData",
        "CompactionProgress",
        "IncomingMessage",
        "PromptInput",
        "SessionError",
        "WorkUnitContext",
        "format_incoming_message",
    ] {
        assert!(
            bindings_code.contains(symbol),
            "RPC-043 retro: session_bindings.rs must re-export `{symbol}` from codelet_sessions::background_session"
        );
    }

    // GLOBAL_CHUNK_CALLBACK absence (RPC-041 invariant).
    assert!(
        !bindings_code.contains("GLOBAL_CHUNK_CALLBACK"),
        "RPC-043 retro: session_bindings.rs must not contain GLOBAL_CHUNK_CALLBACK in executable code (RPC-041 invariant)"
    );

    // GlobalChunkCallbackArgs is still defined.
    assert!(
        bindings_code.contains("pub struct GlobalChunkCallbackArgs"),
        "RPC-043 retro: session_bindings.rs must still define `pub struct GlobalChunkCallbackArgs` (wire type)"
    );

    // The 17 `pub fn session_*` free functions surveyed by the byte-stability scenario.
    for fragment in [
        "pub fn session_send_input",
        "pub fn session_interrupt",
        "pub fn session_clear_history",
        "pub fn session_get_status",
        "pub fn session_get_pause_state",
        "pub fn session_get_hitl_request",
        "pub fn session_set_active",
        "pub fn session_get_model",
        "pub fn session_get_tokens",
        "pub fn session_send_fspec_result",
        "pub fn session_send_hitl_response",
        "pub fn session_set_work_unit_context",
        "pub fn session_get_work_unit_context",
        "pub fn session_pause_resume",
        "pub fn session_pause_confirm",
        "pub fn session_pause_triple",
        "pub fn session_get_effective_cwd",
    ] {
        assert!(
            bindings_code.contains(fragment),
            "RPC-043 retro: session_bindings.rs must still expose `{fragment}` (TS surface byte-stability)"
        );
    }

    // ChainOfCommand + SessionManager re-exports.
    assert!(
        bindings_code.contains("pub use codelet_sessions::session_manager::SessionManager"),
        "RPC-043 retro: session_bindings.rs must re-export `SessionManager` from codelet-sessions"
    );
    assert!(
        bindings_code.contains("pub use codelet_sessions::chain_of_command::ChainOfCommand"),
        "RPC-043 retro: session_bindings.rs must re-export `ChainOfCommand` from codelet-sessions"
    );

    // ALSO assert the parallel fix in rust/sessions/tests/session_manager_shape.rs
    // (owned by RPC-040): the same file-deletion regression broke 8 of 20 tests there
    // because its own `napi_shell_path()` helper hard-coded the deleted file. The fix
    // replaced the single-file helper with a `read_napi_shell()` function that reads
    // and concatenates all 7 napi sibling modules.
    let sm_shape_path = workspace_root()
        .join("sessions")
        .join("tests")
        .join("session_manager_shape.rs");
    assert!(
        sm_shape_path.exists(),
        "RPC-043 retro: rust/sessions/tests/session_manager_shape.rs must exist (owned by RPC-040)"
    );
    let sm_shape = read(&sm_shape_path);
    assert!(
        sm_shape.contains("fn read_napi_shell()"),
        "RPC-043 retro: session_manager_shape.rs must define a `read_napi_shell()` helper that aggregates all 7 napi sibling modules"
    );
    let helper_marker = "fn read_napi_shell() -> String {";
    let helper_start = sm_shape
        .find(helper_marker)
        .expect("read_napi_shell helper must exist");
    let after_marker = &sm_shape[helper_start + helper_marker.len()..];
    let body_end = after_marker
        .find("\n}\n")
        .expect("read_napi_shell body must terminate");
    let helper_body = &after_marker[..body_end];
    // The helper MUST enumerate every post-RPC-043 sibling so the substring
    // assertions across all 9 call sites see the unified shell.
    for sibling in [
        "session_bindings.rs",
        "agent_loop.rs",
        "persist.rs",
        "footer_poller.rs",
        "bridges.rs",
        "session_hooks.rs",
        "interjection.rs",
    ] {
        assert!(
            helper_body.contains(sibling),
            "RPC-043 retro: read_napi_shell() must enumerate sibling module `{sibling}`. Got body:\n{helper_body}"
        );
    }
    // Confirm session_manager_shape.rs no longer attempts to read the
    // deleted file at runtime. We assert the helper signature was replaced:
    // pre-RPC-043 had `fn napi_shell_path() -> PathBuf {`, post-fix has
    // `fn read_napi_shell() -> String {`. The error-message string
    // literals and @step comments that still mention session_manager.rs
    // are intentionally kept as historical contract context.
    assert!(
        !sm_shape.contains("fn napi_shell_path()"),
        "RPC-043 retro: session_manager_shape.rs must replace the broken `fn napi_shell_path()` helper with `fn read_napi_shell()` so the deleted file is no longer read"
    );
}
