//! OpenAI API client and Rig integration
//!
//! # Example
//! ```
//! use rig::providers::openai;
//!
//! let client = openai::Client::new("YOUR_API_KEY");
//!
//! let gpt4o = client.completion_model(openai::GPT_4O);
//! ```
pub mod client;
pub mod completion;
pub mod embedding;
pub mod responses_api;

#[cfg(feature = "audio")]
#[cfg_attr(docsrs, doc(cfg(feature = "audio")))]
pub mod audio_generation;

#[cfg(feature = "image")]
#[cfg_attr(docsrs, doc(cfg(feature = "image")))]
pub mod image_generation;
#[cfg(feature = "image")]
pub use image_generation::*;

pub mod transcription;

pub use client::*;
pub use completion::*;
pub use embedding::*;

/// Ensures a JSON schema is compatible with OpenAI's function parameter restrictions.
///
/// OpenAI's API (both Chat Completions strict mode and Responses API) does NOT support:
/// - `$ref` / `definitions` / `$defs` in function parameter schemas
/// - `oneOf` (must use `anyOf` instead)
/// - Objects without `additionalProperties: false` (strict mode)
/// - Objects with non-exhaustive `required` arrays (strict mode)
///
/// This function performs two phases:
/// 1. **Ref resolution**: Inlines all `$ref` references from `definitions`/`$defs` blocks
///    (generated by schemars for Rust enums/structs) and removes those blocks.
/// 2. **Schema sanitization**: Recursively applies OpenAI-specific rules (additionalProperties,
///    required, oneOf→anyOf conversion).
pub(crate) fn sanitize_schema(schema: &mut serde_json::Value) {
    // Phase 1: Resolve $ref/definitions (schemars generates Draft-07 "definitions" + "$ref"
    // patterns that OpenAI doesn't support in function parameter schemas)
    resolve_schema_refs(schema);

    // Phase 2: Apply OpenAI-specific sanitization rules recursively
    sanitize_node(schema);
}

/// Extract `definitions`/`$defs` from the root schema and inline all `$ref` references.
///
/// schemars (used by Rust `#[derive(JsonSchema)]`) generates JSON Schema Draft-07 with
/// `"definitions": { "TypeName": { ... } }` and `"$ref": "#/definitions/TypeName"` references.
/// OpenAI's function calling API does not support `$ref` or `definitions` at all — schemas
/// must be fully self-contained. This function resolves all references by replacing each
/// `{"$ref": "#/definitions/Foo"}` with the actual definition content, then removes the
/// `definitions`/`$defs` block.
fn resolve_schema_refs(schema: &mut serde_json::Value) {
    use serde_json::Value;

    // Extract definitions from root object
    let definitions = if let Value::Object(obj) = &mut *schema {
        // Remove metadata keys that aren't valid in function parameter schemas
        obj.remove("$schema");
        obj.remove("title");

        // Extract definitions (schemars Draft-07: "definitions", JSON Schema 2020-12: "$defs")
        let defs = obj
            .remove("definitions")
            .or_else(|| obj.remove("$defs"));

        match defs {
            Some(Value::Object(d)) => d,
            _ => return,
        }
    } else {
        return;
    };

    // Recursively replace all $ref with inlined definitions
    inline_ref_values(schema, &definitions);
}

/// Recursively replace `{"$ref": "#/definitions/Foo"}` or `{"$ref": "#/$defs/Foo"}`
/// with the actual definition content. Handles nested $ref within definitions themselves
/// (e.g., ConvertTransform referencing CaseType).
///
/// Uses a depth limit to prevent infinite loops from circular references.
fn inline_ref_values(
    value: &mut serde_json::Value,
    definitions: &serde_json::Map<String, serde_json::Value>,
) {
    inline_ref_values_inner(value, definitions, 0);
}

fn inline_ref_values_inner(
    value: &mut serde_json::Value,
    definitions: &serde_json::Map<String, serde_json::Value>,
    depth: usize,
) {
    use serde_json::Value;

    // Guard against circular references (very unlikely in schemars output, but be safe)
    if depth > 32 {
        return;
    }

    match value {
        Value::Object(obj) => {
            // If this object is a $ref, replace it entirely with the inlined definition
            if let Some(Value::String(ref_path)) = obj.get("$ref") {
                let def_name = ref_path
                    .strip_prefix("#/definitions/")
                    .or_else(|| ref_path.strip_prefix("#/$defs/"))
                    .map(String::from);

                if let Some(name) = def_name
                    && let Some(definition) = definitions.get(&name)
                {
                    let mut inlined = definition.clone();
                    // Recursively resolve any nested $ref in the inlined definition
                    inline_ref_values_inner(&mut inlined, definitions, depth + 1);
                    *value = inlined;
                    return;
                }
            }

            // Not a $ref — recurse into all child values
            for v in obj.values_mut() {
                inline_ref_values_inner(v, definitions, depth + 1);
            }
        }
        Value::Array(arr) => {
            for v in arr.iter_mut() {
                inline_ref_values_inner(v, definitions, depth + 1);
            }
        }
        _ => {}
    }
}

/// Recursively sanitize a JSON schema node for OpenAI compatibility.
///
/// Applied AFTER ref resolution, so the schema is fully self-contained.
fn sanitize_node(schema: &mut serde_json::Value) {
    use serde_json::Value;

    if let Value::Object(obj) = schema {
        // OpenAI/Codex APIs do NOT support `allOf` in function parameter schemas.
        // schemars generates `"allOf": [{"$ref": "#/definitions/SomeType"}]` for fields
        // that reference another type. After ref resolution the $ref is inlined but the
        // `allOf` wrapper remains. Unwrap it by merging each item's keys into the parent
        // object (standard JSON Schema `allOf` semantics = intersection / merge).
        // This MUST happen before any other sanitization so the merged result is processed.
        if let Some(Value::Array(items)) = obj.remove("allOf") {
            for item in items {
                if let Value::Object(item_obj) = item {
                    for (k, v) in item_obj {
                        // Preserve existing parent keys (e.g. "description")
                        obj.entry(k).or_insert(v);
                    }
                }
            }
        }

        let is_object_schema = obj.get("type") == Some(&Value::String("object".to_string()))
            || obj.contains_key("properties");

        // This is required by OpenAI's Responses API when using strict mode.
        // Source: https://platform.openai.com/docs/guides/structured-outputs#additionalproperties-false-must-always-be-set-in-objects
        if is_object_schema && !obj.contains_key("additionalProperties") {
            obj.insert("additionalProperties".to_string(), Value::Bool(false));
        }

        // This is also required by OpenAI's Responses API
        // Source: https://platform.openai.com/docs/guides/structured-outputs#all-fields-must-be-required
        if let Some(Value::Object(properties)) = obj.get("properties") {
            let prop_keys = properties.keys().cloned().map(Value::String).collect();
            obj.insert("required".to_string(), Value::Array(prop_keys));
        }

        // Handle $defs that might still exist (e.g., from non-schemars sources)
        if let Some(defs) = obj.get_mut("$defs")
            && let Value::Object(defs_obj) = defs
        {
            for (_, def_schema) in defs_obj.iter_mut() {
                sanitize_node(def_schema);
            }
        }

        if let Some(properties) = obj.get_mut("properties")
            && let Value::Object(props) = properties
        {
            for (_, prop_value) in props.iter_mut() {
                sanitize_node(prop_value);
            }
        }

        if let Some(items) = obj.get_mut("items") {
            sanitize_node(items);
        }

        // Recurse into additionalProperties if it's a schema (not just true/false)
        if let Some(Value::Object(_)) = obj.get("additionalProperties")
            && let Some(ap) = obj.get_mut("additionalProperties")
        {
            sanitize_node(ap);
        }

        // OpenAI doesn't support oneOf so we need to switch this to anyOf
        if let Some(one_of) = obj.remove("oneOf") {
            // If `anyOf` already exists, merge arrays. If not, insert new.
            match obj.get_mut("anyOf") {
                Some(Value::Array(existing)) => {
                    if let Value::Array(mut incoming) = one_of {
                        existing.append(&mut incoming);
                    }
                }
                _ => {
                    obj.insert("anyOf".to_string(), one_of);
                }
            }
        }

        // Recurse into anyOf/oneOf variants (allOf is already unwrapped above)
        for key in ["anyOf", "oneOf"] {
            if let Some(variants) = obj.get_mut(key)
                && let Value::Array(variants_array) = variants
            {
                for variant in variants_array.iter_mut() {
                    sanitize_node(variant);
                }
            }
        }
    }
}

#[cfg(feature = "audio")]
pub use audio_generation::{TTS_1, TTS_1_HD};

pub use streaming::*;
pub use transcription::*;
