@done
@blob
@refactor
@persistence
@rust
@napi
@rpc
@session-management
@RPC-034
Feature: Lift BlobStore into codelet-core::persistence::blob
  """
  Layout: create rust/core/src/persistence/blob.rs (lifted from rust/napi/src/persistence/blob.rs ~186 lines) holding the `BlobStore` struct + `should_use_blob_storage` free function + `compute_sha256` helper + the `BLOB_STORE` lazy_static singleton + the `init_blob_store/store_blob/get_blob/blob_exists` free-function facade + the test-only accessors (`is_blob_store_initialized_for_tests`, `reset_blob_store_for_tests`). Create rust/core/src/persistence/blob_processing.rs (lifted from rust/napi/src/persistence/blob_processing.rs ~227 lines) holding `BLOB_REF_PREFIX` + `is_blob_reference` + `extract_blob_hash` + `make_blob_reference` + `maybe_store_blob` + `process_envelope_for_blob_storage` + `rehydrate_envelope_blobs`. Update rust/core/src/persistence/mod.rs to add `pub mod blob; pub mod blob_processing; pub use blob::*; pub use blob_processing::*;`.
  codelet-core/Cargo.toml gains two direct dependencies (workspace-shared): `sha2.workspace = true` is already present (RPC-032 added it), and the new direct deps are `sha2` (re-used by the lifted blob.rs compute_sha256) and `hex = "0.4"` is also already present (RPC-032). No new dependencies are needed for blob.rs. For blob_processing.rs the MessageEnvelope+MessagePayload+UserContent+AssistantContent+DocumentSource+ImageSource types are already present from RPC-031 (`crate::persistence::messages` not needed). serde_json is already a workspace dep.
  NAPI shim shrinks: rust/napi/src/persistence/blob.rs is DELETED outright (BlobStore + should_use_blob_storage moved to core), rust/napi/src/persistence/blob_processing.rs is DELETED outright (envelope helpers moved to core), rust/napi/src/persistence/mod.rs loses the `mod blob; mod blob_processing;` declarations, loses the `lazy_static! { BLOB_STORE }` singleton, loses the `init_blob_store/store_blob/get_blob/blob_exists` free-function facade, loses the local `ensure_directories` helper (no remaining callers after the BLOB_STORE move — verify with a final grep), loses the BLOB_STORE-reset block inside `set_data_directory`, and keeps only: (a) the wrapping `set_data_directory` that delegates the persistence reset to `codelet_core::persistence::reset_stores_for_tests` (now widened to cover the BLOB_STORE) and still resets credentials + graph, (b) the `get_data_dir` delegator, (c) the History wrappers (add_history_entry/get_history/search_history), (d) the `pub use codelet_core::persistence::*;` flat re-export, (e) the conditional `mod napi_bindings` / `mod tests` / `mod lazy_init_tests` declarations. End-state: rust/napi/src/persistence/ contains ONLY napi_bindings.rs + tests.rs + lazy_init_tests.rs + a ~30-line mod.rs.
  Test coverage strategy: matches RPC-031/RPC-032/RPC-033 — write a `rust/core/tests/blob_store_lifted_test.rs` integration test that consumes the lifted surface via `codelet_core::persistence::{BlobStore, store_blob, get_blob, blob_exists, process_envelope_for_blob_storage, rehydrate_envelope_blobs, BLOB_REF_PREFIX, is_blob_reference, extract_blob_hash, make_blob_reference, should_use_blob_storage}` (proving the public surface is reachable without codelet-napi), plus a `rust/napi/tests/blob_store_lift_shim_test.rs` that imports the same symbols via `codelet_napi::persistence::*` and asserts compile-time identity (same pattern as RPC-031's message_envelope_lift_shim_test.rs). The existing in-crate `cargo test -p codelet-napi persistence::tests` 48-test suite continues to run unchanged via the re-export shim — including the 12 blob-specific tests (test_blob_reference_format, test_tool_result_blob_storage_and_rehydration, test_blob_storage_dedup, test_image_blob_storage_and_rehydration, test_document_blob_storage_and_rehydration, test_thinking_content_blob_storage, test_tool_use_input_blob_storage_with_marker, test_multi_content_envelope_dedup, test_blob_threshold variants, test_blob_storage_threshold).
  Singleton ownership transition: the BLOB_STORE lazy_static global moves from rust/napi/src/persistence/mod.rs into rust/core/src/persistence/blob.rs. lazy_init_tests.rs in NAPI currently reads BLOB_STORE directly via `super::*` (line 40-44) — after the lift it switches to the test-only accessor `codelet_core::persistence::is_blob_store_initialized_for_tests()` (matching the pattern RPC-033 introduced for MESSAGE_STORE and SESSION_STORE: `codelet_core::persistence::is_message_store_initialized_for_tests()`). rust/core/src/persistence/manifest.rs's existing `reset_stores_for_tests` is widened to also reset the BLOB_STORE singleton (or a new sibling `reset_blob_store_for_tests` is added if separation is preferred). Clippy compliance: codelet-core enforces workspace lints (redundant_closure_for_method_calls, needless_collect, etc.) that codelet-napi does not. The lifted code must pass `cargo clippy -p codelet-core --lib --no-deps` cleanly.
  Caller audit (post-lift expected paths): (a) rust/napi/src/session_search_handler.rs:482,492 — currently writes `persistence::get_blob` + `crate::persistence::extract_blob_hash`; after the lift these still resolve via the NAPI re-export shim with zero source changes. (b) rust/napi/src/persistence/napi_bindings.rs:241-256,580-583 — currently writes `store_blob/get_blob/blob_exists` + `use super::blob_processing::{process_envelope_for_blob_storage, rehydrate_envelope_blobs}`; the `super::blob_processing::*` import is rewritten to `use crate::persistence::{process_envelope_for_blob_storage as process_envelope_impl, rehydrate_envelope_blobs as rehydrate_envelope_impl};` (or just `super::*` since the flat re-export covers it). (c) rust/napi/src/persistence/tests.rs:886,935,975,1023,1051,1104,1148,1201,1234,1281,1345,1428,1430,1485,1520,1576,1628,1682 — currently writes `super::blob_processing::{extract_blob_hash, is_blob_reference, make_blob_reference, process_envelope_for_blob_storage, rehydrate_envelope_blobs}`; the `super::blob_processing::` path no longer resolves after deletion, so each call site is rewritten to `super::{...}` (or qualified path) — this is a mechanical sed replacement, not a logic change. (d) rust/napi/src/persistence/lazy_init_tests.rs:40 — the `BLOB_STORE.lock().map(...)` reference is replaced with the `codelet_core::persistence::is_blob_store_initialized_for_tests()` test-only accessor.
  """

  # ========================================
  # EXAMPLE MAPPING CONTEXT
  # ========================================
  #
  # BUSINESS RULES:
  #   1. BlobStore (struct + impl, including SHA-256 store/get/exists/delete/total_size and the should_use_blob_storage free function) lives in rust/core/src/persistence/blob.rs with the BLOB_THRESHOLD constant value preserved exactly (10 * 1024 bytes) — no #[napi] attributes added
  #   2. Envelope blob helpers (BLOB_REF_PREFIX constant, is_blob_reference, extract_blob_hash, make_blob_reference, process_envelope_for_blob_storage, rehydrate_envelope_blobs) live in rust/core/src/persistence/blob_processing.rs and consume the lifted MessageEnvelope + MessagePayload + UserContent + AssistantContent + DocumentSource + ImageSource types directly from codelet-core (lifted by RPC-031)
  #   3. The BLOB_STORE lazy_static singleton plus the store_blob/get_blob/blob_exists/init_blob_store free-function facade move from rust/napi/src/persistence/mod.rs into codelet-core::persistence::blob so the lifted BlobStore owns its own global state — matching the RPC-033 precedent for MESSAGE_STORE and SESSION_STORE
  #   4. rust/napi/src/persistence/blob.rs and rust/napi/src/persistence/blob_processing.rs are deleted outright — rust/napi/src/persistence/mod.rs shrinks further (the blob/blob_processing module declarations and the BLOB_STORE singleton + store_blob/get_blob/blob_exists facade are removed) and continues to re-export the entire lifted surface via `pub use codelet_core::persistence::*;`
  #   5. On-disk format is byte-identical: blob files continue to live at {data_dir}/blobs/{first2hex}/{full_hash} with no leading prefix on the filename, and the wire-format BLOB_REF_PREFIX value remains exactly the string "blob:sha256:" — agents that hold pre-lift blob references must still resolve
  #   6. BlobStore::new() in the lifted location resolves the data directory via codelet_common::get_data_dir() and creates {data_dir}/blobs/ with std::fs::create_dir_all — it does NOT depend on the NAPI-local ensure_directories helper (matching the RPC-032/RPC-033 lifted pattern for MessageStore::new and SessionStore::new)
  #   7. codelet-napi's set_data_directory (in rust/napi/src/persistence/mod.rs) no longer pokes a NAPI-local BLOB_STORE — instead the new codelet_core::persistence::reset_stores_for_tests helper is widened to also reset the lifted BLOB_STORE singleton alongside MESSAGE_STORE + SESSION_STORE + HistoryStore, and ensure_directories is either deleted (its only remaining caller was internal to napi::persistence::blob::BlobStore::new) or kept as a thin shim that delegates to a codelet-core helper
  #   8. Test-only accessor functions (is_blob_store_initialized_for_tests, reset_blob_store_for_tests) are exposed by codelet-core so that codelet-napi's existing lazy_init_tests.rs can continue to assert per-store lazy initialization without re-introducing a direct reference to the moved BLOB_STORE lazy_static global — matching the test-only accessor pattern RPC-033 introduced for MESSAGE_STORE and SESSION_STORE
  #   9. Every existing `crate::persistence::{BlobStore, store_blob, get_blob, blob_exists, BLOB_REF_PREFIX, is_blob_reference, extract_blob_hash, make_blob_reference, process_envelope_for_blob_storage, rehydrate_envelope_blobs, should_use_blob_storage}` import inside codelet-napi continues to compile unchanged via the flat re-export `pub use codelet_core::persistence::*;` — including session_search_handler.rs (uses get_blob + extract_blob_hash), session_manager.rs (uses get_blob + is_blob_reference via session_search_handler), persistence/napi_bindings.rs (uses process_envelope_for_blob_storage + rehydrate_envelope_blobs + store_blob + get_blob + blob_exists), and persistence/tests.rs (uses get_blob + store_blob + extract_blob_hash + is_blob_reference + make_blob_reference + process_envelope_for_blob_storage + rehydrate_envelope_blobs)
  #   10. The forward-reference left behind by RPC-031 in rust/core/src/persistence/message_envelope.rs (the comment near line 270 noting that the `test_blob_threshold` test stays in the NAPI shim because `should_use_blob_storage` lives in napi::persistence::blob) is resolved — either by moving the test_blob_threshold test next to the lifted should_use_blob_storage in rust/core/src/persistence/blob.rs, or by updating the comment to reflect that should_use_blob_storage now lives in codelet-core
  #
  # EXAMPLES:
  #   1. Round-trip: a 15KB tool_result payload pushed through codelet_core::persistence::process_envelope_for_blob_storage produces an envelope whose UserContent::ToolResult content is replaced with `blob:sha256:<64hex>`; calling codelet_core::persistence::get_blob with that hash returns the original 15KB bytes; calling codelet_core::persistence::rehydrate_envelope_blobs on the processed envelope JSON returns an envelope JSON whose tool_result content equals the original 15KB string
  #   2. Dedup: storing the same 5MB blob twice via codelet_core::persistence::store_blob returns the identical SHA-256 hash both times and the on-disk {data_dir}/blobs/{first2}/{hash} file is written only once (no .tmp leftover after the second call)
  #   3. Forbidden arrow: codelet-rpc-embedded (which depends on codelet-core but is forbidden from depending on codelet-napi by rpc_006_source_shape.rs) can `use codelet_core::persistence::{BlobStore, store_blob, get_blob, blob_exists, is_blob_reference, extract_blob_hash, make_blob_reference, process_envelope_for_blob_storage, rehydrate_envelope_blobs, should_use_blob_storage, BLOB_REF_PREFIX}` and link successfully — proving the forbidden rpc to napi arrow is not re-introduced
  #   4. Shim equivalence: a NAPI test that writes `use codelet_napi::persistence::{BlobStore, get_blob, store_blob, BLOB_REF_PREFIX, is_blob_reference, make_blob_reference, extract_blob_hash, process_envelope_for_blob_storage, rehydrate_envelope_blobs, should_use_blob_storage}` continues to compile and run after blob.rs and blob_processing.rs are deleted from codelet-napi
  #   5. Compatibility with pre-lift blobs: a blob file written by the pre-lift NAPI BlobStore at {data_dir}/blobs/ab/abcdef...full_64_hex still resolves via codelet_core::persistence::get_blob("abcdef...full_64_hex") returning the same bytes — proving the on-disk layout hash-to-path mapping (first 2 hex chars as subdir + full hash as filename) is unchanged
  #   6. All NAPI persistence test suites continue to pass after the blob lift: `cargo test -p codelet-napi persistence::tests` (the 48-test suite including test_blob_reference_format, test_tool_result_blob_storage_and_rehydration, test_blob_storage_dedup, image/document/thinking blob round-trip tests, and the multi-content envelope dedup test), `cargo test -p codelet-napi persistence::lazy_init_tests` (the 9-test suite including the BUG-122 BlobStore lazy-init invariant assertions), and the cross-test blob references in `cargo test -p codelet-napi --test session_persistence_test` all pass via the re-export shim with no test source modifications
  #   7. Lazy init parity: after `codelet_napi::persistence::set_data_directory(tmp_dir)` is called and the test asserts `codelet_core::persistence::is_blob_store_initialized_for_tests()` returns false, a single call to `codelet_core::persistence::store_blob(&large_bytes)` initialises only the BLOB_STORE singleton (the MESSAGE_STORE + SESSION_STORE + HistoryStore initialisation flags remain false) — and the BlobStore is NOT initialized by append_message (per BUG-122)
  #
  # ========================================
  Background: User Story
    As a fspec backend engineer
    I want to lift BlobStore + blob_processing out of codelet-napi into codelet-core::persistence::blob and codelet-core::persistence::blob_processing
    So that codelet-rpc-embedded codelet-rpc-server and the upcoming codelet-sessions crate can hash-store and rehydrate envelope blobs without re-introducing a forbidden rpc to napi arrow while the on-disk content-addressed blob layout and the BLOB_REF_PREFIX wire format remain byte-identical

  Scenario: Envelope tool_result round-trips through the lifted blob storage in codelet-core
    Given a fresh data directory is configured via codelet_common::set_data_directory
    And a user MessageEnvelope is constructed with one UserContent::ToolResult whose content is a 15KB string of ASCII bytes
    When codelet_core::persistence::process_envelope_for_blob_storage is called on the envelope
    Then the processed envelope's UserContent::ToolResult content is exactly the string "blob:sha256:" followed by a 64 hex character SHA-256 digest
    And codelet_core::persistence::get_blob called with that hash returns the original 15KB byte sequence
    And codelet_core::persistence::rehydrate_envelope_blobs called on the processed envelope JSON returns an envelope JSON whose tool_result content equals the original 15KB string

  Scenario: Identical blobs deduplicate to a single on-disk file
    Given a fresh data directory is configured via codelet_common::set_data_directory
    And a 5MB buffer of deterministic bytes is prepared
    When codelet_core::persistence::store_blob is called twice with that same buffer
    Then both calls return the identical SHA-256 hash string
    And exactly one file exists at {data_dir}/blobs/{first2hex}/{full_hash} and no .tmp file is left behind

  Scenario: codelet-core consumers can hash-store and rehydrate envelope blobs without depending on codelet-napi
    Given codelet_core::persistence exports BlobStore store_blob get_blob blob_exists is_blob_reference extract_blob_hash make_blob_reference process_envelope_for_blob_storage rehydrate_envelope_blobs should_use_blob_storage and BLOB_REF_PREFIX
    When a downstream crate that does not depend on codelet-napi writes `use codelet_core::persistence::{BlobStore, store_blob, get_blob, blob_exists, is_blob_reference, extract_blob_hash, make_blob_reference, process_envelope_for_blob_storage, rehydrate_envelope_blobs, should_use_blob_storage, BLOB_REF_PREFIX}`
    Then the build succeeds with no transitive dependency on codelet-napi
    And the dependency-rule test rpc_006_source_shape.rs continues to pass

  Scenario: Pre-lift blob files at {data_dir}/blobs/{first2}/{hash} remain resolvable
    Given a fresh data directory is configured via codelet_common::set_data_directory
    And a blob file is manually written at {data_dir}/blobs/{first2hex}/{full_64_hex} containing a known byte sequence, where {full_64_hex} is the SHA-256 of those bytes and {first2hex} is its first two hex characters
    When codelet_core::persistence::get_blob is called with that hash string
    Then the returned bytes equal the bytes that were manually written
    And codelet_core::persistence::blob_exists with the same hash returns true

  Scenario: BLOB_REF_PREFIX wire-format value is preserved exactly
    Given codelet_core::persistence::BLOB_REF_PREFIX is imported
    When the constant value is inspected and combined with a 64 hex character hash via make_blob_reference
    Then BLOB_REF_PREFIX equals the string "blob:sha256:" exactly
    And is_blob_reference returns true for the combined string and extract_blob_hash returns Some with the original 64 hex characters

  Scenario: should_use_blob_storage preserves the 10KB threshold from the pre-lift implementation
    Given codelet_core::persistence::should_use_blob_storage is imported
    When should_use_blob_storage is called with a 100 byte slice and again with a 20000 byte slice
    Then the 100 byte call returns false and the 20000 byte call returns true
