@done
@codelet
@session-management
@infrastructure
@rpc
@RPC-040
Feature: Move SessionManager from codelet-napi into codelet-sessions
  """
  Architecture: This card lifts FOUR things into codelet-sessions: (1) SessionManager struct + impl + Default, (2) ChainOfCommand struct + impl + Default, (3) the entire `crate::navigation` module (~285 lines, no napi deps once its only `use crate::session_manager::{BackgroundSession, ChainOfCommand};` is rewritten to point at codelet_sessions::), (4) the NAPI-free portion of `crate::credentials` (mod.rs / resolver.rs / store.rs / types.rs; only napi_bindings.rs stays in napi as a thin shim). All four lifts collectively eliminate every `crate::*` reference inside the moved SessionManager methods that the attachment names as a problem
  Architecture: The napi-specific subsystems that SessionManager methods reach for (agent_loop, scheduler engine, footer poller, GLOBAL_CHUNK_CALLBACK, LoopStore) STAY napi-side and are injected via a new `SessionManagerHooks` trait stored as `hooks: ArcSwap<Arc<dyn SessionManagerHooks>>` on SessionManager. The default hooks (NoopSessionManagerHooks) are no-ops so the fspec binary in RPC-044 gets a fully-default SessionManager with no behaviour. The napi side at startup calls `SessionManager::instance().set_hooks(Arc::new(NapiSessionManagerHooks))` to install the JS-bridge behaviour. Trait methods needed for this card: spawn_agent_loop, spawn_scheduler, ensure_scheduler_running_for_loop, spawn_footer_poller, stop_footer_poller, cleanup_session_loops, emit_isolation_state_change
  Architecture: The attachment cites SessionManager at lines 3141-4025 but the actual span is 2135-3013 (confirmed by grep of `^pub struct SessionManager` and the matching closing `}`). Methods documented in the attachment exist at slightly shifted lines: instance() at 2246 (not 3250), create_session_with_id at 2264 (not 3268), create_isolated_session_with_id at 2538 (not 3542), list_sessions at 2798 (not 3802), destroy_session at 2939 (not 3943), supervisor delegation at 2989-3011 (not 3993-4013). The ~1100-line offset is consistent — the napi file accumulated ~1100 LOC of additional code (tests, helpers) between the attachment authoring date (2026-05-19) and today (2026-05-21). All implementation work uses the actual current line numbers
  Architecture: IsolatedSessionResult conversion strategy — the `#[napi(object)] pub struct IsolatedSessionResult` at codelet/napi/src/session_manager.rs:5258-5267 STAYS in napi (it carries the JS-bridge shape). The moved SessionManager::create_isolated_session_with_id returns `codelet_rpc_types::IsolatedSessionInfo` (already lifted by RPC-036). NAPI provides `impl From<codelet_rpc_types::IsolatedSessionInfo> for IsolatedSessionResult` so the #[napi] free function `session_manager_create_isolated` just maps the result. The TS surface is byte-stable
  Architecture: Following the RPC-039 review-findings pattern, this card adds new dependency-rule tests at codelet/sessions/tests/session_manager_shape.rs that mirror background_session_shape.rs — each Gherkin scenario gets one `#[test] fn scenario_*()` with `@step` comments matching every Gherkin step verbatim. We do NOT add new clippy passes here (the same `#![allow(clippy::expect_used, ...)]` carry-overs from napi will need re-tightening — explicitly out of scope, tracked by RPC-042). The new shape test file MUST be added to coverage with accurate line ranges to avoid the line-drift class of bug found in the RPC-039 review (every scenario's testLines must point at the actual #[test] fn span, not a guesstimate)
  """

  # ========================================
  # EXAMPLE MAPPING CONTEXT
  # ========================================
  #
  # BUSINESS RULES:
  #   1. The complete SessionManager struct + impl currently at codelet/napi/src/session_manager.rs lines 2135-3013 lives in codelet/sessions/src/session_manager.rs after the move (NOT lines 3141-4025 as quoted in the attachment — the codebase has drifted; the actual span is 2135-3013 confirmed by AST inspection)
  #   2. ChainOfCommand (struct + Default + impl + cleanup_subordinate + is_empty + supervisor/subordinate methods) currently at codelet/napi/src/session_manager.rs lines 354-512 is lifted into codelet-sessions alongside SessionManager because SessionManager owns it as a field (chain_of_command: ChainOfCommand at line 2138). It lives in its own module codelet/sessions/src/chain_of_command.rs and is re-exported by codelet-sessions/src/lib.rs (pub mod chain_of_command;) so callers can use codelet_sessions::ChainOfCommand
  #   3. No napi:: references appear inside codelet/sessions/src/session_manager.rs and codelet/sessions/src/chain_of_command.rs — every napi::bindgen_prelude::Result<T> (Result is the NAPI Result alias from `use napi::bindgen_prelude::*;`) becomes anyhow::Result<T> or Result<T, String>, every napi::Error::from_reason(msg) becomes a plain String error (or anyhow::anyhow!(msg)), and the #[napi(object)] attribute on IsolatedSessionResult is removed (the wire type IsolatedSessionInfo from codelet_rpc_types::IsolatedSessionInfo replaces it in the moved code; the NAPI #[napi(object)] IsolatedSessionResult struct stays in codelet/napi as a thin From<IsolatedSessionInfo> wrapper for the existing #[napi] session_manager_create_isolated free function)
  #   4. Inside the moved session_manager.rs no `crate::navigation::` references remain — codelet/napi/src/navigation.rs (~285 lines, NAPI-free already except for its `use crate::session_manager::{BackgroundSession, ChainOfCommand};` import) is lifted to codelet/sessions/src/navigation.rs with the import rewritten to `use crate::background_session::BackgroundSession; use crate::chain_of_command::ChainOfCommand;`. The lifted module is re-exported by codelet-sessions/src/lib.rs (pub mod navigation;). The methods get_next_session, get_prev_session, get_first_session resolve their navigation paths to codelet_sessions::navigation::{build_navigation_list, get_next_target, get_prev_target, NavigationTarget}
  #   5. Inside the moved session_manager.rs no `crate::credentials::` references remain — the NAPI-free portion of codelet/napi/src/credentials/ (mod.rs, resolver.rs, store.rs, types.rs; total ~16kB; the only napi:: dep is napi_bindings.rs which stays in NAPI) is lifted to codelet/sessions/src/credentials/ and re-exported by codelet-sessions/src/lib.rs (pub mod credentials;). The single call site `crate::credentials::resolve_and_set_env_var(...)` inside create_session_with_id and create_isolated_session_with_id becomes `codelet_sessions::credentials::resolve_and_set_env_var(...)`. The NAPI-side napi_bindings.rs is rewritten to call the lifted module via codelet_sessions::credentials::*
  #   6. Inside the moved session_manager.rs no `crate::scheduler::` references remain, and no references to the NAPI free functions `spawn_footer_poller`, `stop_footer_poller`, `agent_loop`, `init_block_notification_callbacks`, `init_bridge_metadata_providers`, or the NAPI static GLOBAL_CHUNK_CALLBACK — these subsystems stay napi-side for this card. Their call sites inside SessionManager methods (agent_loop spawn at line 2500/2761, spawn_footer_poller at line 2523/2780, stop_footer_poller at line 2956, crate::scheduler::spawn_scheduler at line 2845/2863, crate::scheduler::LoopStore::instance() at line 2961, GLOBAL_CHUNK_CALLBACK at line 2517/2771) are rewired to call methods on a `hooks: Arc<dyn SessionManagerHooks>` field stored on SessionManager. The `SessionManagerHooks` trait (defined in codelet-sessions) declares: spawn_agent_loop, spawn_scheduler, ensure_scheduler_running_for_loop, spawn_footer_poller, stop_footer_poller, cleanup_session_loops, emit_isolation_state_change. A `NoopSessionManagerHooks` default impl returns no-op for every method so the trait object can be defaulted on `new()`. The napi side at `instance()` startup installs a `NapiSessionManagerHooks` impl that delegates to the existing napi-side helpers — so existing TS behaviour is preserved end-to-end
  #   7. SessionManager gains three new broadcast-sender fields per the attachment: `chunks_tx: broadcast::Sender<(SessionId, StreamChunk)>`, `logs_tx: broadcast::Sender<LogRecord>`, `status_changes_tx: broadcast::Sender<(SessionId, SessionStatus)>`. They are initialized in `new()` via `broadcast::channel(SUPERVISOR_BROADCAST_CAPACITY).0` (or a dedicated CHUNKS_CHANNEL_CAPACITY const) and exposed via accessors `chunks_tx(&self) -> &broadcast::Sender<...>`, `logs_tx(&self)`, `status_changes_tx(&self)`. The fields exist but BackgroundSession::handle_output is NOT yet rewired to use them (that is explicitly RPC-041's deliverable) — the existing GLOBAL_CHUNK_CALLBACK fan-out in napi keeps working unchanged via the SessionManagerHooks.emit_isolation_state_change hook for the IsolationStateChange chunks at lines 2517/2771
  #   8. SessionManager::instance() remains a global singleton living in codelet-sessions, NAPI accesses it through `pub use codelet_sessions::session_manager::SessionManager;` at the top of codelet/napi/src/session_manager.rs. The napi lib.rs (or session_manager.rs) startup path installs the napi-specific hooks by calling `SessionManager::instance().set_hooks(Arc::new(NapiSessionManagerHooks::default()))` once at module init. The fspec binary in RPC-044 will NOT use instance() — it constructs its own Arc<SessionManager> via `SessionManager::new()` (with default no-op hooks), per the attachment's behavioural notes
  #   9. The build invariants ALL hold after the move: `cargo build -p codelet-sessions` succeeds, `cargo build -p codelet-napi` succeeds (re-exports keep SessionManager, ChainOfCommand, and the #[napi] free functions session_manager_create / session_manager_create_isolated / session_manager_list / session_manager_destroy / session_set_global_chunk_callback / etc. compiling unchanged), `cargo build -p codelet-napi --release` regenerates codelet/napi/index.d.ts with NO removed or renamed TypeScript symbols and no field reorders, `cargo metadata -p codelet-sessions --format-version 1` reports zero `codelet-napi` package entries in the transitive dependency graph (the same forbidden-arrow invariant locked in by codelet/sessions/tests/skeleton_invariants.rs), and `cargo clippy -p codelet-sessions --all-targets -- -D warnings` passes (the codelet-sessions crate inherits workspace lints whereas the napi crate does not — same situation as RPC-039)
  #   10. All pre-existing in-file napi unit tests still pass via re-exports — the ChainOfCommand tests in codelet/napi/src/session_manager.rs (lines 1180-1450: test_register_supervisor_for_subordinate_session, test_subordinate_with_multiple_supervisors, test_query_subordinate_for_supervisor, test_remove_supervisor_relationship, test_supervisor_can_observe_multiple_subordinates, test_duplicate_subordinate_under_same_supervisor_rejected, test_circular_supervision_prevented, test_regular_session_has_no_subordinate, test_cleanup_supervisors_when_subordinate_removed) continue to compile and pass against the re-exported ChainOfCommand symbol. The NAPI-side scheduler/agent_job/trigger/catch_up/engine references to `crate::session_manager::SessionManager::instance()` still resolve through the re-export. The codelet/sessions/tests/smoke.rs crate_compiles test continues to pass
  #   11. No behavioural changes are introduced — this is a code move + import-path rewrite + hook indirection. Specifically: (a) the IsolatedSessionResult NAPI-shape wrapper at codelet/napi/src/session_manager.rs:5258-5267 stays in NAPI but its From<codelet_sessions::session_manager::IsolatedSessionInfo> impl produces the JS-facing shape so the TS `Promise<IsolatedSessionResult>` signature on session_manager_create_isolated is preserved verbatim; (b) the napi-side error mapping is updated to convert anyhow::Error / String into napi::Error::from_reason at the wire boundary inside each #[napi] wrapper; (c) the spawn_scheduled_session method (called only by the scheduler trigger.rs) preserves its error contract by returning Result<(), String>; (d) the IsolationStateChange chunk emitted at lines 2517/2771 still reaches GLOBAL_CHUNK_CALLBACK via the NapiSessionManagerHooks.emit_isolation_state_change hook, so TS still sees both create paths firing IsolationStateChange chunks at exactly the same line offsets in the session lifecycle
  #
  # EXAMPLES:
  #   1. Developer runs `cargo build -p codelet-sessions` — build succeeds and the resulting library exposes `codelet_sessions::session_manager::SessionManager`, `codelet_sessions::chain_of_command::ChainOfCommand`, `codelet_sessions::navigation::{NavigationTarget, build_navigation_list, get_next_target, get_prev_target}`, `codelet_sessions::credentials::{resolve_and_set_env_var, resolve_credential, ...}`, and `codelet_sessions::session_manager::{SessionManagerHooks, NoopSessionManagerHooks}`
  #   2. Developer runs `cargo build -p codelet-napi` (default features) — build succeeds because codelet/napi/src/session_manager.rs now `pub use codelet_sessions::session_manager::SessionManager;` and `pub use codelet_sessions::chain_of_command::ChainOfCommand;` keep every existing import path resolvable (the scheduler engine, agent_job, trigger and catch_up modules continue to reach `crate::session_manager::SessionManager::instance()` through the re-export)
  #   3. Developer greps `codelet/sessions/src/session_manager.rs` and `codelet/sessions/src/chain_of_command.rs` for the regex `napi::|use napi|#\[napi` and finds zero matches — the moved files have no NAPI references
  #   4. Developer greps `codelet/sessions/src/session_manager.rs` for the regex `crate::scheduler|crate::navigation|crate::credentials|GLOBAL_CHUNK_CALLBACK|spawn_footer_poller|stop_footer_poller|init_block_notification_callbacks|init_bridge_metadata_providers|agent_loop\(` and finds zero matches — every reference to napi-private modules and free functions has been replaced by either a lifted codelet_sessions path or a `self.hooks.<method>(...)` call
  #   5. Developer inspects `SessionManager::create_session_with_id` in the moved file — the signature has dropped napi::Result<()> and is now `pub async fn create_session_with_id(&self, id: &str, model: &str, project: &str, name: &str) -> Result<(), String>`; the body calls `codelet_sessions::credentials::resolve_and_set_env_var(...)` instead of `crate::credentials::resolve_and_set_env_var(...)`; the agent_loop spawn is `self.hooks.spawn_agent_loop(session.clone(), input_rx, mcp_injection_rx)` instead of `tokio::spawn(async move { agent_loop(...).await })`; the footer poller invocation is `self.hooks.spawn_footer_poller(id.to_string(), project.to_string(), None)`; the IsolationStateChange emit is `self.hooks.emit_isolation_state_change(id.to_string(), false, None)`
  #   6. Developer inspects `SessionManager::create_isolated_session_with_id` in the moved file — the signature is `pub async fn create_isolated_session_with_id(&self, id: &str, model: &str, project: &str, name: &str) -> Result<codelet_rpc_types::IsolatedSessionInfo, String>` (returns the wire type, not the napi-shape IsolatedSessionResult); the NAPI #[napi] free function `session_manager_create_isolated` (still in codelet/napi/src/session_manager.rs) wraps the new return type via `.map(IsolatedSessionResult::from)` so the TypeScript `Promise<IsolatedSessionResult>` shape is preserved verbatim
  #   7. Developer inspects SessionManager fields in the moved file — beyond the original five (`sessions: RwLock<IndexMap<Uuid, Arc<BackgroundSession>>>`, `chain_of_command: ChainOfCommand`, `active_session_id: RwLock<Option<Uuid>>`, `scheduler_handle: RwLock<Option<tokio::task::JoinHandle<()>>>`, `default_model: RwLock<Option<String>>`) the struct now has four new fields: `chunks_tx: broadcast::Sender<(SessionId, StreamChunk)>`, `logs_tx: broadcast::Sender<LogRecord>`, `status_changes_tx: broadcast::Sender<(SessionId, SessionStatus)>`, and `hooks: ArcSwap<Arc<dyn SessionManagerHooks>>` (ArcSwap because the napi side replaces the default no-op hooks at startup via SessionManager::instance().set_hooks(...))
  #   8. Developer runs `cargo metadata -p codelet-sessions --format-version 1 | jq '.packages[].name'` and the output contains zero entries equal to `codelet-napi` — no transitive napi dependency. The existing dependency-rule test at codelet/sessions/tests/skeleton_invariants.rs::scenario_codelet_sessions_has_no_transitive_dependency_on_codelet_napi still passes
  #   9. Developer runs `cargo test -p codelet-napi --lib session_manager::tests` (or the more specific `chain_of_command_tests`) — the pre-existing ChainOfCommand tests at codelet/napi/src/session_manager.rs lines 1180-1450 (test_register_supervisor_for_subordinate_session, test_subordinate_with_multiple_supervisors, test_query_subordinate_for_supervisor, test_remove_supervisor_relationship, test_supervisor_can_observe_multiple_subordinates, test_duplicate_subordinate_under_same_supervisor_rejected, test_circular_supervision_prevented, test_regular_session_has_no_subordinate, test_cleanup_supervisors_when_subordinate_removed) all continue to pass via the `pub use codelet_sessions::chain_of_command::ChainOfCommand;` re-export
  #   10. Developer runs `cargo test -p codelet-sessions --tests` — the existing smoke test crate_compiles passes, the skeleton_invariants suite passes, the RPC-039 background_session_shape suite passes, AND a new integration test file codelet/sessions/tests/session_manager_shape.rs adds scenarios that statically reference the moved types: `let _: codelet_sessions::session_manager::SessionManager;`, `let _: codelet_sessions::chain_of_command::ChainOfCommand;`, asserts SessionManager has the four new broadcast/hooks fields by constructing a default and calling .chunks_tx().subscribe() / .logs_tx().subscribe() / .status_changes_tx().subscribe(), asserts the SessionManagerHooks trait is publicly reachable, and asserts NoopSessionManagerHooks::default() can be used to construct a fully-default SessionManager
  #   11. Developer runs `cargo build -p codelet-napi --release` regenerating codelet/napi/index.d.ts — git diff shows no removed or renamed TypeScript symbols compared to the pre-move version: session_manager_create, session_manager_create_isolated, session_manager_list, session_manager_destroy, session_set_global_chunk_callback, and every other #[napi]-decorated free function preserves its exact signature; IsolatedSessionResult preserves its three fields (session_id, worktree_path, base_commit) in the same order
  #   12. Developer inspects how the napi side installs its hooks — a new module codelet/napi/src/session_hooks.rs (or an inline impl in session_manager.rs) defines `pub struct NapiSessionManagerHooks;` and `impl codelet_sessions::SessionManagerHooks for NapiSessionManagerHooks { ... }` that delegates spawn_agent_loop → tokio::spawn(async move { agent_loop(...).await }), spawn_scheduler → crate::scheduler::spawn_scheduler(...), spawn_footer_poller → existing spawn_footer_poller, stop_footer_poller → existing stop_footer_poller, cleanup_session_loops → crate::scheduler::LoopStore::instance().remove_for_session(...), and emit_isolation_state_change → GLOBAL_CHUNK_CALLBACK.get().map(|cb| cb.call(...)). The napi #[napi] init point (#[napi::module_init] or first call to SessionManager::instance()) calls `SessionManager::instance().set_hooks(Arc::new(NapiSessionManagerHooks))`
  #
  # ========================================
  Background: User Story
    As a Rust developer porting SessionManager out of codelet-napi
    I want to move the SessionManager struct + impl (and the ChainOfCommand companion type) into the NAPI-free codelet-sessions crate, with the new broadcast-sender fields added (but unwired) and the few NAPI-private dependencies lifted or hook-injected
    So that the codelet-sessions crate exposes a complete agent-loop owner that both the fspec binary (RPC-044) and the codelet-napi thin adapter (RPC-043) consume via the same Rust API, with zero transitive napi entries in its dependency graph

  Scenario: codelet-sessions builds standalone with SessionManager, ChainOfCommand, navigation, credentials and the hooks trait at their new home
    Given the SessionManager and ChainOfCommand structs have been moved into codelet/sessions/src/
    And the crate::navigation module has been lifted to codelet/sessions/src/navigation.rs
    And the NAPI-free portion of crate::credentials has been lifted to codelet/sessions/src/credentials/
    And the SessionManagerHooks trait plus NoopSessionManagerHooks default impl have been added to codelet/sessions/src/session_manager.rs
    When I run `cargo build -p codelet-sessions`
    Then the build completes successfully with no errors
    And the public paths codelet_sessions::session_manager::SessionManager, codelet_sessions::chain_of_command::ChainOfCommand, codelet_sessions::navigation::{NavigationTarget, build_navigation_list, get_next_target, get_prev_target}, codelet_sessions::credentials::resolve_and_set_env_var, and codelet_sessions::session_manager::{SessionManagerHooks, NoopSessionManagerHooks} all resolve at compile time

  Scenario: codelet-napi still builds against the re-exported SessionManager and ChainOfCommand
    Given codelet/napi/src/session_manager.rs now `pub use`s SessionManager and ChainOfCommand from codelet-sessions
    And the NAPI-side scheduler/agent_job/trigger/catch_up/engine modules continue to reach `crate::session_manager::SessionManager::instance()` through the re-export
    When I run `cargo build -p codelet-napi`
    Then the build completes successfully with no errors
    And the rest of session_manager.rs (the agent_loop free function, the #[napi] free functions session_manager_create / session_manager_create_isolated / session_manager_list / session_manager_destroy / session_set_global_chunk_callback / session_manager_add_supervisor / etc., the in-file unit-test module) resolves every SessionManager and ChainOfCommand path through the re-exports

  Scenario: The moved session_manager.rs and chain_of_command.rs have no napi:: references
    Given the SessionManager and ChainOfCommand code has been moved into codelet/sessions/src/
    When I grep codelet/sessions/src/session_manager.rs and codelet/sessions/src/chain_of_command.rs for the regex `napi::|use napi|#\[napi`
    Then I find zero matches in either file

  Scenario: The moved session_manager.rs has no crate references to napi-private modules or free functions
    Given the SessionManager code has been moved into codelet/sessions/src/session_manager.rs
    When I grep the moved file for the regex `crate::scheduler|crate::navigation|crate::credentials|GLOBAL_CHUNK_CALLBACK|spawn_footer_poller|stop_footer_poller|init_block_notification_callbacks|init_bridge_metadata_providers|agent_loop\(`
    Then I find zero matches in codelet/sessions/src/session_manager.rs
    And every former `crate::navigation::*` path resolves to `codelet_sessions::navigation::*`
    And every former `crate::credentials::*` path resolves to `codelet_sessions::credentials::*`
    And every former `crate::scheduler::*` call resolves to `self.hooks.<method>(...)`
    And every former GLOBAL_CHUNK_CALLBACK call resolves to `self.hooks.emit_isolation_state_change(...)`
    And every former spawn_footer_poller/stop_footer_poller call resolves to `self.hooks.spawn_footer_poller(...)` / `self.hooks.stop_footer_poller(...)`
    And every former `tokio::spawn(async move { agent_loop(...).await })` call resolves to `self.hooks.spawn_agent_loop(...)`

  Scenario: create_session_with_id is rewritten to a non-NAPI Result type and routes side-effects through the hooks
    Given the SessionManager code has been moved into codelet/sessions/src/session_manager.rs
    When I inspect the `create_session_with_id` method signature and body in the moved file
    Then the signature is `pub async fn create_session_with_id(&self, id: &str, model: &str, project: &str, name: &str) -> Result<(), String>`
    And every former `napi::Error::from_reason(format!(...))` error path is rewritten to a plain `format!(...)` String error
    And the credential resolution call site uses `codelet_sessions::credentials::resolve_and_set_env_var(...)`
    And the agent_loop spawn site calls `self.hooks.spawn_agent_loop(session.clone(), input_rx, mcp_injection_rx)` instead of `tokio::spawn(async move { agent_loop(...).await })`
    And the footer-poller spawn site calls `self.hooks.spawn_footer_poller(id.to_string(), project.to_string(), None)`
    And the IsolationStateChange emit site calls `self.hooks.emit_isolation_state_change(id.to_string(), false, None)` instead of `GLOBAL_CHUNK_CALLBACK.get().map(|cb| cb.call(...))`

  Scenario: create_isolated_session_with_id returns the wire-type IsolatedSessionInfo and the NAPI wrapper converts to IsolatedSessionResult
    Given the SessionManager code has been moved into codelet/sessions/src/session_manager.rs
    And the wire-portable type codelet_rpc_types::IsolatedSessionInfo was lifted in RPC-036
    When I inspect the `create_isolated_session_with_id` method signature in the moved file
    Then the signature is `pub async fn create_isolated_session_with_id(&self, id: &str, model: &str, project: &str, name: &str) -> Result<codelet_rpc_types::IsolatedSessionInfo, String>`
    And the napi-side #[napi(object)] IsolatedSessionResult struct at codelet/napi/src/session_manager.rs:5258-5267 stays in NAPI carrying the JS-bridge shape
    And NAPI provides `impl From<codelet_rpc_types::IsolatedSessionInfo> for IsolatedSessionResult`
    And the #[napi] free function session_manager_create_isolated maps the Ok value via `.map(IsolatedSessionResult::from)` and maps the String error via `.map_err(napi::Error::from_reason)`

  Scenario: SessionManager gains four new fields beyond the original five
    Given the SessionManager code has been moved into codelet/sessions/src/session_manager.rs
    When I inspect the field list of the SessionManager struct in the moved file
    Then the five original fields (sessions, chain_of_command, active_session_id, scheduler_handle, default_model) are preserved
    And a new field `chunks_tx: broadcast::Sender<(SessionId, StreamChunk)>` exists and is initialized in `new()` via `broadcast::channel(SUPERVISOR_BROADCAST_CAPACITY).0`
    And a new field `logs_tx: broadcast::Sender<LogRecord>` exists and is initialized in `new()`
    And a new field `status_changes_tx: broadcast::Sender<(SessionId, SessionStatus)>` exists and is initialized in `new()`
    And a new field `hooks: ArcSwap<Arc<dyn SessionManagerHooks>>` exists and defaults to `ArcSwap::from_pointee(Arc::new(NoopSessionManagerHooks::default()))`
    And accessor methods `chunks_tx(&self)`, `logs_tx(&self)`, `status_changes_tx(&self)` exist returning a `&broadcast::Sender<...>` so subscribers can call `.subscribe()`
    And BackgroundSession::handle_output is NOT yet rewired to use these fields (that rewiring is explicitly deferred to RPC-041)

  Scenario: codelet-sessions has no transitive dependency on codelet-napi
    Given the SessionManager code has been moved into codelet/sessions/src/session_manager.rs
    When I run `cargo metadata -p codelet-sessions --format-version 1`
    Then the resulting JSON contains zero packages with name `codelet-napi`
    And the existing dependency-rule test at codelet/sessions/tests/skeleton_invariants.rs::scenario_codelet_sessions_has_no_transitive_dependency_on_codelet_napi still passes

  Scenario: Pre-existing ChainOfCommand unit tests in codelet-napi still pass via the re-export
    Given the ChainOfCommand code has been moved into codelet/sessions/src/chain_of_command.rs
    And codelet/napi/src/session_manager.rs `pub use codelet_sessions::chain_of_command::ChainOfCommand;`
    When I run `cargo test -p codelet-napi --lib session_manager`
    Then every pre-existing ChainOfCommand test (test_register_supervisor_for_subordinate_session, test_subordinate_with_multiple_supervisors, test_query_subordinate_for_supervisor, test_remove_supervisor_relationship, test_supervisor_can_observe_multiple_subordinates, test_duplicate_subordinate_under_same_supervisor_rejected, test_circular_supervision_prevented, test_regular_session_has_no_subordinate, test_cleanup_supervisors_when_subordinate_removed) passes with status ok

  Scenario: codelet-sessions tests assert SessionManager is reachable from its new home and the hooks design is sound
    Given the SessionManager code has been moved into codelet/sessions/src/session_manager.rs
    And a new integration test codelet/sessions/tests/session_manager_shape.rs has been added
    When I run `cargo test -p codelet-sessions --tests`
    Then the existing smoke test crate_compiles passes
    And the existing skeleton_invariants suite passes
    And the existing RPC-039 background_session_shape suite passes
    And the new shape test asserts the path `codelet_sessions::session_manager::SessionManager` resolves at compile-time
    And the new shape test asserts the path `codelet_sessions::chain_of_command::ChainOfCommand` resolves at compile-time
    And the new shape test asserts the path `codelet_sessions::navigation::{NavigationTarget, build_navigation_list, get_next_target, get_prev_target}` resolves at compile-time
    And the new shape test asserts the path `codelet_sessions::credentials::resolve_and_set_env_var` resolves at compile-time
    And the new shape test constructs `SessionManager::new()` and calls `.chunks_tx().subscribe()`, `.logs_tx().subscribe()`, `.status_changes_tx().subscribe()` without panicking
    And the new shape test asserts the `SessionManagerHooks` trait and the `NoopSessionManagerHooks` default impl are publicly reachable

  Scenario: NAPI TypeScript surface is byte-stable across the move
    Given the SessionManager code has been moved into codelet/sessions/src/session_manager.rs
    When I run `cargo build -p codelet-napi --release` regenerating codelet/napi/index.d.ts
    Then no TypeScript interface, function, enum, or type alias in the regenerated codelet/napi/index.d.ts is removed
    And no TypeScript interface, function, enum, or type alias is renamed
    And the #[napi] free functions session_manager_create, session_manager_create_isolated, session_manager_list, session_manager_destroy, session_set_global_chunk_callback, session_manager_add_supervisor, session_manager_remove_supervisor, session_manager_get_supervisors, session_manager_get_subordinates, session_manager_get_active, session_manager_set_active, session_manager_clear_active each preserve their exact signature
    And the #[napi(object)] IsolatedSessionResult interface preserves its three fields (session_id, worktree_path, base_commit) in the same order

  Scenario: The napi side installs its hooks at startup so existing TS behaviour is preserved
    Given the SessionManager code has been moved into codelet/sessions/src/session_manager.rs
    And the NAPI side defines `pub struct NapiSessionManagerHooks` implementing `codelet_sessions::SessionManagerHooks`
    When the napi addon initializes (either via `#[napi::module_init]` or on the first call into a #[napi] free function that touches SessionManager::instance())
    Then the napi init path calls `SessionManager::instance().set_hooks(Arc::new(NapiSessionManagerHooks::default()))`
    And NapiSessionManagerHooks::spawn_agent_loop delegates to `tokio::spawn(async move { agent_loop(session, input_rx, mcp_injection_rx).await })` (where agent_loop is still the napi-side free function at codelet/napi/src/session_manager.rs:3620)
    And NapiSessionManagerHooks::spawn_scheduler delegates to `crate::scheduler::spawn_scheduler(project, rt)`
    And NapiSessionManagerHooks::spawn_footer_poller delegates to the existing napi-side spawn_footer_poller free function at codelet/napi/src/session_manager.rs:5104
    And NapiSessionManagerHooks::stop_footer_poller delegates to the existing napi-side stop_footer_poller free function at codelet/napi/src/session_manager.rs:5223
    And NapiSessionManagerHooks::cleanup_session_loops delegates to `crate::scheduler::LoopStore::instance().remove_for_session(session_id)`
    And NapiSessionManagerHooks::emit_isolation_state_change delegates to `GLOBAL_CHUNK_CALLBACK.get().map(|cb| cb.call(session_id, StreamChunk::isolation_state_change(is_isolated, worktree_path)))`
