@done
@RPC-258 @cli @querying @wip
Feature: query-estimate-accuracy CLI subcommand on the standalone fspec Rust binary

  """
  This feature file describes the shell-facing clap subcommand exposed by
  the standalone fspec Rust binary (RPC-258, child of RPC-003). It is the
  CLI front door whose contract MUST match `node dist/index.js
  query-estimate-accuracy` exactly. The dispatcher front door is covered
  by spec/features/query-estimate-accuracy-rust-port.feature.

  Architecture notes:
    - clap subcommand registers ONLY a --format <format> flag (text|json default text)
      to mirror the TS Commander.js registration
    - The bridge module codelet/fspec/src/query_estimate_accuracy.rs marshalls
      the --format flag into the dispatcher JSON shape and delegates to
      fspec_core::commands::query_estimate_accuracy::run
    - On success the rendered text/JSON is written to stdout and the process
      exits 0
    - On any FspecCoreError the message is written to stderr prefixed with
      'Error:' and the process exits 1
    - --help output is generated by the shared formatter in fspec-core and is
      asserted byte-for-byte against the captured TS fixture at
      codelet/fspec/tests/fixtures/help/query-estimate-accuracy.txt
  """

  Background: User Story
    As a fspec maintainer
    I want to invoke the ported Rust `query-estimate-accuracy` command via both the LLM-facing dispatcher and the standalone fspec Rust binary
    So that the canonical TypeScript behaviour ships as a native Rust subcommand with byte-for-byte help and dispatcher parity

  Scenario: Clap exposes query-estimate-accuracy as a subcommand and prints flag-aware --help
    Given the fspec Rust binary at codelet/target/release/fspec has been compiled
    When I run `./codelet/target/release/fspec query-estimate-accuracy --help` from a shell
    Then the command exits 0
    And stdout contains the substring 'query-estimate-accuracy' or 'QUERY-ESTIMATE-ACCURACY'
    And stdout does NOT contain the substring '--work-unit-id'
    And stdout does NOT contain the substring '--by-prefix'
    And stdout does NOT contain the substring '--workspace'

  Scenario: CLI against an empty workspace prints the empty-report header and does not auto-create files
    Given an empty directory with no spec/ subdirectory is set as the current working directory
    When I run `./codelet/target/release/fspec query-estimate-accuracy` from that directory
    Then the command exits 0
    And stdout contains the substring '📊 Estimation Accuracy Report'
    And stdout contains the substring 'No completed work units with estimates and actuals found.'
    And stdout contains the substring 'estimate field (story points)'
    And spec/work-units.json was NOT created in the directory

  Scenario: CLI text output renders the populated By Story Points section
    Given spec/work-units.json contains the done work units AUTH-001 (estimate=1 iterations=1), AUTH-002 (estimate=1 iterations=2), AUTH-003 (estimate=3 iterations=2), AUTH-004 (estimate=5 iterations=2)
    When I run `./codelet/target/release/fspec query-estimate-accuracy`
    Then the command exits 0
    And stdout contains the substring '📊 Estimation Accuracy Report'
    And stdout contains the substring 'By Story Points:'
    And stdout contains the substring '1 points:'
    And stdout contains the substring 'Average iterations: 1.5'
    And stdout contains the substring 'Samples: 2'

  Scenario: CLI --format=json prints pretty-printed JSON to stdout
    Given spec/work-units.json contains the done work unit AUTH-001 (estimate=5 iterations=2)
    When I run `./codelet/target/release/fspec query-estimate-accuracy --format json`
    Then the command exits 0
    And stdout parses as JSON whose root object has a 'byStoryPoints' field
    And the byStoryPoints entry for '5' has avgIterations=2 and samples=1

  Scenario: CLI exits 1 and writes to stderr when work-units.json is malformed
    Given spec/work-units.json exists in the working directory but contains invalid JSON
    When I run `./codelet/target/release/fspec query-estimate-accuracy`
    Then the command exits with code 1
    And stderr contains the substring 'Error:'
    And stderr contains the substring 'Failed to query estimate accuracy:'
    And stderr contains the substring 'Failed to parse work-units.json'

  Scenario: Default combined TUI mode is preserved when no subcommand is provided
    Given the fspec Rust binary has query-estimate-accuracy registered as a clap subcommand alongside daemon, client, status, list-work-units, and list-prefixes
    When I run `./codelet/target/release/fspec --help`
    Then the command exits 0
    And the help output lists query-estimate-accuracy as an available subcommand
    And the long-about description still documents that running fspec with no subcommand enters combined TUI mode

  Scenario: CLI delegates to the same fspec_core function used by the dispatcher
    Given a project root whose spec/work-units.json contains the done work unit AUTH-001 (estimate=5 iterations=2)
    When I dispatch query-estimate-accuracy through fspec_core::dispatch::dispatch_command with format='json'
    Then the dispatcher payload byStoryPoints entry for '5' has samples=1
    And the CLI text output of `fspec query-estimate-accuracy` against the same on-disk state contains the line 'Samples: 1'
    And the CLI bridge module codelet/fspec/src/query_estimate_accuracy.rs contains NO inline aggregation, prefix-grouping, or rendering logic — its only computation is JSON arg marshalling

  Scenario: query-estimate-accuracy --help is byte-for-byte identical to TS reference
    Given the fspec Rust binary at codelet/target/release/fspec has been compiled
    When I run `./codelet/target/release/fspec query-estimate-accuracy --help` piped to non-TTY
    Then the command exits 0
    And stdout is byte-for-byte identical to the fixture at codelet/fspec/tests/fixtures/help/query-estimate-accuracy.txt
    And stdout starts with a blank line followed by 'QUERY-ESTIMATE-ACCURACY'
