@done
@session-management
@refactor
@rpc
@rust
@napi
@persistence
@RPC-035
Feature: Reduce codelet-napi persistence to thin napi_bindings.rs shims
  """
  Final layout: rust/napi/src/persistence/mod.rs becomes a ~15-line file containing exactly: a 5-line doc comment naming this as the NAPI persistence facade, a single `pub use codelet_core::persistence::*;` (the flat re-export that preserves every historical `crate::persistence::Foo` import in codelet-napi), and the `#[cfg(not(feature = "noop"))] mod napi_bindings;` + `#[cfg(not(feature = "noop"))] pub use napi_bindings::*;` declarations. The `#[cfg(test)] mod tests;` and `#[cfg(test)] mod lazy_init_tests;` declarations are deleted (those test files no longer exist in codelet-napi). No pub fn declarations remain in mod.rs.
  napi_bindings.rs imports header: the file opens with two `use` groups — first `use codelet_core::persistence::{ create_session, create_session_with_provider, load_session, resume_last_session, list_sessions, delete_session, rename_session, fork_session, merge_messages, cherry_pick, append_message, append_message_with_metadata, get_message, get_session_messages, get_session_messages_full, update_session_tokens, set_session_tokens, set_compaction_state, clear_compaction_state, cleanup_orphaned_messages, store_blob, get_blob, blob_exists, process_envelope_for_blob_storage, rehydrate_envelope_blobs, MessageEnvelope, MessagePayload, UserContent, AssistantContent, SessionManifest, ForkPoint, MergeRecord, CompactionState, TokenUsage, StoredMessage, HistoryEntry, history, };` (the explicit acknowledgement that codelet-napi consumes these from codelet-core), then `use napi::bindgen_prelude::*;` + `use std::collections::HashMap;` + `use std::path::PathBuf;`. No `use super::*;` line appears. The two history-aliasing wrappers are replaced by direct calls to `history::add`, `history::get`, `history::search` inside the `persistence_add_history`, `persistence_get_history`, `persistence_search_history` bodies.
  set_data_directory inlining: the `#[napi] pub fn persistence_set_data_directory(dir: String) -> Result<()>` body becomes (in pseudo-code) `let path = PathBuf::from(dir); codelet_common::set_data_directory(path).map_err(Error::from_reason)?; codelet_core::persistence::reset_stores_for_tests(); crate::credentials::reset_credential_store(); crate::graph::reset_graph_db(); Ok(())` — i.e. the current mod.rs `set_data_directory` body is inlined verbatim. The matching `persistence_get_data_directory` body becomes `codelet_common::get_data_dir().map(|p| p.to_string_lossy().to_string()).map_err(Error::from_reason)`.
  Test relocation mechanics: (1) `git mv rust/napi/src/persistence/tests.rs rust/core/src/persistence/tests.rs` and `git mv rust/napi/src/persistence/lazy_init_tests.rs rust/core/src/persistence/lazy_init_tests.rs` preserves git blame. (2) Add `#[cfg(test)] mod tests;` + `#[cfg(test)] mod lazy_init_tests;` to rust/core/src/persistence/mod.rs. (3) Replace `use super::*;` at the top of each file with `use crate::persistence::*;` (codelet-core canonical path). (4) Replace the body of `setup_test_env()` (currently `crate::persistence::set_data_directory(temp_dir.path().to_path_buf()).expect(...)`) with the codelet-core-only sequence: `codelet_common::set_data_directory(temp_dir.path().to_path_buf()).expect(...); reset_stores_for_tests();`. (5) Add `tempfile = { workspace = true }` and `lazy_static = { workspace = true }` to rust/core/Cargo.toml under [dev-dependencies] if not already present. (6) Delete the `#[cfg(test)] mod tests; #[cfg(test)] mod lazy_init_tests;` lines from rust/napi/src/persistence/mod.rs.
  Caller audit and ripple effects: a final `rg --hidden -t rust 'use super::\*' rust/napi/src/persistence/` returns zero matches. `rg -t rust 'crate::persistence::set_data_directory' rust/napi/src/` returns only test_support.rs:21 which is rewritten per rule [7]. `rg -t rust 'crate::persistence::ensure_directories' rust/napi/src/` returns zero matches. `rg -t rust 'crate::persistence::add_history_entry|crate::persistence::get_history|crate::persistence::search_history' rust/napi/src/` returns only the calls inside napi_bindings.rs (which now use `history::add`/`history::get`/`history::search` directly). The `#[cfg(test)] mod tests; #[cfg(test)] mod lazy_init_tests;` declarations are removed from rust/napi/src/persistence/mod.rs.
  Test coverage strategy and verification: matches the precedent set by RPC-031/032/033/034 lift cards. (a) Write `rust/core/tests/persistence_shim_layout_test.rs` — a new build-time test that assert-greps the on-disk layout of rust/napi/src/persistence/ to contain only `mod.rs` and `napi_bindings.rs` (using std::fs::read_dir). (b) Capture the SHA-256 of rust/napi/index.d.ts BEFORE the card runs and assert byte-identity AFTER via a shell-driven CI step (or attach the pre-card hash as a fixture and verify it matches). (c) Run all 80+ persistence tests under their NEW codelet-core home and confirm the count is preserved (48 + 9). (d) Confirm `cargo build -p codelet-napi --features napi` AND `cargo build -p codelet-napi --features noop` BOTH succeed (the noop build must continue to compile because the `#[cfg(not(feature = "noop"))]` gate on `mod napi_bindings` is preserved). (e) Confirm `cargo test -p codelet-napi --test session_persistence_test` and `cargo test -p codelet-napi --test subordinate_session_persistence_test` still pass.
  Clippy compliance and lint scope: the relocated test files are compiled under codelet-core's lint configuration (workspace-shared lints enforce `clippy::redundant_closure_for_method_calls`, `clippy::needless_collect`, etc. — stricter than codelet-napi). The existing `#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]` allow at the top of each test file is preserved. Any test that fails the stricter lints under codelet-core gets the minimum `#[allow(...)]` added to its `#[test] fn` rather than relaxing the file-wide attribute. Expect zero or one tests to need additional allows.
  """

  # ========================================
  # EXAMPLE MAPPING CONTEXT
  # ========================================
  #
  # BUSINESS RULES:
  #   1. After this card, rust/napi/src/persistence/ contains exactly two files: mod.rs (~15 lines: doc-comment + flat `pub use codelet_core::persistence::*;` + `mod napi_bindings;` + `pub use napi_bindings::*;` under the `not(feature = "noop")` cfg) and napi_bindings.rs (the only place a `#[napi]` attribute appears in the persistence module). No other .rs files exist in that directory — tests.rs and lazy_init_tests.rs have been relocated to codelet-core, and dead files (storage.rs, types.rs, blob.rs, blob_processing.rs, message_envelope.rs, message_index.rs, history.rs) were already deleted by RPC-031..RPC-034.
  #   2. Every #[napi] persistence_* function inside rust/napi/src/persistence/napi_bindings.rs sources its non-Napi callees through explicit `codelet_core::persistence::{...}` imports (not the loose `use super::*;` re-export trick). The top of napi_bindings.rs imports the lifted symbols via `use codelet_core::persistence::{create_session, create_session_with_provider, load_session, append_message, append_message_with_metadata, get_message, get_session_messages, get_session_messages_full, list_sessions, delete_session, rename_session, fork_session, merge_messages, cherry_pick, update_session_tokens, set_session_tokens, set_compaction_state, clear_compaction_state, cleanup_orphaned_messages, store_blob, get_blob, blob_exists, resume_last_session, process_envelope_for_blob_storage, rehydrate_envelope_blobs, MessageEnvelope, MessagePayload, UserContent, AssistantContent, SessionManifest, TokenUsage, MergeRecord, ForkPoint, CompactionState, StoredMessage, HistoryEntry, history};` so the dependency direction is documented at the call site rather than buried in a wildcard re-export.
  #   3. rust/napi/index.d.ts is byte-identical before and after this card — verified by a build artifact snapshot diff. The TS-facing API surface (every `persistenceXxx` declaration, every `Napi*` interface, and their field orders) is unchanged. This is the primary regression guarantee: the TS frontend continues to call into codelet-napi exactly as it did before RPC-035.
  #   4. The set_data_directory / get_data_dir / ensure_directories / add_history_entry / get_history / search_history helpers currently in rust/napi/src/persistence/mod.rs are absorbed into napi_bindings.rs as inlined call bodies inside the corresponding `#[napi] pub fn persistence_set_data_directory` / `persistence_get_data_directory` / `persistence_add_history` / `persistence_get_history` / `persistence_search_history` entry points. They are no longer declared as standalone `pub fn` items in mod.rs. The credentials + knowledge-graph reset logic that currently lives inside the mod.rs set_data_directory wrapper moves inline into `persistence_set_data_directory` (which is the only non-test caller). The `ensure_directories` helper is deleted from mod.rs entirely — its only test-time callers in codelet-napi switch to calling `codelet_core::persistence::ensure_directories()` directly.
  #   5. The 48-test suite from rust/napi/src/persistence/tests.rs (89,620 bytes) and the 9-test suite from rust/napi/src/persistence/lazy_init_tests.rs (14,680 bytes) are relocated to rust/core/src/persistence/tests.rs and rust/core/src/persistence/lazy_init_tests.rs respectively. The test bodies are unchanged except: (a) `use super::*;` becomes `use crate::persistence::*;` (the canonical path inside codelet-core), (b) the test-only setup helper drops the NAPI-only resets (credentials + knowledge graph) and instead calls `codelet_common::set_data_directory(...)` + `codelet_core::persistence::reset_stores_for_tests()` directly, (c) the `TEST_MUTEX` lazy_static lives in `rust/core/src/persistence/tests.rs` and is exposed as `pub(super)` so `lazy_init_tests.rs` can keep reaching it via `use super::tests::TEST_MUTEX;`.
  #   6. After the test relocation, the test count assertions hold byte-for-byte: `cargo test -p codelet-core --lib persistence::tests` runs the 48 relocated tests, `cargo test -p codelet-core --lib persistence::lazy_init_tests` runs the 9 relocated tests, and `cargo test -p codelet-napi --test session_persistence_test` + `cargo test -p codelet-napi --test subordinate_session_persistence_test` continue to pass (these are the NAPI-bridge-specific integration tests that exercise the `Napi*` wire structs and stay in codelet-napi). No persistence tests are dropped or silently disabled.
  #   7. The `Napi*` wire structs (NapiSessionManifest, NapiForkPoint, NapiMergeRecord, NapiCompactionState, NapiTokenUsage, NapiStoredMessage, NapiHistoryEntry, NapiAppendResult, NapiCherryPickResult) and their `From<…>` impls stay co-located with the bindings inside napi_bindings.rs. Their field order is locked exactly as it appears today so napi-rs's index.d.ts regenerator produces an identical TS surface — any reorder would silently break the TS frontend. The two helper free functions (`truncate_chars` and `calculate_envelope_tokens` and `extract_content_summary`) remain inside napi_bindings.rs since they are NAPI-bridge-only concerns (they translate envelope content into the truncated content-summary string the NAPI `persistence_store_message_envelope` wrapper uses).
  #   8. No additional codelet-core dependency is needed in codelet-napi for this card — codelet-napi already depends on codelet-core (added by RPC-031..RPC-034). No new dependencies are added to either crate. The `tempfile` workspace dep is already pulled into codelet-core's [dev-dependencies] by RPC-032/033/034 lifted-test integration tests; if not, it is added so the relocated `tests.rs` setup helper can use `tempfile::tempdir()` to create isolated test data directories.
  #   9. Acceptable. credentials + knowledge-graph reset is a NAPI-only concern that does not belong in codelet-core. The relocated tests in codelet-core call `codelet_common::set_data_directory(...)` + `codelet_core::persistence::reset_stores_for_tests()` directly. The credentials/graph reset path is exercised by codelet-napi's test_support.rs setup helper (used by the NAPI-bridge integration tests session_persistence_test.rs and subordinate_session_persistence_test.rs which stay in codelet-napi).
  #   10. Option (a). Inline the credentials::reset_credential_store() + graph::reset_graph_db() calls into the body of `persistence_set_data_directory` inside napi_bindings.rs immediately after the codelet_common::set_data_directory and codelet_core::persistence::reset_stores_for_tests calls. This keeps mod.rs at ≤ 20 lines and keeps the NAPI-only reset logic exactly where it executes (the NAPI entry point). rust/napi/src/test_support.rs::setup_test_data_directory continues to call `crate::persistence::persistence_set_data_directory(...)` if it needs the credentials/graph reset — or switches to the test-only path that calls codelet_common::set_data_directory + reset_stores_for_tests + reset_credential_store + reset_graph_db inline.
  #   11. Option (a). Inline the credentials::reset_credential_store() + graph::reset_graph_db() calls into the body of `persistence_set_data_directory` inside napi_bindings.rs immediately after the codelet_common::set_data_directory + codelet_core::persistence::reset_stores_for_tests calls. This keeps mod.rs at ≤ 20 lines and keeps the NAPI-only reset logic exactly where it executes (the NAPI entry point).
  #   12. `cargo build -p codelet-napi --features napi` and `cargo build -p codelet-napi --features noop` both succeed after the move. The `noop` build still excludes napi_bindings.rs via the existing `#[cfg(not(feature = "noop"))]` gate. The `#[cfg(test)]` declarations for the old in-crate test modules (`mod tests;` and `mod lazy_init_tests;`) are removed from `rust/napi/src/persistence/mod.rs` since those files no longer exist in codelet-napi. rust/napi/src/test_support.rs::setup_test_env is rewritten to call `codelet_common::set_data_directory(temp_dir.path().to_path_buf())` + `codelet_core::persistence::reset_stores_for_tests()` + `crate::credentials::reset_credential_store()` + `crate::graph::reset_graph_db()` inline (4 lines), replacing the single call to `crate::persistence::set_data_directory` that no longer exists.
  #
  # EXAMPLES:
  #   1. Directory shape: running `ls rust/napi/src/persistence/` after the card returns exactly two filenames `mod.rs` and `napi_bindings.rs` (no `tests.rs`, no `lazy_init_tests.rs`, no `storage.rs`, no `types.rs`, no `blob.rs`, no `blob_processing.rs`, no `message_envelope.rs`, no `message_index.rs`, no `history.rs`). Running `wc -l rust/napi/src/persistence/mod.rs` returns ≤ 20 lines.
  #   2. index.d.ts byte-identity: a backend engineer captures `sha256sum rust/napi/index.d.ts` BEFORE this card (call it H1), runs the card to completion, then `cargo build -p codelet-napi --release` regenerates the TS declaration file, and `sha256sum rust/napi/index.d.ts` returns the same hash H1. If the hashes differ, the engineer treats it as a regression and audits the field order of the `Napi*` wire structs before merging.
  #   3. Explicit-import documentation: the engineer opens `rust/napi/src/persistence/napi_bindings.rs` and the very first `use` block they read is `use codelet_core::persistence::{create_session, load_session, append_message, append_message_with_metadata, fork_session, merge_messages, cherry_pick, ..., MessageEnvelope, MessagePayload, SessionManifest, TokenUsage, ...};` — no `use super::*;` line obscures where the symbols come from. The engineer can confirm by reading just the top of the file that codelet-napi consumes (not owns) every persistence type and function.
  #   4. Relocated test execution: an engineer running `cargo test -p codelet-core --lib persistence::tests` sees 48 tests pass with names like `test_resume_session_after_closing_terminal`, `test_blob_reference_format`, `test_tool_result_blob_storage_and_rehydration`, `test_blob_storage_dedup`, etc. — every test that previously lived in codelet-napi now runs under codelet-core. Running `cargo test -p codelet-core --lib persistence::lazy_init_tests` shows 9 tests pass including `test_lazy_get_history_only_inits_history_store`, `test_lazy_store_message_inits_message_and_blob_and_session_store`, `test_lazy_create_session_only_inits_session_store`, `test_lazy_session_resume_loads_only_that_session`, `test_lazy_cross_session_search_loads_on_demand`, `test_lazy_shell_history_cross_session`, `test_lazy_search_command_cross_session`, `test_lazy_forked_message_accessible`, `test_lazy_append_and_immediate_read`.
  #   5. NAPI-bridge integration tests still green: an engineer running `cargo test -p codelet-napi --test session_persistence_test` sees the 23 NAPI-bridge tests pass, and `cargo test -p codelet-napi --test subordinate_session_persistence_test` shows 4 tests pass — these exercise the `Napi*` wire-struct round-trip (e.g. `NapiSessionManifest::from(SessionManifest)`) which is the NAPI-bridge's only remaining job. None of those tests are moved out of codelet-napi.
  #   6. Forbidden-arrow regression intact: the existing `rust/rpc-embedded/tests/rpc_006_source_shape.rs` test continues to pass — proving the `rpc → napi` forbidden arrow is not re-introduced by this card. A downstream consumer (codelet-rpc-embedded, which depends on codelet-core but never on codelet-napi) writes `use codelet_core::persistence::{create_session, load_session, append_message_with_metadata, fork_session, store_blob, get_blob, blob_exists, process_envelope_for_blob_storage, rehydrate_envelope_blobs, history};` and links cleanly — and ALSO writes `use codelet_core::persistence::ensure_directories;` cleanly (proving the ensure_directories shim's deletion from codelet-napi does not regress codelet-core's surface).
  #   7. Setup helper migration: the engineer reads the relocated `rust/core/src/persistence/tests.rs` and finds the new setup helper at the top: ```fn setup_test_env() -> (std::sync::MutexGuard<'static, ()>, tempfile::TempDir) { let guard = TEST_MUTEX.lock().unwrap(); let temp_dir = tempfile::tempdir().expect("Failed to create temp directory"); codelet_common::set_data_directory(temp_dir.path().to_path_buf()).expect("Failed to set data directory"); codelet_core::persistence::reset_stores_for_tests(); (guard, temp_dir) }``` — confirming the relocated tests no longer reach into NAPI-only credentials / knowledge-graph reset code, since those concerns do not belong to codelet-core.
  #
  # QUESTIONS (ANSWERED):
  #   Q: The original NAPI tests (rust/napi/src/persistence/tests.rs and lazy_init_tests.rs) currently call into the NAPI-shim `crate::persistence::set_data_directory` which resets credentials + graph stores. When we relocate them to codelet-core, those tests no longer reset credentials / graph. Is it acceptable that the relocated tests stop exercising the credentials/graph reset path? (Recommended answer: YES — credentials and graph resets are NAPI-only concerns; the test_support.rs helper in codelet-napi already covers the credentials/graph reset path indirectly, and the relocated tests only need persistence-store isolation.)
  #   A: Option (a). Inline the credentials::reset_credential_store() + graph::reset_graph_db() calls into the body of `persistence_set_data_directory` inside napi_bindings.rs immediately after the codelet_common::set_data_directory and codelet_core::persistence::reset_stores_for_tests calls. This keeps mod.rs at ≤ 20 lines and keeps the NAPI-only reset logic exactly where it executes (the NAPI entry point). rust/napi/src/test_support.rs::setup_test_data_directory continues to call `crate::persistence::persistence_set_data_directory(...)` if it needs the credentials/graph reset — or switches to the test-only path that calls codelet_common::set_data_directory + reset_stores_for_tests + reset_credential_store + reset_graph_db inline.
  #
  #   Q: Should the credentials + knowledge-graph reset that currently lives inside `rust/napi/src/persistence/mod.rs::set_data_directory` move (a) inline into the `#[napi] pub fn persistence_set_data_directory` body in napi_bindings.rs, or (b) into a new top-level helper in `rust/napi/src/lib.rs` or `rust/napi/src/test_support.rs` so the #[napi] entry point can stay short? (Recommended: (a) inline into persistence_set_data_directory — it is the only non-test caller, and the inlined body is 5 lines.)
  #   A: Option (a). Inline the credentials::reset_credential_store() + graph::reset_graph_db() calls into the body of `persistence_set_data_directory` inside napi_bindings.rs immediately after the codelet_common::set_data_directory + codelet_core::persistence::reset_stores_for_tests calls. This keeps mod.rs at ≤ 20 lines and keeps the NAPI-only reset logic exactly where it executes (the NAPI entry point).
  #
  # ========================================
  Background: User Story
    As a fspec backend engineer maintaining the NAPI persistence surface
    I want to reduce rust/napi/src/persistence/ to a pure NAPI adapter (mod.rs + napi_bindings.rs only) by routing every persistence call inside napi_bindings.rs explicitly through codelet_core::persistence and relocating the persistence test suites into codelet-core
    So that Phase 1 of RPC-030 is observably complete: codelet-napi no longer owns any persistence logic or test ownership, the dependency direction (napi → core) is documented at every call site, the TS-facing index.d.ts surface remains byte-identical, and the path is cleared for Phase 2 (rpc-types widening) without any latent napi-only persistence assumptions

  Scenario: rust/napi/src/persistence/ contains exactly mod.rs and napi_bindings.rs after the card
    Given RPC-031 through RPC-034 have lifted every persistence type and singleton into codelet-core::persistence
    And the relocation work for tests.rs and lazy_init_tests.rs has completed
    When std::fs::read_dir lists the entries of rust/napi/src/persistence/
    Then the result contains exactly two filenames, "mod.rs" and "napi_bindings.rs", and nothing else
    And rust/napi/src/persistence/mod.rs is at most 20 lines long
    And rust/napi/src/persistence/mod.rs contains no pub fn declarations
    And rust/napi/src/persistence/mod.rs contains exactly one pub use line: `pub use codelet_core::persistence::*;`

  Scenario: rust/napi/index.d.ts is byte-identical before and after the card
    Given the SHA-256 hash H1 of rust/napi/index.d.ts captured before RPC-035 is committed as a fixture
    When `cargo build -p codelet-napi --release` is run on the post-card source tree
    And napi-rs regenerates rust/napi/index.d.ts from the #[napi] attributes
    Then `sha256sum rust/napi/index.d.ts` returns the same hash H1
    And no `persistenceXxx` declaration is added, removed, renamed, or reordered relative to the pre-card snapshot
    And no Napi* interface field is reordered relative to the pre-card snapshot

  Scenario: Every #[napi] persistence_* function sources its callees through an explicit codelet_core::persistence import
    Given the engineer opens rust/napi/src/persistence/napi_bindings.rs
    When the engineer reads the import block at the top of the file
    Then a single `use codelet_core::persistence::{ create_session, create_session_with_provider, load_session, resume_last_session, list_sessions, delete_session, rename_session, fork_session, merge_messages, cherry_pick, append_message, append_message_with_metadata, get_message, get_session_messages, get_session_messages_full, update_session_tokens, set_session_tokens, set_compaction_state, clear_compaction_state, cleanup_orphaned_messages, store_blob, get_blob, blob_exists, process_envelope_for_blob_storage, rehydrate_envelope_blobs, MessageEnvelope, MessagePayload, UserContent, AssistantContent, SessionManifest, ForkPoint, MergeRecord, CompactionState, TokenUsage, StoredMessage, HistoryEntry, history };` is present
    And the file contains no `use super::*;` line anywhere
    And each #[napi] persistence_* function body references its callees by their unqualified name (e.g. `load_session(uuid)`) imported from codelet_core::persistence (not from `super::`)

  Scenario: The relocated codelet-core persistence::tests suite runs all 48 tests
    Given rust/core/src/persistence/tests.rs has been added with the relocated 48 tests
    And rust/core/src/persistence/mod.rs declares `#[cfg(test)] mod tests;`
    When `cargo test -p codelet-core --lib persistence::tests` is run
    Then 48 tests pass, including test_resume_session_after_closing_terminal, test_blob_reference_format, test_tool_result_blob_storage_and_rehydration, and test_blob_storage_dedup
    And `cargo test -p codelet-napi --lib persistence::tests` reports zero tests because rust/napi/src/persistence/tests.rs no longer exists

  Scenario: The relocated codelet-core persistence::lazy_init_tests suite runs all 9 BUG-122 lazy-init invariants
    Given rust/core/src/persistence/lazy_init_tests.rs has been added with the relocated 9 tests
    And rust/core/src/persistence/mod.rs declares `#[cfg(test)] mod lazy_init_tests;`
    When `cargo test -p codelet-core --lib persistence::lazy_init_tests` is run
    Then 9 tests pass, including test_lazy_get_history_only_inits_history_store, test_lazy_store_message_inits_message_and_blob_and_session_store, test_lazy_create_session_only_inits_session_store, test_lazy_session_resume_loads_only_that_session, test_lazy_cross_session_search_loads_on_demand, test_lazy_shell_history_cross_session, test_lazy_search_command_cross_session, test_lazy_forked_message_accessible, and test_lazy_append_and_immediate_read

  Scenario: NAPI-bridge integration tests still pass after the relocation
    Given the NAPI-bridge integration tests session_persistence_test.rs and subordinate_session_persistence_test.rs stay in rust/napi/tests/
    And rust/napi/src/test_support.rs::setup_test_env is rewritten to call codelet_common::set_data_directory + codelet_core::persistence::reset_stores_for_tests + crate::credentials::reset_credential_store + crate::graph::reset_graph_db inline
    When `cargo test -p codelet-napi --test session_persistence_test` is run
    And `cargo test -p codelet-napi --test subordinate_session_persistence_test` is run
    Then 23 tests pass in session_persistence_test
    And 4 tests pass in subordinate_session_persistence_test
    And those tests continue to exercise the Napi* wire-struct round-trip (e.g. NapiSessionManifest::from(SessionManifest))

  Scenario: codelet-rpc-embedded continues to consume persistence without re-introducing the forbidden rpc to napi arrow
    Given rust/rpc-embedded depends on codelet-core but is forbidden from depending on codelet-napi by rpc_006_source_shape.rs
    When a downstream consumer in rust/rpc-embedded writes `use codelet_core::persistence::{create_session, load_session, append_message_with_metadata, fork_session, store_blob, get_blob, blob_exists, process_envelope_for_blob_storage, rehydrate_envelope_blobs, ensure_directories, history};`
    Then the build succeeds with no transitive dependency on codelet-napi
    And the dependency-rule test rpc_006_source_shape.rs continues to pass

  Scenario: The relocated setup_test_env helper uses codelet-core primitives only
    Given the engineer opens rust/core/src/persistence/tests.rs
    When the engineer reads the body of setup_test_env at the top of the file
    Then the body is `let guard = TEST_MUTEX.lock().unwrap(); let temp_dir = tempfile::tempdir().expect("Failed to create temp directory"); codelet_common::set_data_directory(temp_dir.path().to_path_buf()).expect("Failed to set data directory"); codelet_core::persistence::reset_stores_for_tests(); (guard, temp_dir)`
    And there is no reference to crate::credentials::reset_credential_store or crate::graph::reset_graph_db in the relocated setup helper because those are NAPI-only concerns

  Scenario: Both codelet-napi feature builds succeed after the relocation
    Given rust/napi/src/persistence/mod.rs no longer declares mod tests or mod lazy_init_tests and contains no pub fn declarations
    And napi_bindings.rs imports its callees via `use codelet_core::persistence::{...};`
    When `cargo build -p codelet-napi --features napi` is run
    And `cargo build -p codelet-napi --features noop` is run
    Then both builds succeed without warnings about unresolved imports
    And the napi build emits the unchanged rust/napi/index.d.ts with SHA-256 hash equal to the pre-card snapshot
