@done
@rpc
@infrastructure
@session-management
@codelet
@RPC-041
Feature: Replace GLOBAL_CHUNK_CALLBACK with tokio::broadcast sender; rewire NAPI ThreadsafeFunction as a subscriber
  """
  Architecture: The four GLOBAL_CHUNK_CALLBACK call sites in codelet/napi/src/session_manager.rs are categorized by their fan-out source: (A) chunks emitted from inside a BackgroundSession (existing supervisor_broadcast + chunks_tx.send via handle_output — agent_loop, set_status etc.) — already broadcast as part of the session lifecycle, no extra wiring needed; (B) chunks emitted from napi-private free functions that already know the session_id (emit_block_notification_to_tui at line 4432, spawn_footer_poller at line 4152) — these route through SessionManager::instance().chunks_tx().send(...) directly because they have the manager singleton in scope; (C) chunks emitted from inside SessionManager methods (the previously-hook-routed IsolationStateChange at create_session_with_id and create_isolated_session_with_id) — these become direct `self.chunks_tx.send(...)` calls because the manager owns the sender natively, eliminating the hook indirection entirely; (D) registration sanity-check gates (FspecHandler at 3005, command_emitter at 3285) — these use the new is_global_chunk_callback_registered() helper that consults CHUNK_FANOUT_TSFN
  Architecture: Receiver-side fan-out task lifetime — `tokio::spawn(async move { while let Ok((sid, chunk)) = rx.recv().await { ... } })` runs for the lifetime of the napi node addon. The `Drop`-on-broadcast-Closed branch is unreachable in practice (the manager-owned sender lives in the static singleton), so the task effectively never exits — exactly mirrors the lifetime of the old GLOBAL_CHUNK_CALLBACK static. `RecvError::Lagged(n)` from a sluggish JS callback is logged via `tracing::warn!` (matching the existing supervisor_broadcast lag treatment in BackgroundSession) and the loop continues — slow consumers don't block other subscribers
  Architecture: Following the RPC-039/040 review-findings pattern, RPC-041 EXTENDS the existing test suites at codelet/sessions/tests/background_session_shape.rs and codelet/sessions/tests/session_manager_shape.rs rather than creating new test files. Each new Gherkin scenario maps 1:1 to a `#[test] fn scenario_*()` block with `@step` comments matching every Gherkin step verbatim. Inverted assertions (REQUIRING absence of GLOBAL_CHUNK_CALLBACK in napi) replace the prior assertions that REQUIRED it to remain. Coverage updates use accurate line ranges to avoid the line-drift bug class found in the RPC-039 review
  Architecture: status_changes_tx is wired but no JS-visible subscriber yet — the JS side currently observes status changes via the `SessionStateChange` StreamChunk variant (emitted by set_status → handle_output → chunks_tx). The status_changes_tx broadcast added in this card is consumed by the future Rust fspec-tui (RPC-045+) and by any internal Rust subscriber that wants a typed `(SessionId, SessionStatus)` stream without parsing a StreamChunk. Adding the sender now (with no JS-side subscriber) is intentional — it keeps the trait surface stable and consumer-ready when the Rust frontend lands
  """

  # ========================================
  # EXAMPLE MAPPING CONTEXT
  # ========================================
  #
  # BUSINESS RULES:
  #   1. The OnceCell<GlobalChunkCallback> static at codelet/napi/src/session_manager.rs line 73 (`static GLOBAL_CHUNK_CALLBACK: OnceCell<GlobalChunkCallback> = OnceCell::new();`) is deleted; the `GlobalChunkCallback` struct + `new()` + `call()` impl at lines 75-98 is deleted; the `unsafe impl Send for GlobalChunkCallback {}` / `unsafe impl Sync for GlobalChunkCallback {}` block at lines 100-102 is deleted. After RPC-041 nothing in codelet/napi/src/session_manager.rs grep-matches the literal token `GLOBAL_CHUNK_CALLBACK` and nothing matches the regex `unsafe\s+impl\s+(Send|Sync)\s+for\s+GlobalChunkCallback`
  #   2. BackgroundSession (in codelet/sessions/src/background_session.rs) replaces its current `chunks_tx: Option<broadcast::Sender<(codelet_rpc_types::SessionId, StreamChunk)>>` field with a mandatory `chunks_tx: broadcast::Sender<(codelet_rpc_types::SessionId, StreamChunk)>` (no Option wrapper) and gains a new `status_changes_tx: broadcast::Sender<(codelet_rpc_types::SessionId, codelet_rpc_types::SessionStatus)>` field. Both are populated by SessionManager via constructor injection — `BackgroundSession::new` grows two extra parameters `chunks_tx` and `status_changes_tx` (placed after the existing `lifecycle_hooks` parameter so positional matching of pre-existing callers fails loudly at compile time)
  #   3. `BackgroundSession::handle_output` is rewritten so the previously-conditional `if let Some(tx) = &self.chunks_tx { let _ = tx.send(...) }` becomes an unconditional `let _ = self.chunks_tx.send((codelet_rpc_types::SessionId::from(self.id.to_string()), chunk.clone()));` immediately after the existing `supervisor_broadcast.send(chunk.clone())` call. The output_buffer push and supervisor_broadcast emission are both preserved — only the third sink (the new manager-owned chunks_tx) becomes mandatory
  #   4. `BackgroundSession::set_status` is widened so that whenever `old_status != status as u8` (i.e. the status actually changes) it additionally calls `let _ = self.status_changes_tx.send((codelet_rpc_types::SessionId::from(self.id.to_string()), status));`. The existing side effects are preserved verbatim: the `self.status.swap(status as u8, Ordering::AcqRel)` atomic update, the `self.handle_output(StreamChunk::session_state_change(state))` emit, and the `codelet_tools::broadcast_metadata_update()` call all still happen in the same order
  #   5. Both `SessionManager::create_session_with_id` and `SessionManager::create_isolated_session_with_id` (in codelet/sessions/src/session_manager.rs) pass `self.chunks_tx.clone()` and `self.status_changes_tx.clone()` to `BackgroundSession::new(...)` as the new trailing arguments. The accessor methods `SessionManager::chunks_tx() -> &broadcast::Sender<...>`, `logs_tx()`, and `status_changes_tx()` continue to expose the manager-owned senders unchanged — they remain the source of truth that the napi adapter and the fspec-tui frontend subscribe to
  #   6. The napi free function `session_set_global_chunk_callback` (still public, still `#[napi]`-decorated, still accepts `ThreadsafeFunction<GlobalChunkCallbackArgs>`, still returns `Result<()>` — TS surface is byte-stable) is rewritten to: (a) store the supplied `ThreadsafeFunction` inside a new `static CHUNK_FANOUT_TSFN: OnceCell<parking_lot::Mutex<Option<ThreadsafeFunction<GlobalChunkCallbackArgs>>>> = OnceCell::new();` (replaces the previous OnceCell<GlobalChunkCallback>) — re-registration replaces, not duplicates; (b) call `SessionManager::instance().chunks_tx().subscribe()` ONCE and `tokio::spawn` a long-running task that loops on `rx.recv()` and forwards each `(SessionId, StreamChunk)` into the TSFN as `GlobalChunkCallbackArgs { session_id: session_id.to_string(), chunk }` via `ThreadsafeFunctionCallMode::NonBlocking`; `RecvError::Lagged` is logged and the loop continues, `RecvError::Closed` terminates the task; (c) continue to call `init_block_notification_callbacks()`, `install_napi_session_manager_hooks()`, `init_bridge_metadata_providers()`, and `init_bridge_session_and_terminal_creators()` as before — these are unrelated wiring steps
  #   7. Every napi-side call site that previously reached for `GLOBAL_CHUNK_CALLBACK.get()` is rewritten: (a) `emit_block_notification_to_tui` (around line 4432) builds `StreamChunk::user_notification(...)` and emits via `let _ = SessionManager::instance().chunks_tx().send((SessionId::from(session_id_str), chunk));` — the napi-side fan-out task delivers it to the TS callback exactly as before; (b) `spawn_footer_poller`'s emit site (around line 4152) routes the `FooterStateUpdate` through `SessionManager::instance().chunks_tx().send(...)` with the same conditional `first_run || cwd_changed || ...` gate; (c) the `FspecHandler` registration check (around line 3005) and the `command_emitter` registration check (around line 3285) are rewritten to call a new private helper `is_global_chunk_callback_registered() -> bool` that consults `CHUNK_FANOUT_TSFN.get().and_then(|m| m.lock().map(|g| g.is_some()).ok()).unwrap_or(false)` — the user-visible error string `Global chunk callback not registered - cannot execute fspec command` is preserved verbatim for back-compat
  #   8. The `emit_isolation_state_change` method on the `SessionManagerHooks` trait (defined in codelet/sessions/src/session_manager.rs) is removed entirely (both from the trait definition, from `NoopSessionManagerHooks`, and from the napi-side `NapiSessionManagerHooks` impl at codelet/napi/src/session_manager.rs:6683-6693). Its two call sites inside SessionManager (`create_session_with_id` line ~641, `create_isolated_session_with_id` line ~876) are rewritten in-place to `let _ = self.chunks_tx.send((codelet_rpc_types::SessionId::from(id.to_string()), codelet_rpc_types::StreamChunk::isolation_state_change(is_isolated, worktree_path_opt)));`. With the hook gone, the napi-side `NapiSessionManagerHooks` impl loses one method but every other hook (spawn_agent_loop, spawn_scheduler, ensure_scheduler_running_for_loop, spawn_footer_poller, stop_footer_poller, cleanup_session_loops) stays untouched
  #   9. Cross-frontend fan-out invariant — multiple subscribers (the napi adapter at startup, future fspec-tui at startup, and any test code that calls `manager.chunks_tx().subscribe()`) all receive every chunk emitted by every BackgroundSession in arrival order. `tokio::sync::broadcast` guarantees per-sender ordering and the only sender is `BackgroundSession::handle_output` for any given chunk, so the order TS sees is identical to the order Rust emits
  #   10. Build invariants ALL hold after the change: `cargo build -p codelet-sessions` succeeds; `cargo build -p codelet-napi` succeeds; `cargo build -p codelet-napi --release` regenerates codelet/napi/index.d.ts with NO removed/renamed TypeScript symbols and no field reorders (sessionSetGlobalChunkCallback preserves its exact signature, GlobalChunkCallbackArgs preserves session_id + chunk fields in that order); `cargo metadata -p codelet-sessions --format-version 1` continues to report zero `codelet-napi` package entries (skeleton_invariants.rs::scenario_codelet_sessions_has_no_transitive_dependency_on_codelet_napi keeps passing); `cargo clippy -p codelet-sessions --all-targets -- -D warnings` passes (workspace-lints inherited)
  #   11. Existing dependency-rule tests in codelet/sessions/tests/background_session_shape.rs and codelet/sessions/tests/session_manager_shape.rs are updated to reflect the new invariants: the assertions that previously REQUIRED `static GLOBAL_CHUNK_CALLBACK` to still live in codelet/napi/src/session_manager.rs (background_session_shape.rs lines 460-469) are INVERTED — the test now asserts the literal token `GLOBAL_CHUNK_CALLBACK` does NOT appear anywhere in codelet/napi/src/session_manager.rs. The session_manager_shape.rs scenario at lines 1001-1009 that requires `emit_isolation_state_change` to delegate to `GLOBAL_CHUNK_CALLBACK` is removed (the hook itself is gone). New RPC-041 scenarios added in both files cover: handle_output uses mandatory chunks_tx, set_status emits on status_changes_tx, BackgroundSession::new signature widening, session_set_global_chunk_callback subscribes via SessionManager::instance().chunks_tx().subscribe(), the napi-side helper is_global_chunk_callback_registered() gates the FspecHandler + command_emitter paths
  #   12. The legacy structural test file `codelet/napi/tests/global_chunk_callback_napi_test.rs` is updated to match the new contract. Specifically: `test_global_callback_returns_void` (line 64) and `test_global_callback_registration_exports` (line 34) continue to require `sessionSetGlobalChunkCallback` is exported and returns `Result<()>` — these stay green. `test_handle_output_uses_global_callback` (line 90), `test_global_callback_receives_session_id` (line 104), `test_global_callback_receives_chunk` (line 117), `test_global_callback_is_static_singleton` (line 144), `test_each_session_passes_own_id_to_callback` (line 158) — these all assert `GLOBAL_CHUNK_CALLBACK.get()` / `GlobalChunkCallback` artefacts that are removed by this card; they are INVERTED to assert ABSENCE of those tokens (the chunks now flow via `SessionManager::instance().chunks_tx().send(...)` and the subscriber task). Tests in `no_attachment_state_in_rust` and `no_per_session_napi_attachment_functions` modules stay green unchanged
  #
  # EXAMPLES:
  #   1. Developer greps `codelet/napi/src/session_manager.rs` for the regex `GLOBAL_CHUNK_CALLBACK|struct GlobalChunkCallback|unsafe impl (Send|Sync) for GlobalChunkCallback` — every match returns ZERO lines. The static, the struct, and the unsafe impls are all gone.
  #   2. Developer inspects `BackgroundSession::handle_output` in codelet/sessions/src/background_session.rs and sees it ends with an unconditional `let _ = self.chunks_tx.send((codelet_rpc_types::SessionId::from(self.id.to_string()), chunk.clone()));` — no `if let Some(tx)` wrapper, no `Option<broadcast::Sender>` field on the struct
  #   3. Developer inspects `BackgroundSession::set_status` and sees that, immediately after the `self.status.swap(...)` atomic update and the `if old_status != status as u8` guard, the method now emits the status change on `self.status_changes_tx` via `let _ = self.status_changes_tx.send((codelet_rpc_types::SessionId::from(self.id.to_string()), status));` BEFORE the `self.handle_output(StreamChunk::session_state_change(state))` and `codelet_tools::broadcast_metadata_update()` calls that were already there
  #   4. Developer inspects `BackgroundSession::new` and sees its signature now ends with two extra trailing parameters: `chunks_tx: tokio::sync::broadcast::Sender<(codelet_rpc_types::SessionId, codelet_rpc_types::StreamChunk)>, status_changes_tx: tokio::sync::broadcast::Sender<(codelet_rpc_types::SessionId, codelet_rpc_types::SessionStatus)>`. The struct fields `chunks_tx` and `status_changes_tx` are non-Option, non-pub. The previous `None` initializer for the field is replaced by the constructor argument
  #   5. Developer inspects `SessionManager::create_session_with_id` and `SessionManager::create_isolated_session_with_id` in codelet/sessions/src/session_manager.rs — both call sites for `BackgroundSession::new(...)` now pass `self.chunks_tx.clone()` and `self.status_changes_tx.clone()` as the last two arguments. The `self.hooks().emit_isolation_state_change(...)` calls at lines ~641 and ~876 are gone — both call sites now emit IsolationStateChange via `let _ = self.chunks_tx.send((codelet_rpc_types::SessionId::from(id.to_string()), codelet_rpc_types::StreamChunk::isolation_state_change(...)));`
  #   6. Developer inspects the `SessionManagerHooks` trait declaration in codelet/sessions/src/session_manager.rs and observes there is NO method `emit_isolation_state_change` anymore. The trait now has six methods: `spawn_agent_loop`, `spawn_scheduler`, `ensure_scheduler_running_for_loop`, `spawn_footer_poller`, `stop_footer_poller`, `cleanup_session_loops`. The `NoopSessionManagerHooks` and `NapiSessionManagerHooks` (in codelet/napi/src/session_manager.rs) impls are both updated to match the new six-method trait surface
  #   7. Developer inspects the rewritten `session_set_global_chunk_callback` napi free function in codelet/napi/src/session_manager.rs. The body: (1) stores the supplied `ThreadsafeFunction<GlobalChunkCallbackArgs>` in `CHUNK_FANOUT_TSFN: OnceCell<parking_lot::Mutex<Option<ThreadsafeFunction<...>>>>`, returning `Error::from_reason("Global chunk callback already set...")` on re-registration; (2) calls `let mut rx = SessionManager::instance().chunks_tx().subscribe();` and `tokio::spawn(async move { while let Ok((sid, chunk)) = rx.recv().await { ... tsfn.call(Ok(GlobalChunkCallbackArgs { session_id: sid.to_string(), chunk }), ThreadsafeFunctionCallMode::NonBlocking); } });`; (3) keeps the existing `init_block_notification_callbacks(); install_napi_session_manager_hooks(); init_bridge_metadata_providers(); init_bridge_session_and_terminal_creators();` calls in the same order
  #   8. Developer inspects `emit_block_notification_to_tui` (around line 4432) in codelet/napi/src/session_manager.rs and sees the body has been rewritten from `if let Some(global_cb) = GLOBAL_CHUNK_CALLBACK.get() { ... global_cb.call(session_id_str, chunk); }` to `let chunk = StreamChunk::user_notification(format!("AI was blocked from {} - {}", action, reason), NotificationSeverity::Warning); let _ = SessionManager::instance().chunks_tx().send((codelet_rpc_types::SessionId::from(session_id_str), chunk));`. Similarly `spawn_footer_poller`'s emit site at line 4152 routes via `SessionManager::instance().chunks_tx().send(...)` with the same `first_run || cwd_changed || ...` gate preserved
  #   9. Developer inspects the FspecHandler closure (around line 3001) and the bridge command_emitter closure (around line 3283) in codelet/napi/src/session_manager.rs — the `if GLOBAL_CHUNK_CALLBACK.get().is_none()` early-return gate is rewritten to `if !is_global_chunk_callback_registered()` calling a new private helper at the bottom of the file. The helper reads `CHUNK_FANOUT_TSFN.get().and_then(|m| m.lock().ok()).map(|g| g.is_some()).unwrap_or(false)`. The user-facing error string `Global chunk callback not registered - cannot execute fspec command` is preserved verbatim
  #   10. Developer runs `cargo build -p codelet-sessions` and `cargo build -p codelet-napi` — both succeed. Then runs `cargo build -p codelet-napi --release` to regenerate codelet/napi/index.d.ts and `git diff codelet/napi/index.d.ts` shows ZERO removed/renamed TypeScript exports; specifically `sessionSetGlobalChunkCallback(callback: ...): void;` and the `GlobalChunkCallbackArgs { session_id: string; chunk: StreamChunk }` shape preserve their pre-existing signatures byte-for-byte
  #   11. Developer runs `cargo test -p codelet-sessions --tests` — every test passes. Specifically: `skeleton_invariants::scenario_codelet_sessions_has_no_transitive_dependency_on_codelet_napi` still green (zero codelet-napi entries in transitive graph); `background_session_shape::scenario_handle_output_uses_the_new_chunks_tx_broadcast_and_no_longer_touches_global_chunk_callback` is rewritten to require the mandatory chunks_tx send AND inverted to assert the napi shell has NO `GLOBAL_CHUNK_CALLBACK` token; new scenarios `scenario_handle_output_emits_unconditionally_on_chunks_tx` and `scenario_set_status_emits_on_status_changes_tx` and `scenario_session_manager_passes_broadcast_senders_to_background_session` all green; existing session_manager_shape.rs tests updated to reflect the removed hook
  #   12. Developer writes a multi-subscriber smoke test in codelet/sessions/tests/ that constructs a SessionManager, calls `manager.chunks_tx().subscribe()` twice to obtain two receivers, fabricates a BackgroundSession with the manager's chunks_tx clone, calls `session.handle_output(StreamChunk::user_input("hello"))`, and observes that BOTH receivers see the same `(SessionId, StreamChunk)` tuple in arrival order. This proves the fan-out: napi adapter + fspec-tui (or any other downstream subscriber) get every chunk
  #
  # ========================================
  Background: User Story
    As a Rust developer porting the Codelet session manager out of codelet-napi
    I want to delete the napi-side GLOBAL_CHUNK_CALLBACK static and rewire BackgroundSession::handle_output to broadcast through the SessionManager-owned chunks_tx (with a thin napi-side subscriber fanning into the JS ThreadsafeFunction), while also having set_status broadcast on status_changes_tx
    So that the agent loop's stream-chunk fan-out has a single push-based source of truth that both the napi adapter and the eventual Rust fspec-tui frontend can subscribe to as peers, with zero unsafe Send/Sync impls and no global OnceCell

  Scenario: The GLOBAL_CHUNK_CALLBACK static, GlobalChunkCallback struct, and its unsafe Send/Sync impls are removed
    Given the napi-side codelet/napi/src/session_manager.rs file previously declared `static GLOBAL_CHUNK_CALLBACK: OnceCell<GlobalChunkCallback>`, a `struct GlobalChunkCallback { callback: ThreadsafeFunction<GlobalChunkCallbackArgs> }`, and `unsafe impl Send for GlobalChunkCallback {}` / `unsafe impl Sync for GlobalChunkCallback {}`
    When I grep codelet/napi/src/session_manager.rs for the regex `GLOBAL_CHUNK_CALLBACK|struct GlobalChunkCallback|unsafe impl (Send|Sync) for GlobalChunkCallback`
    Then I find zero matches in the file
    And the `GlobalChunkCallbackArgs` `#[napi(object)]` struct still exists because it is the TS-facing wire shape

  Scenario: BackgroundSession::handle_output broadcasts unconditionally on the mandatory chunks_tx field
    Given the BackgroundSession code lives at codelet/sessions/src/background_session.rs
    And `BackgroundSession::handle_output(&self, chunk: StreamChunk)` is defined there
    When I inspect the body of handle_output in the moved file
    Then the body still pushes the chunk into output_buffer
    And the body still calls `supervisor_broadcast.send(chunk.clone())`
    And the body unconditionally calls `self.chunks_tx.send((codelet_rpc_types::SessionId::from(self.id.to_string()), chunk.clone()))` without an `if let Some(tx)` wrapper
    And the BackgroundSession struct declares `chunks_tx: broadcast::Sender<(codelet_rpc_types::SessionId, StreamChunk)>` as a non-Option, non-pub field

  Scenario: BackgroundSession::set_status emits on the new status_changes_tx broadcast when the status actually changes
    Given the BackgroundSession code lives at codelet/sessions/src/background_session.rs
    And `BackgroundSession::set_status(&self, status: SessionStatus)` is defined there
    When I inspect the body of set_status in the moved file
    Then the body first calls `let old_status = self.status.swap(status as u8, Ordering::AcqRel)`
    And under the `if old_status != status as u8` guard the body calls `let _ = self.status_changes_tx.send((codelet_rpc_types::SessionId::from(self.id.to_string()), status))`
    And the body still calls `self.handle_output(StreamChunk::session_state_change(state))`
    And the body still calls `codelet_tools::broadcast_metadata_update()`
    And the BackgroundSession struct declares a non-Option `status_changes_tx: broadcast::Sender<(codelet_rpc_types::SessionId, codelet_rpc_types::SessionStatus)>` field

  Scenario: BackgroundSession::new accepts chunks_tx and status_changes_tx as new trailing parameters
    Given the BackgroundSession constructor `BackgroundSession::new(...)` is the sole construction site for BackgroundSession
    When I inspect the parameter list of `BackgroundSession::new` in codelet/sessions/src/background_session.rs
    Then the signature ends with two new trailing parameters `chunks_tx: tokio::sync::broadcast::Sender<(codelet_rpc_types::SessionId, codelet_rpc_types::StreamChunk)>` and `status_changes_tx: tokio::sync::broadcast::Sender<(codelet_rpc_types::SessionId, codelet_rpc_types::SessionStatus)>`
    And the body initializes the `chunks_tx` struct field directly from the parameter (no `None` placeholder remains)
    And the body initializes the `status_changes_tx` struct field directly from the parameter
