//! `generate_tags_md` — Rust port of `src/generators/tags-md.ts`.
//!
//! Produces `TAGS.md` from a parsed `tags.json` document. The output is
//! **byte-for-byte identical** to the TypeScript `generateTagsMd` reference:
//! the TS builds a `string[]` and `join('\n')`s it, so we accumulate
//! `Vec<String>` and `join("\n")` the same way. The TS generator pushes a
//! trailing empty section (`sections.push('')`) before `join('\n')`, so the
//! result carries a single trailing newline — matching the TS
//! `writeFile(tagsMdPath, markdown)` bytes exactly.
//!
//! The generator operates directly off a `serde_json::Value` rather than a
//! strongly-typed struct so that optional sections present in the rich
//! `tags.json` tree (`usageGuidelines`, `statistics`, …) round-trip without a
//! struct change. JS truthiness / `arr && arr.length > 0` checks are mirrored
//! via [`super::foundation_md_util::truthy`] and the local `arr` helper, and
//! numeric template-literal coercion via [`super::foundation_md_util::js_str`].

use serde_json::Value;

use super::foundation_md_util::{js_str, truthy};

/// Return the array at `key` only when it is a non-empty JS array
/// (`v.key && v.key.length > 0`).
fn arr<'a>(v: &'a Value, key: &str) -> Option<&'a Vec<Value>> {
    match v.get(key).and_then(Value::as_array) {
        Some(a) if !a.is_empty() => Some(a),
        _ => None,
    }
}

/// JS truthiness of the value at `key`.
fn has(v: &Value, key: &str) -> bool {
    truthy(v.get(key))
}

/// `${v.key}` template-literal coercion (empty string when absent).
fn field(v: &Value, key: &str) -> String {
    match v.get(key) {
        Some(value) => js_str(value),
        None => String::new(),
    }
}

/// `${item}` coercion for a bare array element.
fn item_str(v: &Value) -> String {
    js_str(v)
}

/// Render `TAGS.md` from a parsed `tags.json` value.
pub fn generate_tags_md(tags: &Value) -> String {
    let mut sections: Vec<String> = vec![
        // Header with auto-generation warning.
        "<!-- THIS FILE IS AUTO-GENERATED FROM spec/tags.json -->".to_string(),
        "<!-- DO NOT EDIT THIS FILE DIRECTLY -->".to_string(),
        "<!-- Edit spec/tags.json and run: fspec generate-tags -->".to_string(),
        String::new(),
        // Main title.
        "# fspec Feature File Tag Registry".to_string(),
        String::new(),
    ];

    // Tag Categories.
    if let Some(categories) = arr(tags, "categories") {
        sections.push("## Tag Categories".to_string());
        sections.push(String::new());

        for category in categories {
            let required_text = if category
                .get("required")
                .and_then(Value::as_bool)
                .unwrap_or(false)
            {
                " (Required)"
            } else {
                ""
            };
            sections.push(format!("### {}{}", field(category, "name"), required_text));
            sections.push(String::new());
            sections.push(field(category, "description"));
            sections.push(String::new());

            // Tag table.
            if let Some(cat_tags) = arr(category, "tags") {
                sections.push("| Tag | Description |".to_string());
                sections.push("|-----|-------------|".to_string());

                for tag in cat_tags {
                    sections.push(format!(
                        "| `{}` | {} |",
                        field(tag, "name"),
                        field(tag, "description")
                    ));
                }
                sections.push(String::new());
            }

            // Category rule.
            if has(category, "rule") {
                sections.push(format!("**Rule**: {}", field(category, "rule")));
                sections.push(String::new());
            }
        }

        sections.push("---".to_string());
        sections.push(String::new());
    }

    // Tag Combination Examples.
    if let Some(examples) = arr(tags, "combinationExamples") {
        sections.push("## Tag Combination Examples".to_string());
        sections.push(String::new());

        for example in examples {
            sections.push(format!("### {}", field(example, "title")));
            sections.push(String::new());
            sections.push("```gherkin".to_string());
            sections.push(field(example, "tags"));
            sections.push("Feature: Create Feature File with Template".to_string());
            sections.push("```".to_string());
            sections.push(String::new());

            if let Some(interpretation) = arr(example, "interpretation") {
                sections.push("**Interpretation**:".to_string());
                for it in interpretation {
                    sections.push(format!("- {}", item_str(it)));
                }
                sections.push(String::new());
            }
        }

        sections.push("---".to_string());
        sections.push(String::new());
    }

    // Usage Guidelines.
    if has(tags, "usageGuidelines") {
        let guidelines = tags.get("usageGuidelines").unwrap_or(&Value::Null);
        sections.push("## Usage Guidelines".to_string());
        sections.push(String::new());

        // Required Combinations.
        if let Some(req) = guidelines.get("requiredCombinations").filter(|v| truthy(Some(*v))) {
            if has(req, "title") {
                sections.push(format!("### {}", field(req, "title")));
                sections.push(String::new());
            }
            if let Some(requirements) = arr(req, "requirements") {
                for requirement in requirements {
                    sections.push(format!("- {}", item_str(requirement)));
                }
                sections.push(String::new());
            }
            if has(req, "minimumExample") {
                sections.push("**Minimum Example**:".to_string());
                sections.push(String::new());
                sections.push("```gherkin".to_string());
                sections.push(field(req, "minimumExample"));
                sections.push("```".to_string());
                sections.push(String::new());
            }
        }

        // Recommended Combinations.
        if let Some(rec) = guidelines.get("recommendedCombinations").filter(|v| truthy(Some(*v))) {
            if has(rec, "title") {
                sections.push(format!("### {}", field(rec, "title")));
                sections.push(String::new());
            }
            if let Some(includes) = arr(rec, "includes") {
                for include in includes {
                    sections.push(format!("- {}", item_str(include)));
                }
                sections.push(String::new());
            }
            if has(rec, "recommendedExample") {
                sections.push("**Recommended Example**:".to_string());
                sections.push(String::new());
                sections.push("```gherkin".to_string());
                sections.push(field(rec, "recommendedExample"));
                sections.push("```".to_string());
                sections.push(String::new());
            }
        }

        // Ordering Convention.
        if let Some(ord) = guidelines.get("orderingConvention").filter(|v| truthy(Some(*v))) {
            if has(ord, "title") {
                sections.push(format!("### {}", field(ord, "title")));
                sections.push(String::new());
            }
            if let Some(order) = arr(ord, "order") {
                for it in order {
                    sections.push(format!("- {}", item_str(it)));
                }
                sections.push(String::new());
            }
            if has(ord, "example") {
                sections.push("**Example**:".to_string());
                sections.push(String::new());
                sections.push("```gherkin".to_string());
                sections.push(field(ord, "example"));
                sections.push("```".to_string());
                sections.push(String::new());
            }
        }

        sections.push("---".to_string());
        sections.push(String::new());
    }

    // Adding New Tags.
    if has(tags, "addingNewTags") {
        let adding = tags.get("addingNewTags").unwrap_or(&Value::Null);
        sections.push("## Adding New Tags".to_string());
        sections.push(String::new());

        // Process.
        if let Some(process) = arr(adding, "process") {
            sections.push("### Process".to_string());
            sections.push(String::new());
            for step in process {
                sections.push(format!(
                    "**{}**: {}",
                    field(step, "step"),
                    field(step, "description")
                ));
                sections.push(String::new());
            }
        }

        // Naming Conventions.
        if let Some(conventions) = arr(adding, "namingConventions") {
            sections.push("### Naming Conventions".to_string());
            sections.push(String::new());
            for convention in conventions {
                sections.push(format!("- {}", item_str(convention)));
            }
            sections.push(String::new());
        }

        // Anti-patterns.
        if has(adding, "antiPatterns") {
            let anti = adding.get("antiPatterns").unwrap_or(&Value::Null);
            sections.push("### Anti-Patterns".to_string());
            sections.push(String::new());

            if let Some(donts) = arr(anti, "dont") {
                sections.push("❌ **DON'T**:".to_string());
                for anti_pattern in donts {
                    if has(anti_pattern, "example") {
                        sections.push(format!(
                            "- {} ({})",
                            field(anti_pattern, "description"),
                            field(anti_pattern, "example")
                        ));
                    } else {
                        sections.push(format!("- {}", field(anti_pattern, "description")));
                    }
                }
                sections.push(String::new());
            }

            if let Some(dos) = arr(anti, "do") {
                sections.push("✅ **DO**:".to_string());
                for best_practice in dos {
                    if has(best_practice, "example") {
                        sections.push(format!(
                            "- {} ({})",
                            field(best_practice, "description"),
                            field(best_practice, "example")
                        ));
                    } else {
                        sections.push(format!("- {}", field(best_practice, "description")));
                    }
                }
                sections.push(String::new());
            }
        }

        sections.push("---".to_string());
        sections.push(String::new());
    }

    // Tag-Based Queries.
    if let Some(queries) = tags.get("queries") {
        if let Some(examples) = arr(queries, "examples") {
            if has(queries, "title") {
                sections.push(format!("## {}", field(queries, "title")));
            } else {
                sections.push("## Tag-Based Queries".to_string());
            }
            sections.push(String::new());

            for query in examples {
                sections.push(format!("**{}**:", field(query, "description")));
                sections.push(String::new());
                sections.push("```bash".to_string());
                sections.push(field(query, "command"));
                sections.push("```".to_string());
                sections.push(String::new());
            }

            sections.push("---".to_string());
            sections.push(String::new());
        }
    }

    // Tag Statistics.
    if has(tags, "statistics") {
        let stats = tags.get("statistics").unwrap_or(&Value::Null);
        sections.push("## Tag Statistics".to_string());
        sections.push(String::new());

        // Phase Stats.
        if let Some(phase_stats) = arr(stats, "phaseStats") {
            sections.push("### By Phase".to_string());
            sections.push(String::new());
            sections.push("| Phase | Total Features | Complete | In Progress | Planned |".to_string());
            sections.push("|-------|----------------|----------|-------------|---------|".to_string());

            for stat in phase_stats {
                sections.push(format!(
                    "| {} | {} | {} | {} | {} |",
                    field(stat, "phase"),
                    field(stat, "total"),
                    field(stat, "complete"),
                    field(stat, "inProgress"),
                    field(stat, "planned")
                ));
            }
            sections.push(String::new());
        }

        // Component Stats.
        if let Some(component_stats) = arr(stats, "componentStats") {
            sections.push("### By Component".to_string());
            sections.push(String::new());
            sections.push("| Component | Feature Count | Percentage |".to_string());
            sections.push("|-----------|---------------|------------|".to_string());

            for stat in component_stats {
                sections.push(format!(
                    "| {} | {} | {} |",
                    field(stat, "component"),
                    field(stat, "count"),
                    field(stat, "percentage")
                ));
            }
            sections.push(String::new());
        }

        // Feature Group Stats.
        if let Some(group_stats) = arr(stats, "featureGroupStats") {
            sections.push("### By Feature Group".to_string());
            sections.push(String::new());
            sections.push("| Feature Group | Feature Count | Percentage |".to_string());
            sections.push("|---------------|---------------|------------|".to_string());

            for stat in group_stats {
                sections.push(format!(
                    "| {} | {} | {} |",
                    field(stat, "featureGroup"),
                    field(stat, "count"),
                    field(stat, "percentage")
                ));
            }
            sections.push(String::new());
        }

        // Last Updated.
        if has(stats, "lastUpdated") {
            sections.push(format!("_Last updated: {}_", field(stats, "lastUpdated")));
            sections.push(String::new());
        }

        // Update Command.
        if has(stats, "updateCommand") {
            sections.push(format!("**Update Command**: `{}`", field(stats, "updateCommand")));
            sections.push(String::new());
        }

        sections.push("---".to_string());
        sections.push(String::new());
    }

    // Validation.
    if has(tags, "validation") {
        let validation = tags.get("validation").unwrap_or(&Value::Null);
        sections.push("## Validation".to_string());
        sections.push(String::new());

        // Rules.
        if let Some(rules) = arr(validation, "rules") {
            sections.push("### Rules".to_string());
            sections.push(String::new());
            for rule in rules {
                sections.push(format!(
                    "- **{}**: {}",
                    field(rule, "rule"),
                    field(rule, "description")
                ));
            }
            sections.push(String::new());
        }

        // Commands.
        if let Some(commands) = arr(validation, "commands") {
            sections.push("### Commands".to_string());
            sections.push(String::new());
            for cmd in commands {
                sections.push(format!("**{}**:", field(cmd, "description")));
                sections.push(String::new());
                sections.push("```bash".to_string());
                sections.push(field(cmd, "command"));
                sections.push("```".to_string());
                sections.push(String::new());
            }
        }

        sections.push("---".to_string());
        sections.push(String::new());
    }

    // References.
    if let Some(references) = arr(tags, "references") {
        sections.push("## References".to_string());
        sections.push(String::new());
        for reference in references {
            sections.push(format!(
                "- [{}]({})",
                field(reference, "title"),
                field(reference, "url")
            ));
        }
        sections.push(String::new());
    }

    sections.join("\n")
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
    use super::*;
    use serde_json::json;

    #[test]
    fn renders_header_and_title() {
        let md = generate_tags_md(&json!({}));
        assert!(md.starts_with("<!-- THIS FILE IS AUTO-GENERATED FROM spec/tags.json -->"));
        assert!(md.contains("# fspec Feature File Tag Registry"));
        assert!(
            md.ends_with('\n'),
            "TS pushes a trailing empty section before join('\\n'), yielding a single trailing newline"
        );
    }

    #[test]
    fn renders_category_with_required_marker_and_tag_table() {
        let tags = json!({
            "categories": [
                { "name": "Phase Tags", "description": "Phase identification", "required": true,
                  "tags": [ { "name": "@critical", "description": "Critical priority" } ] }
            ]
        });
        let md = generate_tags_md(&tags);
        assert!(md.contains("### Phase Tags (Required)"));
        assert!(md.contains("| `@critical` | Critical priority |"));
    }

    #[test]
    fn renders_statistics_integers_without_decimals() {
        let tags = json!({
            "statistics": {
                "phaseStats": [
                    { "phase": "Phase 1", "total": 5, "complete": 3, "inProgress": 1, "planned": 1 }
                ]
            }
        });
        let md = generate_tags_md(&tags);
        assert!(md.contains("| Phase 1 | 5 | 3 | 1 | 1 |"), "got:\n{md}");
    }

    #[test]
    fn renders_anti_patterns_with_and_without_example() {
        let tags = json!({
            "addingNewTags": {
                "antiPatterns": {
                    "dont": [ { "description": "Overlap", "example": "@x @y" } ],
                    "do": [ { "description": "Reuse" } ]
                }
            }
        });
        let md = generate_tags_md(&tags);
        assert!(md.contains("- Overlap (@x @y)"));
        assert!(md.contains("- Reuse"));
    }
}
