#Requires -Version 5.1
<#
.SYNOPSIS
    fspec Sandbox Setup Script for Windows
    Installs and configures ExitBox for running fspec agents in isolated containers.

.DESCRIPTION
    This script downloads ExitBox, configures it with Node.js support for fspec,
    and sets up the necessary configuration files.

.EXAMPLE
    .\setup-sandbox.ps1

.NOTES
    Requirements:
    - Docker Desktop for Windows
    - PowerShell 5.1 or later
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

# Colors for output
function Write-Info { param($Message) Write-Host "[INFO] " -ForegroundColor Blue -NoNewline; Write-Host $Message }
function Write-Success { param($Message) Write-Host "[OK] " -ForegroundColor Green -NoNewline; Write-Host $Message }
function Write-Warn { param($Message) Write-Host "[WARN] " -ForegroundColor Yellow -NoNewline; Write-Host $Message }
function Write-Error2 { param($Message) Write-Host "[ERROR] " -ForegroundColor Red -NoNewline; Write-Host $Message; exit 1 }

# Check for Docker Desktop
function Test-ContainerRuntime {
    Write-Info "Checking for Docker Desktop..."
    
    try {
        $dockerInfo = docker info 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Success "Docker Desktop is running"
            return $true
        }
    } catch {}
    
    Write-Error2 @"
Docker Desktop not found or not running.

Please install Docker Desktop for Windows:
https://docs.docker.com/desktop/install/windows-install/

After installation, ensure Docker Desktop is running before re-running this script.
"@
}

# Install ExitBox
function Install-ExitBox {
    $installDir = "$env:LOCALAPPDATA\bin"
    $exitboxPath = "$installDir\exitbox.exe"
    
    # Check if already installed
    $existingExitbox = Get-Command exitbox -ErrorAction SilentlyContinue
    if ($existingExitbox) {
        $version = & exitbox --version 2>&1
        Write-Success "ExitBox already installed: $version"
        return
    }
    
    Write-Info "Installing ExitBox..."
    
    # Create install directory
    if (-not (Test-Path $installDir)) {
        New-Item -ItemType Directory -Path $installDir -Force | Out-Null
    }
    
    # Detect architecture
    $arch = if ([System.Environment]::Is64BitOperatingSystem) { "amd64" } else { "386" }
    if ($env:PROCESSOR_ARCHITECTURE -eq "ARM64") { $arch = "arm64" }
    
    $url = "https://github.com/Cloud-Exit/ExitBox/releases/latest/download/exitbox-windows-$arch.exe"
    Write-Info "Downloading from: $url"
    
    try {
        Invoke-WebRequest -Uri $url -OutFile $exitboxPath -UseBasicParsing
    } catch {
        Write-Error2 "Failed to download ExitBox: $_"
    }
    
    # Add to PATH if not already there
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    if ($userPath -notlike "*$installDir*") {
        Write-Info "Adding $installDir to PATH..."
        [Environment]::SetEnvironmentVariable("Path", "$userPath;$installDir", "User")
        $env:Path = "$env:Path;$installDir"
        Write-Warn "PATH updated. You may need to restart your terminal."
    }
    
    Write-Success "ExitBox installed to $exitboxPath"
}

# Configure ExitBox for fspec
function Set-ExitBoxConfig {
    $configDir = "$env:APPDATA\exitbox"
    
    if (-not (Test-Path $configDir)) {
        New-Item -ItemType Directory -Path $configDir -Force | Out-Null
    }
    
    $configFile = "$configDir\config.yaml"
    
    if (Test-Path $configFile) {
        Write-Info "ExitBox config exists. Please ensure 'node' is in your development profiles."
        Write-Info "Run 'exitbox setup' to reconfigure if needed."
    } else {
        Write-Info "Creating ExitBox configuration for fspec..."
        
        $config = @"
# ExitBox configuration for fspec
# Generated by fspec setup-sandbox.ps1
version: 1

roles:
  - fullstack

workspaces:
  active: default
  items:
    - name: default
      development:
        - node
        - base
        - shell

agents:
  claude:
    enabled: true
  codex:
    enabled: false
  opencode:
    enabled: false

settings:
  status_bar: true
  default_workspace: default
  default_flags:
    no_firewall: false
    read_only: false
    no_env: false
    auto_resume: true
"@
        
        $config | Out-File -FilePath $configFile -Encoding UTF8
        Write-Success "Created ExitBox config at $configFile"
    }
    
    # Create allowlist
    $allowlistFile = "$configDir\allowlist.yaml"
    
    if (-not (Test-Path $allowlistFile)) {
        Write-Info "Creating network allowlist..."
        
        $allowlist = @"
# ExitBox network allowlist for fspec
# Generated by fspec setup-sandbox.ps1
version: 1

ai_providers:
  - anthropic.com
  - api.anthropic.com
  - claude.ai
  - openai.com
  - api.openai.com
  - generativelanguage.googleapis.com
  - api.x.ai
  - api.deepseek.com
  - api.mistral.ai
  - api.groq.com
  - openrouter.ai
  - api.together.xyz

development:
  - github.com
  - api.github.com
  - raw.githubusercontent.com
  - npmjs.org
  - registry.npmjs.org
  - yarnpkg.com
  - registry.yarnpkg.com
  - nodejs.org

custom: []
"@
        
        $allowlist | Out-File -FilePath $allowlistFile -Encoding UTF8
        Write-Success "Created allowlist at $allowlistFile"
    }
}

# Create fspec sandbox instructions
function Set-SandboxInstructions {
    $workspaceDir = "$env:APPDATA\exitbox\profiles\global\default\claude\.claude"
    
    if (-not (Test-Path $workspaceDir)) {
        New-Item -ItemType Directory -Path $workspaceDir -Force | Out-Null
    }
    
    $instructionsFile = "$workspaceDir\CLAUDE.md"
    
    if (-not (Test-Path $instructionsFile)) {
        Write-Info "Creating fspec agent instructions..."
        
        $instructions = @"
# fspec Sandbox Environment

You are running inside an ExitBox sandbox container. This provides security isolation
for AI coding agents.

## Available Tools

- **fspec** - Installed globally via npm. Use for ACDD workflow management.
- **Node.js** - Full Node.js runtime with npm available.
- **Git** - Version control (may require --full-git-support flag for push/pull).

## Constraints

- Network access is restricted to allowlisted domains only
- File system access is limited to /workspace (your project)
- Cannot run Docker/Podman commands (nested containers disabled)
- Cannot access host SSH keys unless --full-git-support is used

## fspec Workflow

When the user wants to use ACDD methodology:

1. Check for ``spec/foundation.json`` - if missing, run ``fspec discover-foundation``
2. View the board with ``fspec board``
3. Follow the workflow: BACKLOG -> SPECIFYING -> TESTING -> IMPLEMENTING -> VALIDATING -> DONE
4. Use Example Mapping to gather requirements before writing specs

For quick tasks without formal workflow, just write code directly.
"@
        
        $instructions | Out-File -FilePath $instructionsFile -Encoding UTF8
        Write-Success "Created agent instructions at $instructionsFile"
    }
}

# Main
function Main {
    Write-Host ""
    Write-Host "+=============================================================+" -ForegroundColor Cyan
    Write-Host "|           fspec Sandbox Setup (ExitBox)                     |" -ForegroundColor Cyan
    Write-Host "|                                                             |" -ForegroundColor Cyan
    Write-Host "|   Secure container environment for AI coding agents        |" -ForegroundColor Cyan
    Write-Host "+=============================================================+" -ForegroundColor Cyan
    Write-Host ""
    
    # Step 1: Check container runtime
    Test-ContainerRuntime
    
    # Step 2: Install ExitBox
    Install-ExitBox
    
    # Step 3: Configure for fspec
    Set-ExitBoxConfig
    
    # Step 4: Create sandbox instructions
    Set-SandboxInstructions
    
    Write-Host ""
    Write-Host "=============================================================" -ForegroundColor Green
    Write-Success "Setup complete!"
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor White
    Write-Host ""
    Write-Host "  1. Run the ExitBox setup wizard (recommended):" -ForegroundColor White
    Write-Host "     " -NoNewline; Write-Host "exitbox setup" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  2. Navigate to your project and start a sandboxed agent:" -ForegroundColor White
    Write-Host "     " -NoNewline; Write-Host "cd C:\path\to\your\project" -ForegroundColor Cyan
    Write-Host "     " -NoNewline; Write-Host "exitbox run claude" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  3. Inside the container, install and use fspec:" -ForegroundColor White
    Write-Host "     " -NoNewline; Write-Host "npm install -g @sengac/fspec" -ForegroundColor Cyan
    Write-Host "     " -NoNewline; Write-Host "fspec" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "For more information:" -ForegroundColor White
    Write-Host "  - ExitBox docs: https://github.com/cloud-exit/exitbox"
    Write-Host "  - fspec docs:   https://fspec.dev"
    Write-Host ""
}

Main
