#!/usr/bin/env bash
#
# fspec Sandbox Setup Script
# Installs and configures ExitBox for running fspec agents in isolated containers.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/sengac/fspec/main/scripts/setup-sandbox.sh | bash
#   # or
#   ./scripts/setup-sandbox.sh
#
# Requirements:
#   - Podman (recommended) or Docker
#   - macOS, Linux, or WSL2
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info() { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# Detect platform
detect_platform() {
    local os arch
    os="$(uname -s | tr '[:upper:]' '[:lower:]')"
    arch="$(uname -m)"
    
    case "$arch" in
        x86_64) arch="amd64" ;;
        aarch64|arm64) arch="arm64" ;;
        *) error "Unsupported architecture: $arch" ;;
    esac
    
    case "$os" in
        linux|darwin) ;;
        *) error "Unsupported OS: $os. Use setup-sandbox.ps1 for Windows." ;;
    esac
    
    echo "${os}-${arch}"
}

# Check for container runtime
check_container_runtime() {
    if command -v podman &>/dev/null; then
        if [[ "$(uname -s)" == "Darwin" ]]; then
            if ! podman machine inspect &>/dev/null 2>&1; then
                warn "Podman machine not initialized. Initializing..."
                podman machine init
            fi
            if ! podman info &>/dev/null 2>&1; then
                info "Starting Podman machine..."
                podman machine start
            fi
        fi
        success "Container runtime: Podman"
        return 0
    elif command -v docker &>/dev/null; then
        if docker info &>/dev/null 2>&1; then
            success "Container runtime: Docker"
            return 0
        else
            error "Docker found but not running. Please start Docker Desktop."
        fi
    else
        error "No container runtime found. Please install Podman or Docker first.

For macOS:
    brew install podman && podman machine init && podman machine start

For Ubuntu/Debian:
    sudo apt update && sudo apt install -y podman

For other Linux:
    See https://podman.io/getting-started/installation"
    fi
}

# Install ExitBox
install_exitbox() {
    local platform="$1"
    local install_dir="${HOME}/.local/bin"
    local exitbox_path="${install_dir}/exitbox"
    
    # Check if already installed
    if command -v exitbox &>/dev/null; then
        local current_version
        current_version="$(exitbox --version 2>/dev/null || echo 'unknown')"
        success "ExitBox already installed: $current_version"
        return 0
    fi
    
    info "Installing ExitBox..."
    
    # Create install directory
    mkdir -p "$install_dir"
    
    # Download latest release
    local url="https://github.com/Cloud-Exit/ExitBox/releases/latest/download/exitbox-${platform}"
    info "Downloading from: $url"
    
    if ! curl -fsSL "$url" -o "$exitbox_path"; then
        error "Failed to download ExitBox. Check your internet connection."
    fi
    
    chmod +x "$exitbox_path"
    
    # Add to PATH if not already there
    if [[ ":$PATH:" != *":$install_dir:"* ]]; then
        warn "$install_dir is not in PATH"
        
        local shell_rc=""
        case "$SHELL" in
            */zsh) shell_rc="$HOME/.zshrc" ;;
            */bash) shell_rc="$HOME/.bashrc" ;;
            *) shell_rc="$HOME/.profile" ;;
        esac
        
        if [[ -n "$shell_rc" ]]; then
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$shell_rc"
            info "Added $install_dir to PATH in $shell_rc"
            info "Run: source $shell_rc"
        fi
        
        # Export for current session
        export PATH="$install_dir:$PATH"
    fi
    
    success "ExitBox installed to $exitbox_path"
}

# Configure ExitBox for fspec
configure_exitbox() {
    local config_dir
    if [[ "$(uname -s)" == "Darwin" ]]; then
        config_dir="$HOME/.config/exitbox"
    else
        config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/exitbox"
    fi
    
    mkdir -p "$config_dir"
    
    local config_file="$config_dir/config.yaml"
    
    # Check if config exists
    if [[ -f "$config_file" ]]; then
        info "ExitBox config exists. Checking for Node.js profile..."
        if grep -q "node" "$config_file" 2>/dev/null; then
            success "Node.js profile already configured"
        else
            warn "Adding Node.js profile to existing config..."
            # This is a simple append - user may need to adjust manually
            info "Please run 'exitbox setup' and ensure 'node' is in your development profiles"
        fi
    else
        info "Creating ExitBox configuration for fspec..."
        
        cat > "$config_file" << 'EOF'
# ExitBox configuration for fspec
# Generated by fspec setup-sandbox.sh
version: 1

roles:
  - fullstack

workspaces:
  active: default
  items:
    - name: default
      development:
        - node
        - base
        - shell

agents:
  claude:
    enabled: true
  codex:
    enabled: false
  opencode:
    enabled: false

settings:
  status_bar: true
  default_workspace: default
  default_flags:
    no_firewall: false
    read_only: false
    no_env: false
    auto_resume: true
EOF
        
        success "Created ExitBox config at $config_file"
    fi
    
    # Create allowlist if it doesn't exist
    local allowlist_file="$config_dir/allowlist.yaml"
    if [[ ! -f "$allowlist_file" ]]; then
        info "Creating network allowlist..."
        
        cat > "$allowlist_file" << 'EOF'
# ExitBox network allowlist for fspec
# Generated by fspec setup-sandbox.sh
version: 1

ai_providers:
  - anthropic.com
  - api.anthropic.com
  - claude.ai
  - openai.com
  - api.openai.com
  - generativelanguage.googleapis.com
  - api.x.ai
  - api.deepseek.com
  - api.mistral.ai
  - api.groq.com
  - openrouter.ai
  - api.together.xyz

development:
  - github.com
  - api.github.com
  - raw.githubusercontent.com
  - npmjs.org
  - registry.npmjs.org
  - yarnpkg.com
  - registry.yarnpkg.com
  - nodejs.org

custom: []
EOF
        
        success "Created allowlist at $allowlist_file"
    fi
}

# Create fspec sandbox instructions
create_sandbox_instructions() {
    local config_dir
    if [[ "$(uname -s)" == "Darwin" ]]; then
        config_dir="$HOME/.config/exitbox"
    else
        config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/exitbox"
    fi
    
    local workspace_dir="$config_dir/profiles/global/default/claude"
    mkdir -p "$workspace_dir/.claude"
    
    local instructions_file="$workspace_dir/.claude/CLAUDE.md"
    
    # Only create if doesn't exist (ExitBox also creates one)
    if [[ ! -f "$instructions_file" ]]; then
        info "Creating fspec agent instructions..."
        
        cat > "$instructions_file" << 'EOF'
# fspec Sandbox Environment

You are running inside an ExitBox sandbox container. This provides security isolation
for AI coding agents.

## Available Tools

- **fspec** — Installed globally via npm. Use for ACDD workflow management.
- **Node.js** — Full Node.js runtime with npm available.
- **Git** — Version control (may require --full-git-support flag for push/pull).

## Constraints

- Network access is restricted to allowlisted domains only
- File system access is limited to /workspace (your project)
- Cannot run Docker/Podman commands (nested containers disabled)
- Cannot access host SSH keys unless --full-git-support is used

## fspec Workflow

When the user wants to use ACDD methodology:

1. Check for `spec/foundation.json` — if missing, run `fspec discover-foundation`
2. View the board with `fspec board`
3. Follow the workflow: BACKLOG → SPECIFYING → TESTING → IMPLEMENTING → VALIDATING → DONE
4. Use Example Mapping to gather requirements before writing specs

For quick tasks without formal workflow, just write code directly.
EOF
        
        success "Created agent instructions at $instructions_file"
    fi
}

# Main
main() {
    echo ""
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║           fspec Sandbox Setup (ExitBox)                   ║"
    echo "║                                                           ║"
    echo "║   Secure container environment for AI coding agents       ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo ""
    
    # Step 1: Detect platform
    info "Detecting platform..."
    local platform
    platform="$(detect_platform)"
    success "Platform: $platform"
    
    # Step 2: Check container runtime
    info "Checking container runtime..."
    check_container_runtime
    
    # Step 3: Install ExitBox
    install_exitbox "$platform"
    
    # Step 4: Configure for fspec
    configure_exitbox
    
    # Step 5: Create sandbox instructions
    create_sandbox_instructions
    
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    success "Setup complete!"
    echo ""
    echo "Next steps:"
    echo ""
    echo "  1. Run the ExitBox setup wizard (recommended):"
    echo "     ${BLUE}exitbox setup${NC}"
    echo ""
    echo "  2. Navigate to your project and start a sandboxed agent:"
    echo "     ${BLUE}cd /path/to/your/project${NC}"
    echo "     ${BLUE}exitbox run claude${NC}"
    echo ""
    echo "  3. Inside the container, install and use fspec:"
    echo "     ${BLUE}npm install -g @sengac/fspec${NC}"
    echo "     ${BLUE}fspec${NC}"
    echo ""
    echo "For more information:"
    echo "  - ExitBox docs: https://github.com/cloud-exit/exitbox"
    echo "  - fspec docs:   https://fspec.dev"
    echo ""
}

main "$@"
