#!/bin/bash
# End-to-end test for codelet-napi npm publishing
#
# This script tests the full publish → install → load flow using
# a local Verdaccio registry, without touching the public npm registry.
#
# Usage: ./scripts/test-napi-publish.sh

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
VERDACCIO_PORT=4873
REGISTRY_URL="http://localhost:${VERDACCIO_PORT}"
TEST_DIR="/tmp/codelet-napi-e2e-test-$$"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
NAPI_DIR="${PROJECT_ROOT}/codelet/napi"
VERDACCIO_PID=""

# Cleanup function
cleanup() {
    echo -e "\n${BLUE}Cleaning up...${NC}"

    # Kill Verdaccio if running
    if [ -n "$VERDACCIO_PID" ] && kill -0 "$VERDACCIO_PID" 2>/dev/null; then
        echo "Stopping Verdaccio (PID: $VERDACCIO_PID)"
        kill "$VERDACCIO_PID" 2>/dev/null || true
        wait "$VERDACCIO_PID" 2>/dev/null || true
    fi

    # Also kill any other verdaccio processes we might have started
    pkill -f "verdaccio.*${VERDACCIO_PORT}" 2>/dev/null || true

    # Remove test directory
    if [ -d "$TEST_DIR" ]; then
        echo "Removing test directory: $TEST_DIR"
        rm -rf "$TEST_DIR"
    fi

    # Clean up npm directory in napi folder (generated by prepublish)
    if [ -d "${NAPI_DIR}/npm" ]; then
        echo "Removing generated npm directory"
        rm -rf "${NAPI_DIR}/npm"
    fi

    # Clean up .npmrc file
    if [ -f "${NAPI_DIR}/.npmrc" ]; then
        echo "Removing generated .npmrc"
        rm -f "${NAPI_DIR}/.npmrc"
    fi

    echo -e "${GREEN}Cleanup complete${NC}"
}

# Set up trap for cleanup on exit
trap cleanup EXIT

# Print step header
step() {
    echo -e "\n${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
}

# Check if a command exists
require_cmd() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "${RED}Error: $1 is required but not installed.${NC}"
        exit 1
    fi
}

# Main script
main() {
    echo -e "${GREEN}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║     codelet-napi E2E Publish Test                         ║"
    echo "║     Testing full publish → install → load flow            ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"

    # Check prerequisites
    step "Step 1/8: Checking prerequisites"
    require_cmd node
    require_cmd npm
    require_cmd npx
    echo -e "${GREEN}✓ All prerequisites met${NC}"

    # Check if we're in the right directory
    if [ ! -f "${NAPI_DIR}/package.json" ]; then
        echo -e "${RED}Error: Cannot find codelet/napi/package.json${NC}"
        echo "Please run this script from the fspec project root"
        exit 1
    fi

    # Create test directory
    mkdir -p "$TEST_DIR"

    # Start Verdaccio
    step "Step 2/8: Starting Verdaccio local registry"

    # Kill any existing verdaccio on this port
    pkill -f "verdaccio.*${VERDACCIO_PORT}" 2>/dev/null || true
    sleep 1

    # Create a minimal verdaccio config that allows anonymous publish
    VERDACCIO_CONFIG="${TEST_DIR}/verdaccio-config.yaml"
    VERDACCIO_STORAGE="${TEST_DIR}/storage"
    mkdir -p "$VERDACCIO_STORAGE"

    cat > "$VERDACCIO_CONFIG" << EOF
storage: ${VERDACCIO_STORAGE}
auth:
  htpasswd:
    file: ${TEST_DIR}/htpasswd
    max_users: 100
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@sengac/*':
    access: \$anonymous
    publish: \$anonymous
    unpublish: \$anonymous
  '**':
    access: \$all
    publish: \$anonymous
    proxy: npmjs
server:
  keepAliveTimeout: 60
max_body_size: 100mb
log:
  type: stdout
  format: pretty
  level: error
EOF

    # Create empty htpasswd
    touch "${TEST_DIR}/htpasswd"

    # Start Verdaccio in background
    echo "Starting Verdaccio on port ${VERDACCIO_PORT}..."
    npx --yes verdaccio@latest --config "$VERDACCIO_CONFIG" --listen ${VERDACCIO_PORT} > "${TEST_DIR}/verdaccio.log" 2>&1 &
    VERDACCIO_PID=$!

    # Wait for Verdaccio to start
    echo "Waiting for Verdaccio to be ready..."
    for i in {1..60}; do
        if curl -s "${REGISTRY_URL}/-/ping" > /dev/null 2>&1; then
            echo -e "${GREEN}✓ Verdaccio is ready (took ${i}s)${NC}"
            break
        fi
        if [ $i -eq 60 ]; then
            echo -e "${RED}Error: Verdaccio failed to start${NC}"
            echo "Log output:"
            cat "${TEST_DIR}/verdaccio.log"
            exit 1
        fi
        sleep 1
    done

    # Configure npm for local registry
    step "Step 3/8: Configuring npm for local registry"
    echo -e "${GREEN}✓ Using anonymous publish (no auth required)${NC}"

    # Build the NAPI module
    step "Step 4/8: Building codelet-napi"
    cd "$NAPI_DIR"

    echo "Installing dependencies..."
    npm ci --silent

    echo "Building native module..."
    npm run build

    NODE_FILES=$(ls -1 *.node 2>/dev/null | wc -l)
    if [ "$NODE_FILES" -eq 0 ]; then
        echo -e "${RED}Error: No .node file generated${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Native module built successfully${NC}"
    ls -la *.node

    # Generate platform packages for available binaries only
    step "Step 5/8: Generating platform packages"

    # Detect available .node files
    echo "Detecting available platform binaries..."
    NODE_FILES=(*.node)
    if [ ${#NODE_FILES[@]} -eq 0 ] || [ ! -f "${NODE_FILES[0]}" ]; then
        echo -e "${RED}Error: No .node files found${NC}"
        exit 1
    fi

    echo -e "Found ${#NODE_FILES[@]} platform binary:"
    for f in "${NODE_FILES[@]}"; do
        echo "  - $f"
    done

    # Get package version
    PKG_VERSION=$(node -p "require('./package.json').version")
    echo -e "\nPackage version: ${PKG_VERSION}"

    # Create npm directory for platform packages
    mkdir -p npm

    # Map .node filename to npm package directory name
    # codelet-napi.darwin-arm64.node -> darwin-arm64
    # codelet-napi.darwin-x64.node -> darwin-x64
    # etc.
    PLATFORM_COUNT=0
    for node_file in "${NODE_FILES[@]}"; do
        # Extract platform from filename: codelet-napi.PLATFORM.node
        PLATFORM=$(echo "$node_file" | sed 's/codelet-napi\.\(.*\)\.node/\1/')

        # Map Rust target to npm package name
        case "$PLATFORM" in
            "darwin-arm64")
                NPM_PLATFORM="darwin-arm64"
                NPM_OS="darwin"
                NPM_CPU="arm64"
                ;;
            "darwin-x64")
                NPM_PLATFORM="darwin-x64"
                NPM_OS="darwin"
                NPM_CPU="x64"
                ;;
            "linux-arm64-gnu")
                NPM_PLATFORM="linux-arm64-gnu"
                NPM_OS="linux"
                NPM_CPU="arm64"
                ;;
            "linux-x64-gnu")
                NPM_PLATFORM="linux-x64-gnu"
                NPM_OS="linux"
                NPM_CPU="x64"
                ;;
            "win32-arm64-msvc")
                NPM_PLATFORM="win32-arm64-msvc"
                NPM_OS="win32"
                NPM_CPU="arm64"
                ;;
            "win32-x64-msvc")
                NPM_PLATFORM="win32-x64-msvc"
                NPM_OS="win32"
                NPM_CPU="x64"
                ;;
            *)
                echo -e "${YELLOW}Warning: Unknown platform ${PLATFORM}, skipping${NC}"
                continue
                ;;
        esac

        echo -e "\nCreating platform package for ${NPM_PLATFORM}..."
        mkdir -p "npm/${NPM_PLATFORM}"

        # Create platform-specific package.json
        cat > "npm/${NPM_PLATFORM}/package.json" << PKGEOF
{
  "name": "@sengac/codelet-napi-${NPM_PLATFORM}",
  "version": "${PKG_VERSION}",
  "os": ["${NPM_OS}"],
  "cpu": ["${NPM_CPU}"],
  "main": "codelet-napi.${PLATFORM}.node",
  "files": ["codelet-napi.${PLATFORM}.node"],
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/sengac/fspec"
  }
}
PKGEOF

        # Copy the .node file
        cp "$node_file" "npm/${NPM_PLATFORM}/"
        PLATFORM_COUNT=$((PLATFORM_COUNT + 1))
        echo -e "${GREEN}✓ Created @sengac/codelet-napi-${NPM_PLATFORM}${NC}"
    done

    echo -e "\nGenerated platform packages:"
    ls -la npm/

    echo -e "${GREEN}✓ Generated ${PLATFORM_COUNT} platform package(s)${NC}"
    echo -e "${YELLOW}Note: Full CI builds all 6 platforms. Local test has ${PLATFORM_COUNT}.${NC}"

    # Publish to local registry
    step "Step 6/8: Publishing packages to local registry"

    # Create .npmrc to set registry and fake auth token for this directory
    # Verdaccio with $anonymous publish accepts any auth token
    cat > .npmrc << NPMRCEOF
registry=${REGISTRY_URL}
//localhost:${VERDACCIO_PORT}/:_authToken=fake-test-token
NPMRCEOF

    echo "Publishing main package (@sengac/codelet-napi)..."
    # Use --ignore-scripts since we already generated platform packages manually
    npm publish --registry "${REGISTRY_URL}" --access public --ignore-scripts 2>&1 || {
        echo -e "${RED}Failed to publish main package${NC}"
        exit 1
    }
    echo -e "${GREEN}✓ Main package published${NC}"

    echo -e "\nPublishing platform packages..."
    PUBLISHED_COUNT=0
    FAILED_PACKAGES=""

    for pkg in npm/*/; do
        if [ -d "$pkg" ]; then
            PKG_NAME=$(basename "$pkg")
            echo -n "  Publishing @sengac/codelet-napi-${PKG_NAME}... "
            # Copy .npmrc to platform package directory for auth
            cp .npmrc "$pkg/.npmrc"
            cd "$pkg"
            if npm publish --registry "${REGISTRY_URL}" --access public 2>&1; then
                echo -e "${GREEN}✓${NC}"
                PUBLISHED_COUNT=$((PUBLISHED_COUNT + 1))
            else
                echo -e "${RED}✗${NC}"
                FAILED_PACKAGES="${FAILED_PACKAGES} ${PKG_NAME}"
            fi
            cd "${NAPI_DIR}"
        fi
    done

    echo -e "\n${GREEN}✓ Published ${PUBLISHED_COUNT}/${PLATFORM_COUNT} platform packages${NC}"

    if [ -n "$FAILED_PACKAGES" ]; then
        echo -e "${YELLOW}Warning: Failed to publish:${FAILED_PACKAGES}${NC}"
    fi

    # List what's in the registry
    echo -e "\nPackages in local registry:"
    curl -s "${REGISTRY_URL}/-/all" 2>/dev/null | grep -o '"name":"[^"]*"' | head -20 || echo "(could not list)"

    # Test installation
    step "Step 7/8: Testing installation from local registry"

    INSTALL_TEST_DIR="${TEST_DIR}/install-test"
    mkdir -p "$INSTALL_TEST_DIR"
    cd "$INSTALL_TEST_DIR"

    echo '{"name":"test-install","version":"1.0.0","type":"commonjs"}' > package.json

    echo "Installing @sengac/codelet-napi from local registry..."
    npm install @sengac/codelet-napi --registry "${REGISTRY_URL}" 2>&1

    if [ ! -d "node_modules/@sengac/codelet-napi" ]; then
        echo -e "${RED}Error: Package not installed correctly${NC}"
        ls -la node_modules/ 2>/dev/null || echo "node_modules not found"
        exit 1
    fi
    echo -e "${GREEN}✓ Package installed successfully${NC}"

    echo -e "\nInstalled package structure:"
    ls -la node_modules/@sengac/

    # Check for platform-specific package
    echo -e "\nPlatform binary check:"
    find node_modules/@sengac -name "*.node" -type f 2>/dev/null || echo "No .node files found (might be in optional deps)"

    # Verify the module loads
    step "Step 8/8: Verifying module loads correctly"

    echo "Testing module import..."
    node -e "
const path = require('path');
try {
    const pkg = require('@sengac/codelet-napi');
    console.log('Package exports:', Object.keys(pkg));

    if (pkg.CodeletSession) {
        console.log('✓ CodeletSession class found');
        console.log('  Type:', typeof pkg.CodeletSession);
    } else {
        console.log('Available exports:', pkg);
    }
    console.log('✓ Module loaded successfully');
} catch (err) {
    console.error('✗ Failed to load module:', err.message);
    console.error('Stack:', err.stack);
    process.exit(1);
}
"

    LOAD_RESULT=$?

    if [ $LOAD_RESULT -eq 0 ]; then
        echo -e "\n${GREEN}════════════════════════════════════════════════════════════${NC}"
        echo -e "${GREEN}  ✓ E2E TEST PASSED${NC}"
        echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
        echo -e "\nSummary:"
        echo -e "  - Main package: ${GREEN}published${NC}"
        echo -e "  - Platform packages: ${GREEN}${PUBLISHED_COUNT}/${PLATFORM_COUNT} published${NC}"
        echo -e "  - Installation: ${GREEN}success${NC}"
        echo -e "  - Module load: ${GREEN}success${NC}"
        echo -e "\nYou can safely push a version tag to publish to npm.\n"
    else
        echo -e "\n${RED}════════════════════════════════════════════════════════════${NC}"
        echo -e "${RED}  ✗ E2E TEST FAILED${NC}"
        echo -e "${RED}════════════════════════════════════════════════════════════${NC}"
        exit 1
    fi
}

# Run main function
main "$@"
